### ISSUE TITLE
Test fails for gcc v2.95.3 on Haiku

### ISSUE THREAD

**Issue by Begasus** [libexpat/libexpat#113]
Latest version for expat 2.2.3 buils on all architectures and the test is ok with gcc v5.4.0 (x86, and x86_64), for x86_gcc2 I'm getting the next error:

In file included from /sources/expat-2.2.3/tests/runtestspp.cpp:6:
/sources/expat-2.2.3/tests/runtests.c:154: parse error before `__attribute__'
/sources/expat-2.2.3/tests/runtests.c: In function `void dummy_xdecl_handler(...)':
/sources/expat-2.2.3/tests/runtests.c:161: parse error before `__attribute__'
/sources/expat-2.2.3/tests/runtests.c:161: cannot declare static function inside another function

I 'think' it should be an easy fix, but as I'm not a developer I'm not able to solve it myself.

**Comment by hartwork** [comment]
Hi,

GCC 2.95.3 is 16 or so years old and GCC 5 seems to be working fine according to your comment at https://github.com/haikuports/haikuports/pull/1525#issuecomment-320417840. I would consider a patch if it doesn't litter up the code too much but you're saying you are not going to make some and I consider GCC 2.95.3 unsupported and not a priority so I think it's reasonable to close this ticket as unsupported/wontfix. I'm happy to patch for GCC 5.x.

Best, Sebastian

**Comment by Begasus** [comment]
You are right that it's an old compiler, and it's only there to provide backwards compatibility to BeOS apps, test are ok for the gcc5 compiler, thanks for the fix on the poor entropy stuff :+1:
