### ISSUE TITLE
It would be nice if files included license information that licensecheck, etc. could parse

### ISSUE THREAD

**Issue by dominiccooney** [libexpat/libexpat#116]
When I run [licensecheck](https://metacpan.org/pod/App::Licensecheck) on expat files it does not grok most of them. It would be splendid if header and implementation files mentioned which license they used in a way that could be extracted by scripts like that.

**Comment by hartwork** [comment]
Hi!

So it's about all `.c` and `.h` files? Does licensecheck identify `loadlibrary.c` correctly? That one has the full license text in its header.

**Comment by hartwork** [comment]
I have now inlined license information into code headers and also mention that it's the MIT license, see a704c940a4247f6e7da6ba1e2fa66981916fa728. My distro doesn't come with [licensecheck](https://metacpan.org/pod/App::Licensecheck) packaged and I'm not at home with Perl so I rely on you to let me know how well licensecheck likes the new headers. Please re-open this ticket if you need anything more on this topic.
