### ISSUE TITLE
Please include Windows files (*.sln, etc.) in source only distro

### ISSUE THREAD

**Issue by sldr** [libexpat/libexpat#117]
I am happy that you have a binary distro for Windows and it even includes source (*.sln, *.vcxproj, etc.). Please don't stop doing this because I am sure some Windows users just want the binaries from a trusted source.

We however are building for serval different platforms (Unix, Linux, Windows) and it means that I can not just download source into our repository and it work. I do realize I can use GitHub to select R_2_2_3 tag and download the zip (and that is what I have done).

It would be nice for your users like me to just get the standard source distro and have it all. If you later start GPG signing your distros this is really going to become an issue for some users.

Just my $0.02 worth... ;-)

Thanks,
SLDR
(Stephen L. De Rudder)

**Comment by hartwork** [comment]
I'm happy to include Windows source files missing from the source tarball in the future. I'm playing with a migration to GNU Automake (#65) right now, let me get that done, first.

**Comment by hartwork** [comment]
@sldr this is the list of files currently planned to add to future source tarballs:
```
examples/elements.vcxproj
examples/elements.vcxproj.filters
examples/outline.vcxproj
examples/outline.vcxproj.filters
expat.sln
expat.spec
gennmtab/gennmtab.c
lib/expat_static.vcxproj
lib/expat_static.vcxproj.filters
lib/expat.vcxproj
lib/expat.vcxproj.filters
lib/expatw_static.vcxproj
lib/expatw_static.vcxproj.filters
lib/expatw.vcxproj
lib/expatw.vcxproj.filters
tests/benchmark/benchmark.sln
tests/benchmark/benchmark.vcxproj
tests/runtests.sln
tests/runtests.vcxproj
tests/runtests.vcxproj.filters
tests/xmltest.log.expected
xmlwf/xmlwf.vcxproj
xmlwf/xmlwf.vcxproj.filters
```
Does that match what you had in mind?

It's a subset of what I got from this command:
```
diff -u <(tar tf expat-2.2.3.tar.bz2 | sort | sed 's,^expat-2.2.3/,,') <(git ls-files | sort) | grep '^+[^+]' | sed 's,^+,,'
```

PS: If you want to help with review of the Automake migration, the pull request is #118.

**Comment by sldr** [comment]
Looks great! The only thing I saw missing was the libexpat.def and libexpatw.def but for some reason those do go out in tar.bz distro.

Thanks for the quick response!

I will be looking forward to the next version.

SLDR

PS: I would help review the Automake migration but I am not that much of a Linux/Unix guy and probably only be able to give you $-0.02 worth of help. ;-)

**Comment by hartwork** [comment]
I have added the Visual Studio files and the missing `tests/xmltest.log.expected` nw, see commits above. I'm closing this ticket as fixed, please re-open if anything more is needed.

For the record, here's the updated list of files that are in Git (in folder `expat`) that are still not included in source tarballs:
```
# diff -u <(tar tf expat-2.2.3.tar.bz2 | sort | sed 's,^expat-2.2.3/,,') <(git ls-files | sort) | grep '^+[^+]' | sed 's,^+,,'
buildconf.sh
clean_coverage.sh
conftools/.gitignore
coverage.sh
doc/.gitignore
examples/.gitignore
expat.spec
gennmtab/gennmtab.c
gennmtab/.gitignore
.gitignore
lib/.gitignore
memory-sanitizer-blacklist.txt
qa.sh
tests/benchmark/.gitignore
tests/.gitignore
win32/.gitignore
xmlwf/.gitignore
```

**Comment by hartwork** [comment]
@sldr FYI 2.2.4 has been released and includes these files.
