### ISSUE TITLE
__func__ warnings from GCC

### ISSUE THREAD

**Issue by RMJ10** [libexpat/libexpat#12]
I seem to have an odd case for use or suppression of warnings about __func__

I'm running Linux Mint 18 with GCC 5.4.0, and built libexpat with the standard `./buildconf.sh` and vanilla `./configure`.  If I run expat's XML tests (`make check`), I am buried under warnings that ISO C 90 does not support __func__, which is fair enough since it doesn't appear until ISO C 99.

It appears that what is happening is that this version of GCC is taking a very strict interpretation of the C90 standard.  Specifically, __STDC_VERSION__ isn't in C90 and therefore isn't supplied by the compiler, so the checks in minicheck.h that would remove __func__ are passed over.  Presumably those checks come from configure.ac somehow; I'm afraid libtool is just fell sorcery to me!

I can patch around this easily enough for myself, and it doesn't happen on my other Linux Mint machine.  It's not a priority as far as I'm concerned.

**Comment by hartwork** [comment]
I can reproduce it with GCC 5.4.0. Thanks for the report!

**Comment by hartwork** [comment]
Should be fixed. Please report back if otherwise.
