### ISSUE TITLE
About the option of dependency tracking

### ISSUE THREAD

**Issue by heagoo** [libexpat/libexpat#134]
I see there are 2 options when run "./configure --help":
  --enable-dependency-tracking
                          do not reject slow dependency extractors
  --disable-dependency-tracking
                          speeds up one-time build

However, the content of generated expat_config.h keeps unchanged when add either options.
Does such options still work?

**Comment by heagoo** [comment]
Is this option only for tests?

**Comment by hartwork** [comment]
Hi!

These options are not specific to Expat but rather to GNU Automake, see https://www.gnu.org/software/automake/manual/html_node/Dependency-Tracking.html. For short, most users can ignore them, for one time builds or packaging, `--disable-dependency-tracking` may speed things up a little. What's your context?

**Comment by heagoo** [comment]
Thanks for the answer 👍 (I am not familiar with Automake, thus mistakenly take it as the option of Expat)
And, I am trying to find out the optimized configuration for Android system. Do you have any suggestions for that?

**Comment by hartwork** [comment]
Hi!
Optimized configuration for Android is rather unspecific. If you really need me for that, please grab my number from `whois hartwork.org | fgrep "Admin Phone:"` and call me some time >=20:00 UTC+2 for efficient use of time, please.

**Comment by heagoo** [comment]
I use the default setting, seems the perf is good.
Anyway, thanks for your kindness.
