### ISSUE TITLE
Certain UTF-8 characters get rejected by the parser as INVALID_TOKEN

### ISSUE THREAD

**Issue by kookoodan** [libexpat/libexpat#136]
I've noticed that having certain UTF-8 characters into an XML leads to an XML_ERROR_INVALID_TOKEN parsing error.
The 3 byte UTF-8 character is: 0xEF, 0xBF, 0xBF. Taking a valid XML (outline_success.txt) and appending the 3 byte UTF-8 character to the body (thus becoming outline_invalid_token.txt), will make XML_Parse fail and the error will be XML_ERROR_INVALID_TOKEN.
Other 3 byte UTF-8 characters (printable and non-printable) work fine (outline_success_other_3_byte_utf_8_1.txt and outline_success_other_3_byte_utf_8_2.txt).

Issue can be reproduced easily using the outline example and sample files attached 

`outline.exe < outline_invalid_token.txt`

[outline_invalid_token.txt](https://github.com/libexpat/libexpat/files/1260381/outline_invalid_token.txt)
[outline_success.txt](https://github.com/libexpat/libexpat/files/1260382/outline_success.txt)
[outline_success_other_3_byte_utf_8_1.txt](https://github.com/libexpat/libexpat/files/1260403/outline_success_other_3_byte_utf_8_1.txt)
[outline_success_other_3_byte_utf_8_2.txt](https://github.com/libexpat/libexpat/files/1260404/outline_success_other_3_byte_utf_8_2.txt)

**Comment by RMJ10** [comment]
`0xEF 0xBF 0xBF` is `U+FFFF`, which is guaranteed never to be a Unicode character.  By definition, any text containing it is not correctly encoded.

**Comment by hartwork** [comment]
Hi!

I would like to support what @RMJ10 said by the authoritative reference, the XML 1.0 Standard:
> any Unicode character, excluding the surrogate blocks, FFFE, and FFFF.
(from https://www.w3.org/TR/REC-xml/#charsets)

I'm therefore closing as invalid.
