### ISSUE TITLE
Reducing number of build systems

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#14]
Hi!

Before I go on suggesting removal of certain things myself: Of the current build systems below, what do _you_ think ..
* can be dropped, or
* should be kept and why?

Thanks for your participation!

# Build Systems

## Autoconf
* `expat/buildconf.sh`
* `expat/configure.ac`
* `expat/conftools/*`
* `expat/doc/Makefile`
* `expat/expat.pc.in`
* `expat/Makefile.in`

## CMake
* `expat/CMake.README`
* `expat/CMakeLists.txt`
* `expat/ConfigureChecks.cmake`
* `expat/doc/Makefile`
* `expat/expat_config.h.cmake`
* `expat/expat.pc.in`

## AmigaOS build system (and wrapping code?!)
* `expat/amiga/*`

## Borland
* `expat/bcb5/elements.bpr`
* `expat/bcb5/elements.mak`
* `expat/bcb5/expat.bpr`
* `expat/bcb5/expat.mak`
* `expat/bcb5/expat_static.bpr`
* `expat/bcb5/expat_static.mak`
* `expat/bcb5/expatw.bpr`
* `expat/bcb5/expatw.mak`
* `expat/bcb5/expatw_static.bpr`
* `expat/bcb5/expatw_static.mak`
* `expat/bcb5/outline.bpr`
* `expat/bcb5/outline.mak`
* `expat/bcb5/xmlwf.bpr`
* `expat/bcb5/xmlwf.mak`

## Visual Studio 6.0
* `expat/examples/elements.dsp`
* `expat/examples/outline.dsp`
* `expat/expat.dsw`
* `expat/gennmtab/gennmtab.dsp`
* `expat/lib/expat.dsp`
* `expat/lib/expat_static.dsp`
* `expat/lib/expatw.dsp`
* `expat/lib/expatw_static.dsp`
* `expat/tests/benchmark/benchmark.dsp`
* `expat/tests/runtests.dsp`
* `expat/xmlwf/xmlwf.dsp`

## Visual Studio 2013 (auto-upgradable to 2015)
* `expat/examples/elements.vcxproj`
* `expat/examples/outline.vcxproj`
* `expat/expat.sln`
* `expat/lib/expat_static.vcxproj`
* `expat/lib/expat.vcxproj`
* `expat/lib/expatw_static.vcxproj`
* `expat/lib/expatw.vcxproj`
* `expat/tests/benchmark/benchmark.vcxproj`
* `expat/tests/runtests.vcxproj`
* `expat/xmlwf/xmlwf.vcxproj`

## OpenVMS build system
* `expat/vms/`

## Open Watcom OS2/DOS/Win32 build system
* `expat/watcom/`

# Packaging

## Inno Setup installer
* `expat/win32/expat.iss`

## RPM packaging
* `expat/expat.spec`

**Comment by hartwork** [comment]
I would like to explicitly (but by no means exclusively) invite:
@freddrake, @kwaclaw, @tbeu, @catalinr

**Comment by catalinr** [comment]
FWIW `libexpat` is used by `wxWidgets` which still supports building with Visual Studio 2013, but it is not using libexpat build system. So removing VS2013 build files would not change anything, but I think maintaining compatibility with it would be welcomed. I'll add @vadz to this one.

**Comment by bnason-nf** [comment]
@hartwork: we use cmake, but because we cross compile to some platforms that don't work well with the cmake configuration mechanisms, we replace the CMakeLists.txt file provided by expat with an extremely simple one:

```
add_library(expat lib/ascii.h lib/asciitab.h lib/expat.h lib/expat_config.h lib/expat_external.h lib/iasciitab.h lib/internal.h lib/latin1tab.h lib/nametab.h lib/utf8tab.h lib/xmlparse.c lib/xmlrole.c lib/xmlrole.h lib/xmltok.c lib/xmltok.h lib/xmltok_impl.c lib/xmltok_impl.h lib/xmltok_ns.c)
target_include_directories(expat INTERFACE lib)
target_include_directories(expat PRIVATE lib)
```

**Comment by vadz** [comment]
Indeed, wxWidgets doesn't use expat build system, so we don't really care, but, if you're taking any requests, by chance. it would be nice to have a file with the list of expat sources in some very simple format (i.e. just a list of the files with one file per line) as we could reuse it from our build system then.

**Comment by kwaclaw** [comment]
From a Windows point of view the Visual Studio 6.0 build could be dropped,
IMO.

**Comment by freddrake** [comment]
On Tue, Mar 14, 2017 at 7:06 PM, Sebastian Pipping <notifications@github.com
> wrote:

> Before I go on suggesting removal of certain things myself: Of the current
> build systems below, what do *you* think ..
>
>    - can be dropped, or
>    - should be kept and why?
>
> ...

>
>
> Inno Setup installer
>
>    - expat/win32/expat.iss
>
>
The presence of this is probably my fault, IIRC.  At one point, I was told
that Windows users & developers expect installers, and someone familiar
with Inno Setup was available to help me get this set up.

I've since heard that's not really an expectation for things like
libraries, where a ZIP might be preferable for developers (and applications
are going to bundle a copy).

If no one finds the binary installer helpful, I'm all for tossing it.


  -Fred

-- 
Fred L. Drake, Jr.    <fred at fdrake.net>
"A storm broke loose in my mind."  --Albert Einstein

**Comment by hartwork** [comment]
Thanks everyone for your comments so far!

Let me propose these more for dropping myself now:
* AmigaOS
* Borland
* OpenVMS
* Open Watcom

Dropping would mean in practice:
* Dedicated Git commits that can be reverted if need arises
* A note in the change log with invitation to step up as a responsive maintainer for resurrection of build system X

While I actually like Autoconf to some extent, I wonder if and when to drop the Autoconf build system.  Is our CMake one missing anything, still? Soname versioning is in there.

Any thoughts?


@kwaclaw, do you like installer or zip file better for providing Windows binaries?
I think you used the Visual Studio 2013 build files creating the binaries for the last release. Do VS2k3 files work better for you than CMake in the process of creating binaries on Windows?

@bnason-nf, if the current CMake build system does not yet work for you, that's probably a bug.
Please open a bug report with details on what the trouble is.

@vadz, that list would be all *.c and *.h files?
Please open a new bug with details so we can start working on that.

Best, Sebastian

**Comment by RMJ10** [comment]
@hartwork, the CMake build doesn't have support for the benchmarks, XML test downloads and coverage tests.  The qa.sh script definitely assumes it will have support from make to prepare for the coverage tests, and CMake doesn't supply that.

**Comment by hartwork** [comment]
Good point!

**Comment by hartwork** [comment]
Most work probably done now, see commits above.
Keeping open for now due to [open points above](https://github.com/libexpat/libexpat/issues/14#issuecomment-286730494).
