### ISSUE TITLE
Binding memory leak when duplicate attributes error

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#142]
**Original bug report at https://sourceforge.net/p/expat/bugs/521/**

When parsing the following xaml:

~~~~~~
<ContentControl
   xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
   Content="1" Content="2"/>
~~~~~~

The `XML_ERROR_DUPLICATE_ATTRIBUTE` error is generated by `storeAtts()` function, called from switch case `XML_TOK_EMPTY_ELEMENT_WITH_ATTS` in `doContent()`.

A `BINDING*` is created inside `storeAtts`, and that binding is never freed.

I think that this code:

~~~~~~
result = storeAtts(parser, enc, s, &name, &bindings);
if (result)
  return result;
~~~~~~

Should be modified to:

~~~~~~
result = storeAtts(parser, enc, s, &name, &bindings);
if (result) {
  while (bindings) {
    BINDING *b = bindings;
    if (endNamespaceDeclHandler)
      endNamespaceDeclHandler(handlerArg, b->prefix->name);
    bindings = bindings->nextTagBinding;
    b->nextTagBinding = freeBindingList;
    freeBindingList = b;
    b->prefix->binding = b->prevPrefixBinding;
  }
  return result;
}
~~~~~~

**Comment by hartwork** [comment]
That very cases was fixed by b47dbc9745932c160893d433220e462bd605f8cd but we still have very similar code for cases `XML_TOK_START_TAG_NO_ATTS` and `XML_TOK_START_TAG_WITH_ATTS` that neds a closer look as well:

```
    case XML_TOK_START_TAG_NO_ATTS:
      /* fall through */
    case XML_TOK_START_TAG_WITH_ATTS:
[..]
        result = storeAtts(parser, enc, s, &(tag->name), &(tag->bindings));
        if (result)
          return result;
[..]
```

**Comment by RMJ10** [comment]
I believe the `XML_TOK_START_TAG_NO_ATTS` and `XML_TOK_START_TAG_WITH_ATTS` cases are safe.  Unlike the empty element cases, the bindings are stored on `tag` rather than a stack variable, and `tag` has already been added to the parser's `m_tagStack` list by the time `storeAtts()` is called.  When the parser is freed, the tags and their bindings are also freed.

**Comment by kkkunche** [comment]
Could you please review the pull request
https://github.com/libexpat/libexpat/pull/267

**Comment by hartwork** [comment]
In light of #267 I just did:

- Verify that the test suite does line-cover all of …
```
        result = storeAtts(parser, enc, s, &(tag->name), &(tag->bindings));
        if (result)
          return result;
```
- That some of these cases have a non-`NULL` value in `tag->bindings` at the time of `return result;`
- That the test suite passes with both AddressSanitizer and LeakSanatizer enabled
- That LeakSanatizer does work in my setup, e.g. it did detect leaks for an extra `malloc(10)` at that place
- Tried to follow @RMJ10's comment above, in code. See the code below for where the tag stack and binding are removed.

After that, I believe that #267 is not needed and that #142 here can be closed.

```c
XML_Bool XMLCALL
XML_ParserReset(XML_Parser parser, const XML_Char *encodingName)
{
  [..]
  /* move m_tagStack to m_freeTagList */
  tStk = parser->m_tagStack;
  while (tStk) {
    TAG *tag = tStk;
    tStk = tStk->parent;
    tag->parent = parser->m_freeTagList;
    moveToFreeBindingList(parser, tag->bindings);
    tag->bindings = NULL;
    parser->m_freeTagList = tag;
  }
  [..]
}
```

```c
void XMLCALL
XML_ParserFree(XML_Parser parser)
{
  TAG *tagList;
  [..]
  /* free m_tagStack and m_freeTagList */
  tagList = parser->m_tagStack;
  for (;;) {
    TAG *p;
    [..]
    p = tagList;
    tagList = tagList->parent;
    FREE(parser, p->buf);
    destroyBindings(p->bindings, parser);
    FREE(parser, p);
  }
  [..]
}
```

So I vote for closing this ticket.

**Comment by hartwork** [comment]
Closing, please re-open if you see need.

**Comment by kkkunche** [comment]
My apologies for the late reply. I am on leave so couldn't reply.
The main reason for adding the code is for more safer checks for memory leaks.  I also checked the #142 comments that the elements cannot be NULL. 
I am still thinking why tag->bindings cannot be NULL.

typedef struct binding {
  struct prefix *prefix;
  struct binding *nextTagBinding;
  struct binding *prevPrefixBinding;
  const struct attribute_id *attId;
  XML_Char *uri;
  int uriLen;
  int uriAlloc;
} BINDING;

**Comment by hartwork** [comment]
Hi! I don't follow — could you elaborate in more detail? Ideally, there would be a test case in code or crafted XML file to trigger and demonstrate the memory leak.

**Comment by RMJ10** [comment]
To construct an example you will need an allocator that fails at a given point, something like `duff_allocator()` in the file expat/tests/runtests.c.  I'm pretty confident that I'm right, though, and there isn't a leak here.

**Comment by kkkunche** [comment]
Yes your right. Thanks.
