### ISSUE TITLE
AppVeyor: Compile with XML_UNICODE_WCHAR_T defined and without

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#147]
Currently, we compile _without_ `XML_UNICODE_WCHAR_T` (and `XML_UNICODE`) defined on AppVeyor, only. It would be cool to have that covered, as well.

**Comment by hartwork** [comment]
@pepone if you find time, your help would be welcome.

**Comment by pepone** [comment]
@hartwork  what is the idea here to have separate builds with this env, or is it a macro? what combinations do we need ?

**Comment by hartwork** [comment]
Hi! It's two macros:
* `XML_UNICODE` switches internal storage from UTF-8/`char` to UTF-16/`unsigned short`
* `XML_UNICODE_WCHAR_T` requires `XML_UNICODE` but uses `wchar_t` rather than `unsigned short` (which only works with 2-byte `wchar_t`, i.e. on Windows/MinGW but not Linux)

For GCC you would use `CPPFLAGS='-DXML_UNICODE -DXML_UNICODE_WCHAR_T'`.

So two cases:
* a) Both macros `XML_UNICODE` and `XML_UNICODE_WCHAR_T` defined (without any perticular value)
* b) Neither defined.

**Comment by pepone** [comment]
@hartwork I fixed that on my fork, but adding -DXML_UNICODE -DXML_UNICODE_WCHAR_T breaks xmlwf windows builds.

See https://ci.appveyor.com/project/pepone/libexpat/build/job/s1ku53amp3dq0ggh
