### ISSUE TITLE
XInclude

### ISSUE THREAD

**Issue by vschhabra** [libexpat/libexpat#148]
We are looking to use the XInclude mechanism in our parser based upon the expat library. Does anyone have any examples on how to do it with expat? Is there any existing implementation out there? Any help would be greatly appreciated.

**Comment by hartwork** [comment]
Hi @vschhabra,

to my best knowledge one would do that using a start/element handler that creates a new Expat parser.
I have created a ticket for the website to add documentation on that question for the next person asking at https://github.com/libexpat/libexpat.github.io/issues/10 now.

I'm closing this ticket now. If you need support beyond that from me, please extract my phone number from some whois record and give me a call >=20:00 UTC+2 some time, so we don't waste time with mail ping-pong. Thanks.

Best, Sebastian
