### ISSUE TITLE
installlib target not available any more

### ISSUE THREAD

**Issue by FrankLorenz** [libexpat/libexpat#149]
"make installlib" does not work any more - the target is not available in Makefile.in in 2.2.4

This target is used by buildroot to install only the library to the target. When I tried to switch from 2.2.2 to 2.2.4 to fix the "block on too few entropy during boot" issue buildroot stopped because of this.

Is there any alternative way to install only the library, or has the "installib" target added again to the make configuration?

**Comment by FrankLorenz** [comment]
O.k., just figured out that this is not an issue for latest buildroot anymore - they adapted their buildsystem in some way to circumvent it I think:
https://github.com/buildroot/buildroot/blob/master/package/expat/expat.mk

**Comment by hartwork** [comment]
Let me add the related commit for future readers of this ticket: https://github.com/buildroot/buildroot/commit/bfa4428d78c67fade7160f0bf0dd358a0bc1ba44
