### ISSUE TITLE
OSX docbook2x-man is docbook2man

### ISSUE THREAD

**Issue by stephengroat** [libexpat/libexpat#153]
after installing `docbook2x` from `brew`, the `docbook2x-man` binary cannot be found during the build process. after looking, the binary is named `docbook2man` (no `x-`)

i'm not sure how the makefiles do OS dectection, otherwise I could fix with something like an `if DARWIN` in https://github.com/libexpat/libexpat/blob/master/expat/doc/doc.mk

related to #152

**Comment by hartwork** [comment]
Hi!

I'll braindump a few notes on how I think this should be approached if someone finds time to fix this before I do. I should mention this affects two build systems: Autotools and CMake.

* Autotools: Add command auto-detection to `expat/configure.ac`, allow custom command, add `--disable-doc` to continue supporting a build without it
* Autotools: Pass/set `DOCBOOK_TO_MAN` to `$(MAKE) -f $(srcdir)/doc.mk xmlwf.1 srcdir=$(srcdir)` in  `expat/doc/Makefile.am`
* CMake: Adjust `find_program(DOCBOOK_TO_MAN NAMES docbook2x-man)` in `expat/CMakeLists.txt`.

**Comment by stephengroat** [comment]
@hartwork any reason not to use `AC_CHECK_PROGS` right now until we can figure out a better solution?

**Comment by hartwork** [comment]
Seems like `AC_CHECK_PROGS` is non-fatal so we can check for it even without a guard like `--disable-doc` without breaking the build where it is missing. So that would be a start, yes.
If we get rid of `docs.mk`, we need a replacement for Automake and CMake, each.

**Comment by hdatma** [comment]
Brew is using mainstream docbook2x. Just replace "DOCBOOK_TO_MAN = docbook2x-man" with "DOCBOOK_TO_MAN = docbook2man" in doc.mk. 

The next problem: APFS and HFS+ may be case-sensitive...

```
> make
make -f ./doc.mk xmlwf.1 srcdir=.
docbook2x-man ./xmlwf.xml
make[1]: docbook2x-man: No such file or directory
make[1]: *** [XMLWF.1] Error 1
make: *** [xmlwf.1] Error 2
```

**Comment by hartwork** [comment]
@hdatma Good point, I made #159 for that now.

The core issue of  #153 seems to be fixed. Closing.

**Comment by kkkunche** [comment]
hartwork, seems like this issue is fixed ?.

**Comment by hartwork** [comment]
Yes, seems fixed. Related commit is cb7d430d22c02c813eedf69caa491898d49dd82f
