### ISSUE TITLE
Release archives contents

### ISSUE THREAD

**Issue by termim** [libexpat/libexpat#156]
Make release archive contents on github the same as on SF
including archive & directory names.

**Comment by hartwork** [comment]
Hi Mikhail,

release archives (available at SourceForge) include generated files not available in Git (e.g. the compiled `xmlwf` man page) and are created using `make distcheck`. Without rationale or more details I consider this ticket not useful and rather impolite. Please add further details about the what and why. Thanks.

Best, Sebastian

**Comment by termim** [comment]
Hi Sebastian,

Sorry for little details. You described perfectly the difference between release archives and Git snapshots. The point of this ticket is that archives provided on GitHub under the "releases" link are not technically a releases but just a snapshots. With Git it is easy to obtain a snapshot for any tag or revision even from remote repository, so providing snapshot archives for the release tags that are different from the official release archives makes a little sense and even somewhat misleading - one would expect to find a real releases when clicking on the "releases" link. Releases usually are made for library users not library developers :). Hope that helps.

Regards, Mikhail

BTW, if we'd consider authors of all tickets with little detail as impolite then we'd live in a scary world IMHO. Hope it is not true ;)

**Comment by hartwork** [comment]
> BTW, if we'd consider authors of all tickets with little detail as impolite then we'd live in a scary world IMHO. Hope it is not true ;)

That sounds like missing the point to me, but let's take that offline if you want to discuss it further.

> Sorry for little details. You described perfectly the difference between release archives and Git snapshots. The point of this ticket is that archives provided on GitHub under the "releases" link are not technically a releases but just a snapshots. With Git it is easy to obtain a snapshot for any tag or revision even from remote repository, so providing snapshot archives for the release tags that are different from the official release archives makes a little sense and even somewhat misleading - one would expect to find a real releases when clicking on the "releases" link. Releases usually are made for library users not library developers :). Hope that helps.

The current releases lists is what GitHub creates automatically. I haven't taken much time looking into https://help.github.com/articles/creating-releases/ but it looks like the way to go to improve on status quo. I think we're on the same page with that now.

**Comment by hartwork** [comment]
All SourceForge downloads are available at https://github.com/libexpat/libexpat/releases now. Seems fixed to me, please re-open if needed.

**Comment by termim** [comment]
Thank you!
