### ISSUE TITLE
Man page compilation should support case insensitive file system

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#159]
Details at https://github.com/libexpat/libexpat/issues/153#issuecomment-338169106

Affected build systems:
* ~~Autotools: `doc/Makefile.am`~~ (fixed by b242236c8e993259783b5df3f84a110c4f9b31b0 from #167)
* CMake: `CMakeLists.txt`

**Comment by kkkunche** [comment]
hartwork, hope this is not fixed. How to reproduce the issue ?.

**Comment by kkkunche** [comment]
hartwork, hope this is not fixed. How to reproduce the issue ?.

**Comment by hartwork** [comment]
I think you're right: it seems like …

https://github.com/libexpat/libexpat/blob/25051a4c8eadb1daf0d1fe572b58c6843e726f7e/expat/CMakeLists.txt#L215

… makes that work for CMake as well.

**Comment by hartwork** [comment]
It was fixed as a side effect of cb7d430d22c02c813eedf69caa491898d49dd82f which was first included in a release with Expat 2.2.5.
