### ISSUE TITLE
runtests.c:65:3: error: #error The test suite relies on assert(...)

### ISSUE THREAD

**Issue by noloader** [libexpat/libexpat#160]
I'm building libexpat  from sources and attempting to run its self tests. `CPPFLAGS` includes `-DNDEBUG` because I'm in a release configuration. `make check` results in:

```
gcc -DHAVE_CONFIG_H -I. -I..  -I./../lib -I/usr/local/include -DNDEBUG -DHAVE_EX
PAT_CONFIG_H  -m64 -march=native -Wall -Wmissing-prototypes -Wstrict-prototypes
-fexceptions -fno-strict-aliasing -MT runtests.o -MD -MP -MF .deps/runtests.Tpo
-c -o runtests.o runtests.c
runtests.c:65:3: error: #error The test suite relies on assert(...) at the momen
t. You have NDEBUG defined which removes that code so that failures in the test
suite can go unnoticed. While we rely on assert(...), compiling the test suite w
ith NDEBUG defined is not supported.
 # error  \
   ^~~~~
```

I think it would be a good idea if the files in the test suite, like `runtests.c`, performed an unconditional `#undef NDEBUG` if that's what they require. There are three reasons for the suggestion.

First, we can only configure once; we cannot run multiple configurations, like one for the library and one for the test suite. Second, there's no configuration option which applies to just the test suite. For example, configure lacks a `TEST_CPPFLAGS` (or similar). Third, we can run `make CPPFLAGS="..."` to override the make flags supplied during configuration, but its tricky because we don't have the flags that would result from a configuration.

Our other option is to forgo `make check` before an install, but that's not a desirable option (for me). I like to ensure the library was built properly and passes its self tests before an install.

-----

For completeness, here is my standard configuration recipe. All projects get `NDEBUG` if they are being installed to run in production.

```
INSTALL_PREFIX=""/usr/local"
INSTALL_LIBDIR="$INSTALL_PREFIX/lib"    # or lib64 or some OSes

SH_LDLIBS=("-ldl" "-lpthread")
SH_LDFLAGS=("$SH_MARCH" "-Wl,-rpath,$INSTALL_LIBDIR" "-L$INSTALL_LIBDIR")

    PKG_CONFIG_PATH="$INSTALL_LIBDIR/pkgconfig" \
    CPPFLAGS="-I$INSTALL_PREFIX/include -DNDEBUG" \
    CFLAGS="$SH_MARCH $SH_NATIVE" \
    CXXFLAGS="$SH_MARCH $SH_NATIVE" \
    LDFLAGS="${SH_LDFLAGS[*]}" LIBS="${SH_LDLIBS[*]}" \
./configure --enable-shared --prefix="$INSTALL_PREFIX" --libdir="$INSTALL_LIBDIR"
```

**Comment by hartwork** [comment]
Should be auto-fixing now, please re-open if it needs more work.
