### ISSUE TITLE
Syntax error in configure check for DOCBOOK_TO_MAN

### ISSUE THREAD

**Issue by rainerjung** [libexpat/libexpat#165]
configure failure in version 2.2.5

./configure: line 17309: program: command not found

due to a syntax error (wrong quote nesting) in the following configure lines:

17308 test -n "$DOCBOOK_TO_MAN" || DOCBOOK_TO_MAN="if test "x$with_docbook" != xcheck; then
17309     as_fn_error $? "Required program 'docbook2x-man' not found." "$LINENO" 5"

This is generated by the following lines in configure.ac:

239 AS_IF([test "x$with_docbook" != xno],
240   [AC_CHECK_PROGS([DOCBOOK_TO_MAN], [docbook2x-man docbook2man docbook-to-man],
241   [if test "x$with_docbook" != xcheck; then
242     AC_MSG_ERROR([Required program 'docbook2x-man' not found.])])])

Here the third argument of AC_CHECK_PROGS seems to get quoted by autoconf, so using quotes inside it des not work.

**Comment by hartwork** [comment]
That's emberassing. Could you review and test #168 for a fix?
