### ISSUE TITLE
configure: "fgrep -q" fails on Solaris

### ISSUE THREAD

**Issue by rainerjung** [libexpat/libexpat#166]
configure for 2.2.5 fails on Solaris because "fgrep -q" is used and /usr/bin/fgrep does not support "-q".

The use of "fgrep -q" comes from the following lines in configure.ac:

109 AM_CONDITIONAL([MINGW], [echo -- "${host}" | fgrep -q mingw])
110 AM_CONDITIONAL([UNICODE], [echo -- "${CPPFLAGS}${CFLAGS}" | fgrep -q XML_UNICODE])

Probably replacing fgrep by $FGREP will fix this, since FGREP is detected earlier as "/usr/xpg4/bin/grep -F" and the xpg4 variants of grep and fgrep support "-q" even on Solaris.

**Comment by hartwork** [comment]
Hi!

Sorry for the inconvenience. It seems that `-q` is POSIX according to http://pubs.opengroup.org/onlinepubs/009695399/utilities/grep.html but I guess Solaris `/usr/bin/fgrep` is not fully POSIX then?
I believe I have fixed the issue now. Please re-open if it needs more work. Thanks!

Best, Sebastian
