### ISSUE TITLE
Conan package for expat

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [libexpat/libexpat#169]
Hello,
Do you know about Conan package manager? Can you add Conan package for the library and maintain it? Here you can find example of my conan recipe for libpng: https://github.com/ZaMaZaN4iK/conan-libpng

**Comment by hartwork** [comment]
Hi!
There seems to be a conan package for Expat at https://github.com/Pix4D/conan-expat, have you checked that one?

**Comment by ZaMaZaN4iK** [comment]
Thank. But there is not package on conan-center. I think that will be great if libexpat will support also Conan package on Conan-center and provide to users very easy way to use library.

**Comment by hartwork** [comment]
I see. I have no resources to work on this topic myself, so I'll re-add the help-wanted label.

**Comment by MohammedKhajapasha** [comment]
Hi ZaMaZaN4iK,
The Expat:pix4d is available on conan-center from Nov 19, 2018. could you please check this and update, if this aligned with your request, could you please close the ticket.

**Comment by ZaMaZaN4iK** [comment]
Yep. That's already what I want. Thank you a lot!
