### ISSUE TITLE
Memory Leak in Empty Element Handling

### ISSUE THREAD

**Issue by RMJ10** [libexpat/libexpat#17]
The following XML causes a memory leak when parsed: `<D xmlns:L="D" l:a='' L:a=''/>`

What happens is that the attribute parsing in `storeAtts()` creates a binding for the attribute `xmlns:L` and attaches it to the binding list pointer parameter.  However `l:a` doesn't have a valid prefix, so the function aborts and returns an error.  Normally this would leave the newly-minted binding attached to some field of the parser object, from where it will eventually be freed.

Unfortunately, for empty elements (cases `XML_TOK_EMPTY_ELEMENT_NO_ATTS` and `XML_TOK_EMPTY_ELEMENT_WITH_ATTS`), `doContent()` uses a local stack variable as the binding pointer passed to `storeAtts()` and fails to tidy it up if an error is returned.

The solution is to move any bindings onto the parser's free binding list, as is done at the end of the case:

```
rhodri@sto-helit ~/expat/base/libexpat $ git diff expat/lib/xmlparse.c
diff --git a/expat/lib/xmlparse.c b/expat/lib/xmlparse.c
index bb8c9a7..09245a9 100644
--- a/expat/lib/xmlparse.c
+++ b/expat/lib/xmlparse.c
@@ -2527,8 +2527,18 @@ doContent(XML_Parser parser,
           return XML_ERROR_NO_MEMORY;
         poolFinish(&tempPool);
         result = storeAtts(parser, enc, s, &name, &bindings);
-        if (result)
+        if (result) {
+          while (bindings) {
+            BINDING *b = bindings;
+            if (endNamespaceDeclHandler)
+              endNamespaceDeclHandler(handlerArg, b->prefix->name);
+            bindings = bindings->nextTagBinding;
+            b->nextTagBinding = freeBindingList;
+            freeBindingList = b;
+            b->prefix->binding = b->prevPrefixBinding;
+          }
           return result;
+        }
         poolFinish(&tempPool);
         if (startElementHandler) {
           startElementHandler(handlerArg, name.str, (const XML_Char **)atts);
```

**Comment by hartwork** [comment]
Hi!

Very nice!

Let me do a braindump with this:
* `if (result) {` forces the reader to inspect return statements of `storeAtts`. Let's use the occasion to replace that by `if (result != XML_ERROR_NONE)` to save that question to people coming after us.
* The body of `if (result) {` seems to be the exact same thing as done a few lines below right after `poolClear(&tempPool);`; I wonder if it's worth to avoid that code duplication and if so using which approach. As `endNamespaceDeclHandler` and `freeBindingList` are macros hiding their relationship to the `parser` structure pointer, if we extract a new function `parser` and `bindings` would be the only parameters and we could give it a good name, along the lines of "free bindings" or so. My vote for that approach (over a new macro, gotos, or plain duplication).
* It would be nice to have some kind of test for this

Best, Sebastian

**Comment by RMJ10** [comment]
- Fair point
- I wondered about that myself; I didn't do it partly to make it easier to explain and partly in case the function call imposed a noticeable overhead at the end of the state.  It will happen moderately commonly, but IMHO a separate function is better for maintainability.  I'll see if I can get the benchmarks running.
- Can do; we have the hooks to put a suitably specialized allocator in.
- True.  It's called in addBindings, so any binding that actually exists will have had its startNamespaceDeclHandler called.

I'll go do some candidate work on a branch.

**Comment by RMJ10** [comment]
The benchmarks are only accurate to about 1%, but I couldn't see any change!  Well worth making this a function call then.

**Comment by RMJ10** [comment]
Candidate test and fix on RMJ10/libexpat branch issue_17_fix

**Comment by hartwork** [comment]
I thought about 43b22f59472ecac36a30a9b3aa88b1c3b01de313 more: Let's _not_ split it up if you haven't yet. It may say more together, it's clean enough and people copying it would need both halves anyway. Makes sense?

**Comment by hartwork** [comment]
@RMJ10
I forgot: I could use help on a to-the-point summary for the change log. How far off is `fix memory leak on parser error for unbound attribute prefix with new namespaces defined in the same tag`? Thanks in advance!

**Comment by RMJ10** [comment]
@hartwork That sounds like as concise a summary as it could be!

**Comment by hartwork** [comment]
Excellent, thanks for the review.
