### ISSUE TITLE
Nullptr used in arithmetic operation

### ISSUE THREAD

**Issue by tbeu** [libexpat/libexpat#170]
PVS-Studio reports

[V769](https://www.viva64.com/en/w/v769/) The 'parser->m_bufferPtr' pointer in the expression equals nullptr. The resulting value of arithmetic operations on this pointer is senseless and it should not be used. xmlparse.c 2090

https://github.com/libexpat/libexpat/blob/5f9bc4836f84d17804d93c7f6760e2a9e4528f05/expat/lib/xmlparse.c#L2079-L2090

https://github.com/libexpat/libexpat/blob/5f9bc4836f84d17804d93c7f6760e2a9e4528f05/expat/lib/xmlparse.c#L2094-L2098

**Comment by hartwork** [comment]
Confirming as a bug, in there for ages (part from c446fb274ebc043a3de34730f6bef169d13dc0e9 since 1.95.0).

For a bit more code context:
```C
#ifdef XML_CONTEXT_BYTES
      if (parser->m_bufferPtr) {
        [..]
      }
      else {
        parser->m_bufferEnd = newBuf + (parser->m_bufferEnd - parser->m_bufferPtr);  /* sure NULL */
        parser->m_bufferPtr = parser->m_buffer = newBuf;
      }
#else
      if (parser->m_bufferPtr) {
        [..]
      }
      parser->m_bufferEnd = newBuf + (parser->m_bufferEnd - parser->m_bufferPtr);  /* potential NULL */
      parser->m_bufferPtr = parser->m_buffer = newBuf;
#endif  /* not defined XML_CONTEXT_BYTES */
```

**Comment by RMJ10** [comment]
I've removed the examples pointed out above in RMJ10/libexpat branch issue_170_fix, but the whole of `XML_GetBuffer` is doing arithmetic with potentially NULL pointers.  It's all safe &mdash; either all of the `m_bufferXxx` pointers are NULL or none of them are &mdash; but I should really condition all that arithmetic.

**Comment by RMJ10** [comment]
I've made all the changes, though appveyor isn't happy with me for using the wrong types for the pointer differences.  More importantly, I think it looks ugly.  Perhaps the correct fix for this issue is to add a comment at the top of `XML_GetBuffer()` explaining that the pointer arithmetic is safe: either all of the buffer pointers are valid, in which case so are the differences, or all of the buffer pointers are NULL and the differences are consequently zero.

**Comment by hartwork** [comment]
> or all of the buffer pointers are NULL and the differences are consequently zero.

I think that's undefined behavior land?

**Comment by hartwork** [comment]
https://stackoverflow.com/a/22104122

**Comment by RMJ10** [comment]
I like the macro approach.  Maybe call it `EXPAT_SAFE_PTR_DIFF` ?

**Comment by hartwork** [comment]
:+1: for `EXPAT_SAFE_PTR_DIFF` for a name
