### ISSUE TITLE
CMake code should use GNUInstallDirs

### ISSUE THREAD

**Issue by DerDakon** [libexpat/libexpat#178]
The GNUInstallDirs module offers variables that e.g. set the lib-directory to the proper value depending on the platform (lib, lib64, lib/something). Using this would require a newer CMake version as the module was introduced in 2.8.10, but I doubt much older versions are in real use today anyway for someone that wants to use the CMake buildsystem.

**Comment by DerDakon** [comment]
The new Trusty images have CMake 3.9.2 (see [the changelog](https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/)). I can cook something together in the next days. The main question is how high we want to raise the bar. I think 2.8.12 is a sensible minimum default, even if I personally go for 3.x usually, but I have less legacy systems to care about.

**Comment by hartwork** [comment]
If >=2.8.10 is an option, I'd be good with that because:
* CMake is not the default build system — Autotools is — so we have some freedom
* we'd still have CentOS 7 in the boat (if http://jotmynotes.blogspot.de/2016/10/updating-cmake-from-2811-to-362-or.html is right); not sure about CentOS 6

**Comment by DerDakon** [comment]
It will work, but it will not give the best results on all platforms. I think that is "good enough".

**Comment by hartwork** [comment]
> it will not give the best results on all platforms

What do you mean?

**Comment by DerDakon** [comment]
E.g. the correct setting for manpage location on FreeBSD was only fixed for CMake 3.8, so before you will not get the correct path by default (but nothing worse than the current situation).
