### ISSUE TITLE
runtests.c fail if stdint.h is not available

### ISSUE THREAD

**Issue by barry-scott** [libexpat/libexpat#180]
I'm building expat R_2_2_5 on windows using the Visual C++ for Python 2.7 tools.
This does not include stdint.h, that is reported by CMake.
However tests/runtests.h:45 included stdint.h.
I commented this out and it seems to compile without it.

**Comment by hartwork** [comment]
Hi @barry-scott,

we have handling for missing `stdint.h` in https://github.com/libexpat/libexpat/blob/master/expat/lib/siphash.h#L93 but not yet in `runtests.c`, true. The way I read https://www.microsoft.com/en-us/download/details.aspx?id=44266 you are running Visual Studio 9, i.e. version 2008. Looking at `runtests.c` I find use of `uint64_t` and `intptr_t`:

```
# grep -o 'u\?int[a-z0-9]*_t' tests/runtests.c | sort -u
intptr_t
uint64_t
```

What do you think about
```
#if defined(_WIN32) && defined(_MSC_VER) && (_MSC_VER < 1600)
    /* For vs2003/7.1 up to vs2008/9.0; _MSC_VER 1600 is vs2010/10.0 */
 #if defined(_WIN64)
    typedef __int64 intptr_t;
 #else
    typedef __int32 intptr_t;
 #endif
    typedef unsigned __int64 uint64_t;
#else
 #include <stdint.h> /* intptr_t uint64_t */
#endif
```
for a fix to `runtests.c`?

**Comment by barry-scott** [comment]
Yes that looks good for stdint.h.

**Comment by hartwork** [comment]
Should be fixed on `master` now. Please re-open if needed.
