### ISSUE TITLE
xmlwf/readfilemap.c: io.h  required to define _open, _read etc on windows

### ISSUE THREAD

**Issue by barry-scott** [libexpat/libexpat#182]
I see these warning building on windows.

[ 46%] Building C object CMakeFiles/xmlwf.dir/xmlwf/readfilemap.c.obj
readfilemap.c
C:\BuildRoot\Win64-VC-14.0-1.9.7\expat\xmlwf\readfilemap.c(87): warning C4013: 'open' undefined; assuming extern returning int
C:\BuildRoot\Win64-VC-14.0-1.9.7\expat\xmlwf\readfilemap.c(94): warning C4013: 'close' undefined; assuming extern returning int
C:\BuildRoot\Win64-VC-14.0-1.9.7\expat\xmlwf\readfilemap.c(121): warning C4013: '_read' undefined; assuming extern returning int

MSDN says you need <io.h>

**Comment by hartwork** [comment]
Is this about >2.2.5 Git master or <=2.2.5? Git master should have it fixed since bc54490e6d7e6a9f456c59b6ff20a315a01326b0, originally from pull request #173. Can you confirm?

**Comment by barry-scott** [comment]
I'm using R_2_2_5. Reviewing that commit it looks good. Sorry cannot confirm in the short term.
The reason I was hitting this issue was an attempt to build subversion but it turns out that
it does not seem to support expat unbundled builds yet, as far as I can tell.

**Comment by hartwork** [comment]
Closing as fixed by bc54490e6d7e6a9f456c59b6ff20a315a01326b0
