### ISSUE TITLE
parsing files >2GB?

### ISSUE THREAD

**Issue by egorpugin** [libexpat/libexpat#183]
Hi,

I have some very large files (2.5, 8, 23 GBs), but XML_Parse accepts integer lengths.
```
XMLPARSEAPI(enum XML_Status)
XML_Parse(XML_Parser parser, const char *s, int len, int isFinal);
```

libxml2 has same issue.

Please, do not consider this ticket very serious, I'm just playing this and that.
But may be this will be possible in the future as nice to have feature.

**Comment by hartwork** [comment]
Hi @egorpugin,

Expat does support parsing files of 23 GB size: Just call `XML_parse` multiple times, adjusting `s` and `len` and `isFinal` accordingly. `isFinal` would be 0 for all but the last call. `len` should be below `INT_MAX / 2` each time. Please also check Expat compile time switch `XML_LARGE_SIZE`

> to enable 64-bit integer support for line and column numbers and the over-all byte index

(quoting [README.md](https://github.com/libexpat/libexpat/blob/master/expat/README.md)).

I'm closing this ticket as a (hopefully answered) question. Please re-open if needed.

Best, Sebastian

**Comment by egorpugin** [comment]
Wait... I tried to load 2.5 GB file with 3 chunks, last one returned 0 (error).
I'll recheck if this was my mistake or expat's.

**Comment by egorpugin** [comment]
Ok, seems my mistake, sorry. Even works w/out `XML_LARGE_SIZE` option and works with all my files including 23GB one.
Thank you!

ps. I'm developing a C/C++ package (or dependency) manager based on CMake and added your library there:
https://cppan.org/pvt.cppan.demo.expat/version/2.2.5

**Comment by hartwork** [comment]
Cool, I have added a link to the website at https://libexpat.github.io/doc/packages/ through commit https://github.com/libexpat/libexpat.github.io/commit/e3933dbe0240de5cf5c0d1d2596bb84996260614.
