### ISSUE TITLE
Spell fix in comment

### ISSUE THREAD

**Issue by pointsman** [libexpat/libexpat#187]
https://github.com/libexpat/libexpat/blob/8bde051202f4cdc087b9416ffb9e59a19f750089/expat/lib/expat.h#L267

A user of my expat using software reported some spelling error to my project, with this one in expats basket.

    -   valuable when memory allocation overhead is disproportionatly high,
    +   valuable when memory allocation overhead is disproportionately high,

**Comment by hartwork** [comment]
Thanks for the report!
