### ISSUE TITLE
brew: SHA256 mismatch

### ISSUE THREAD

**Issue by noah-seltzer** [libexpat/libexpat#192]
When running brew install expat, I get this error
Error: SHA256 mismatch
Expected: d9dc32efba7e74f788fcc4f212a43216fc37cf5f23f4c2339664d473353aedf6
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /home/pi/.cache/Homebrew/expat-2.2.5.tar.bz2
To retry an incomplete download, remove the file above.

I have tried:
brew update
brew doctor
brew cleanup
Deleting file as instructed in error, then running above commands then re-trying install

please advise

**Comment by hartwork** [comment]
I'd expected d9dc32efba7e74f788fcc4f212a43216fc37cf5f23f4c2339664d473353aedf6 as well. Either you're witnessing a man-in-the-middle attack or something is broken in brew? I would suggest to keep and inspect that download closer (say using recursive diff with a too like Meld), re-try and report to brew if the error is persistent. What do you think?

**Comment by noah-seltzer** [comment]
Solved issue by downloading expat directly from internet
