### ISSUE TITLE
Feature request: GPG-signed release tarballs

### ISSUE THREAD

**Issue by yan12125** [libexpat/libexpat#193]
Since https://github.com/libexpat/libexpat/issues/42, release tags are signed. Could you consider also sign release tarballs? For example, create a signature expat-2.2.5.tar.bz2.asc for the release tarball expat-2.2.5.tar.bz2. That would help people who use plain HTTP instead of git to fetch libexpat.

**Comment by hartwork** [comment]
You'd still need a to limit the set of allowed keys to sign, right? Else, someone could do MITM and sign using his own key and it would pass the valid signature test. Do you have that infrastructure in place?

**Comment by hartwork** [comment]
Seen in PKGBUILD files before, excellent. I'll see what I can do!

**Comment by hartwork** [comment]
@yan12125 2.2.6 is the first release to come with a .asc file now. It was created using [`distribute.sh`](https://github.com/libexpat/libexpat/blob/master/expat/distribute.sh). If you run into any issues with that file please let me know.
