### ISSUE TITLE
dropping a character from a name

### ISSUE THREAD

**Issue by mzimmers** [libexpat/libexpat#194]
I have a small expat test driver, written in C, built with Qt Creator on a Windows 10 system.

When I parse this file (renamed from sample.xml to sample.txt for inclusion here):
[sample.txt](https://github.com/libexpat/libexpat/files/1885473/sample.txt)

the value on line 17 (2000-12-16) is returned as "000-12-16". I've looked at the buffer in memory and confirmed that the leading '2' is missing.

- if I change the value, say so 123452000-12-16, the leading character is always dropped.
- if I move the bk102 section to above bk101, it works correctly, and I don't see the error in any other part of the output.
- if I move the bk102 section to below bk103, it works correctly, and I don't see the error in any other part of the output.

Here are my handlers (sorry about the formatting; I tried to fix it):
```
void startElement(void *data, const char *name, const char **atts)
{
    struct UserData *ud = (struct UserData *) data;
    unsigned int i;

    for (i = 0; i < ud->depth; i++)
    {
        putchar('\t');
    }
    puts(name);

    for (i = 0; atts[i]; i += 2)
    {
        printf(" %s='%s'", atts[i], atts[i + 1]);
    }
    printf("\n");
    ud->depth++;
}

void endElement(void *data, const char *name)
{
    char *p =  name;

    struct UserData *ud = (struct UserData *) data;
    ud->depth--;
    printf("Content of element \"%s\" was \"%s\"\n", name, ud->p);
    free (ud->p);
}

void handleData(void *data, const char *content, int length)
{
    struct UserData *ud = (struct UserData *) data;
    unsigned int l_length = (unsigned) length;
    ud->p = malloc((unsigned) (l_length + 1));
    strncpy(ud->p, content, l_length);
    ud->p[l_length] = '\0';
//    ud->p = trimwhitespace(ud->p);
}
```

**Comment by hartwork** [comment]
Hi!

Which version and distribution of Expat are you using?

**Comment by hartwork** [comment]
PS: Are you aware of https://libexpat.github.io/doc/common-pitfalls/#split-character-data ?

**Comment by mzimmers** [comment]
I'm using 2.2.5, and I think I sounded a false alarm here. Yes, I think the problem is an extreme case of buffer splitting. I'll implement some concatenation logic and report back. Thanks...

**Comment by mzimmers** [comment]
Yeah, that was it. My bad...sorry for the unnecessary noise.
