### ISSUE TITLE
Parsing non-ascii problem

### ISSUE THREAD

**Issue by yough3rt** [libexpat/libexpat#201]
I wanna to parse some xml pattern with non-ascci , like ` <a>\xff\xfe</a>`, is it possible for `libexpat` to accept non-ascii without compile it again. Maybe, if I can change the encoding of the xml or other ways?

**Comment by yough3rt** [comment]
BTW, I try to change the encoding of xml to `ISO-8859-1` which indeed accept non-ascii like `\xff`, however, `libexpat` change the `\xff` to `\xc3\xbf`.

**Comment by hartwork** [comment]
Expat's `XML_ParserCreate` has a parameter `encoding`:
> If encoding is non-null, it specifies a character encoding to use for the document. This overrides the document encoding declaration. There are four built-in encodings:
> * UTF-8
> * UTF-16
> * ISO-8859-1
> * US-ASCII.

The signature is this:
```
XML_Parser XML_ParserCreate(const XML_Char *encoding);
```

I think we have all Expat aspects of this question covered now.
