### ISSUE TITLE
64bit Windows binaries

### ISSUE THREAD

**Issue by ruizpauker** [libexpat/libexpat#203]
I think it'd be nice to have a 64 bit windows release,

**Comment by ennioVisco** [comment]
Yes! Actually most of current windows release are on 64bits and since expat is particularly appreciated for really large files, I guess it is reasonable to assume their usage won't cap at 4 GBs of memory.

**Comment by hartwork** [comment]
Just for the record: You can process >4GB files on 32bit with 4GB memory with Expat, in general, just not with a single call to a function.

I'm not on Windows myself. For official 64bit Windows binaries we'll need one or more of:
- Time from @kwaclaw who builds current official 32bit binaries
- Making AppVeyor build an installer and pushing results somewhere
- MingGW (and wine) to build Windows binaries (#38) and the installer on Travis and again push somewhere
- Other ideas?

**Comment by hartwork** [comment]
@ruizpauker @ennioVisco @luzpaz given that we have [`win32/build_expat_iss.bat`](https://github.com/libexpat/libexpat/blob/master/expat/win32/build_expat_iss.bat) now — can you check if it takes more than adding a few extra parameters to that script to build 64bit binaries?
Also, are there any naming conversions regarding 64bit binaries on Windows? Would it still be `libexpat.dll`? Thanks!

**Comment by hartwork** [comment]
It seems like there is no pressing demand anymore. I'll close the ticket as obsolete for now but I'm happy to re-open. We'll need answers for https://github.com/libexpat/libexpat/issues/203#issuecomment-536321381 then. If you can help — great!

**Comment by hartwork** [comment]
A quick update for anyone interested in 64bit Expat Windows binaries:

[Expat 2.6.4](https://github.com/libexpat/libexpat/releases/tag/R_2_6_4) is the first release to come with 64bit Windows binaries. These binaries were built by GitHub Actions at https://github.com/libexpat/libexpat/actions/runs/12878310769 based on the work from pull request #946. If you find any issues with these new 64bit binaries specifically, please [report that as a new issue](https://github.com/libexpat/libexpat/issues) and we'll see about a fix for Expat >=2.6.5, together. Thank you!
