### ISSUE TITLE
bad command line when running test-driver?

### ISSUE THREAD

**Issue by marcomaggi** [libexpat/libexpat#210]
(After a lot of time, I am coming back to Expat.  I am happy to see that someone is taking care of it.  Thank you!  I am still looking around to see how it is packaged.)

After a checkout on my Slackware 64-bit, I build using the GNU Autotools: everything goes fine until I try the `make check` command; it fails because `expat/conftools/test-driver` is created without executable permissions, but the script `test-driver-wrapper.sh` expects it to have them.

**Comment by hartwork** [comment]
Hi!

Are you using Expat from a .zip archive? The git and tarball editions seem to be executable as I would expect:

```console
# cd "$(mktemp -d)"                                                                                      
# wget -O- https://github.com/libexpat/libexpat/releases/download/R_2_2_6/expat-2.2.6.tar.bz2 | tar xj expat-2.2.6/conftools/test-driver
# ls -l expat-2.2.6/conftools/test-driver 
-rwxr-xr-x 1 user user 4641 Aug 15 14:55 expat-2.2.6/conftools/test-driver
```

If the issue persist, please help me reproduce it in detail. Thanks!

**Comment by marcomaggi** [comment]
I am using the result of a `git clone`.

**Comment by hartwork** [comment]
I see. `test-driver` is created by `autoreconf` of autoconf 2.69.
The output I get from it is executable, see below.

```console
# cd "$(mktemp -d)"                                        

# git clone --depth 1 https://github.com/libexpat/libexpat.git

# ls -l libexpat/expat/conftools/
total 16
-rw-r--r-- 1 user user 2967 Aug 20 20:29 ac_c_bigendian_cross.m4
-rw-r--r-- 1 user user 1442 Aug 20 20:29 expat.m4
-rwxr-xr-x 1 user user  830 Aug 20 20:29 get-version.sh
-rwxr-xr-x 1 user user 2480 Aug 20 20:29 PrintPath

# cd libexpat/

# autoreconf -i -f
aclocal-1.16: warning: couldn't open directory 'm4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'conftools'.
libtoolize: copying file 'conftools/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:59: installing 'conftools/compile'
configure.ac:58: installing 'conftools/config.guess'
configure.ac:58: installing 'conftools/config.sub'
configure.ac:34: installing 'conftools/install-sh'
configure.ac:34: installing 'conftools/missing'
examples/Makefile.am: installing 'conftools/depcomp'
parallel-tests: installing 'conftools/test-driver'

# ls -l conftools/test-driver 
-rwxr-xr-x 1 user user 4642 Aug 20 20:31 conftools/test-driver
```

**Comment by marcomaggi** [comment]
It is enough to replace the last line of `test-driver-wrapper.sh` from:

https://github.com/libexpat/libexpat/blob/39e487da353b20bb3a724311d179ba0fddffc65b/expat/test-driver-wrapper.sh#L43

to:

`
exec /bin/bash "${top_srcdir}"/conftools/test-driver "${test_driver_args[@]}" "${top_builddir}"/run.sh "$@"
`

or:

`
exec $SHELL "${top_srcdir}"/conftools/test-driver "${test_driver_args[@]}" "${top_builddir}"/run.sh "$@"
`

**Comment by hartwork** [comment]
Hi!

I have spun up a Slackware container now to see it with my own eyes in hope to get a bug report for GNU autoconf upstream or downstream. This is what I got:

``` console
$ docker run -it --rm vbatts/slackware-base bash -i

# cat /etc/os-release 
NAME=Slackware
VERSION="14.2"
ID=slackware
VERSION_ID=14.2
PRETTY_NAME="Slackware 14.2"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"

# slackpkg update
[..]

# slackpkg install autoconf automake slackpkg install curl git libtool m4 perl sasl

Looking for autoconf automake slackpkg install curl git libtool m4 perl sasl in package list. Please wait... DONE

autoconf-2.69-noarch-1.txz
automake-1.15-noarch-1.txz
curl-7.61.0-x86_64-1_slack14.2.txz
git-2.14.4-x86_64-1_slack14.2.txz
libtool-2.4.6-x86_64-5_slack14.2.txz
m4-1.4.17-x86_64-1.txz
perl-5.22.2-x86_64-1.txz
cyrus-sasl-2.1.26-x86_64-1.txz

Total package(s): 8

Do you wish to install selected packages (Y/n)? 
[..]

# useradd --create-home --shell /bin/bash unpriv   
# su unpriv
$ cd ~
$ git clone --depth 1 https://github.com/libexpat/libexpat.git
$ cd libexpat/expat/
$ ./buildconf.sh
$ ls -l conftools/test-driver
-rwxr-xr-x 1 unpriv unpriv 4640 Aug 22 16:25 conftools/test-driver
```

So for me that file is created with executable permissions on Slackware with autoconf 2.69.
Was there something in my session above that seems different to your setup?
Please note that this was my very first time at a Slackware shell.

**Comment by hartwork** [comment]
PS: Could this be a umask thing? I get `0022` for a umask on Slackware 14.2.

**Comment by marcomaggi** [comment]
Thanks for all this research!  I am ashamed to say that the problem is on my system: the files installed by Automake under `share`  had bad permissions due to the action of a personal post-installation script, and it appears that `autoreconf` causes the files to be copied as they are rather than install them by explicitly selecting permissions.  I never noticed until now, all the other packages I use worked fine.

**Comment by hartwork** [comment]
No worries, thanks for the update!
