### ISSUE TITLE
[question] expat  - how to break while parsing 

### ISSUE THREAD

**Issue by aksnet123** [libexpat/libexpat#222]
I would like to stop parsing the XML file after finding the required content (do not parse to the end of the file).

Is there any function or flag that allows to break while parsing?

**Comment by hartwork** [comment]
Hi,

yes there is: `XML_StopParser(XML_Parser p, XML_Bool resumable);`.

There is a file `doc/reference.html` in Git and release tarballs that has a few words more about it.

Best, Sebastian
