### ISSUE TITLE
libexpat GitHub repo summary needs to be updated (unless Sourceforge migration still ongoing?)

### ISSUE THREAD

**Issue by luzpaz** [libexpat/libexpat#225]
![image](https://user-images.githubusercontent.com/4140247/46500372-af2f6f00-c7f0-11e8-8b0a-b22fe0971320.png)

**Comment by hartwork** [comment]
I'm between chairs with this. Related: #1

**Comment by hartwork** [comment]
I have adjusted the text to read "migrated from SourceForge to GitHub" now. For anything else, we have ticket #1. Closing.
