### ISSUE TITLE
Provide gzipped release tarballs

### ISSUE THREAD

**Issue by krichter722** [libexpat/libexpat#236]
It'd be great if you'd provide gzipped release tarballs (typically ending in `.tar.gz`) because extraction is supported on most systems out-of-the-box whereas the installation of `bzip2` especially without root permissions can be a time-consuming experience. This is especially relevant on minimized container-systems like Docker which are used in CI/CD environments.

I'm aware that gzipped tarballs of the source at the moment of release (!= release tarball) are available.

**Comment by hartwork** [comment]
I'd expect that either you have a system so minimal that not even build-essentials (thinking Debian-based) is around to comple Expat or you do have that and then the system is not minimal and either does have bzip2 already or is okay to expect to have it or to install at the same time. How come your case is on neither end of these?

Personally, I'd rather move towards `.tar.lz` (not `.tar.xz` as that seems to have issues) and I'm only sticking to `.tar.bz2` for a compromise between size and support out of the box, already. By any chance, would `.tar.lz` work _better_ than `.tar.bz2` for you?

**Comment by krichter722** [comment]
Thanks for you feedback.

> How come your case is on neither end of the spectrum?

Imagine a system where build-essentials are available (installed with root permissions by an admin) and you want to build other things in a user prefix without root permissions - this case probably has a loophole; I'd like to stress that my suggestion is more focusing on convenience than on necessity.

> Personally, I'd rather move towards .tar.lz (not .tar.xz as that seems to have issues) and I'm only sticking to .tar.bz2 for a compromise between size and support out of the box, already. By any chance, would .tar.lz work better than .tar.bz2 for you?

Maybe you don't need to move, just provide other compression formats on the release download page - then the question about about compromises disappears, however as long as the release tarball is less than 100MB, I wouldn't worry about the size. As `.tar.lz` requires another program it doesn't have any advantage over `.tar.bz2`.

**Comment by hartwork** [comment]
I do "worry" about size because it multiplies with each download. I'm not in with this change. Please add bzip2 to your `Dockerfile`, derive a new `Dockerfile`, use `buildconf.sh` with a Git download or clone, all pretty acceptable in my book on a system that is supposed to build software. Minimalism means saying goodbye to a few bits of convenience: It's okay that say Debian comes without `tmux` and `wget` installed. I'm happy to fix other things for you.

**Comment by krichter722** [comment]
OK, that a good idea. Thanks for your constructive feedback.

**Comment by hartwork** [comment]
@krichter722 just a quick heads up that the next release will come with `.tar.gz` archives as well if you're still interested. Ticket #258 is related.
