### ISSUE TITLE
Build problem under Solaris 10 due to stdbool.h requiring C99

### ISSUE THREAD

**Issue by vadz** [libexpat/libexpat#251]
We received a [bug report](https://trac.wxwidgets.org/ticket/18352) about a build failure under Solaris 10 using gcc because `stdbool.h` apparently requires using C99 there. I don't know if Expat requires C99 (in which case please just close this one) or if you'd be interested in fixing this (in which case I could make a PR).

**Comment by hartwork** [comment]
Hi @vadz,

does the configure script of wxWidgets add `-std=c99` or `-std=gnu99` to `CFLAGS`? Expat does require a C99 compiler and GCC on Solaris 10 should support C99; error "valid only in a c99 compilation environment" makes me keep that hope up. So I'd expect the issue to be in the way that GCC is invoked by the build system, but I don't have "proof" without further investigation. Could you ask reporter `liuqiong7618` to try build Expat from Git master in the same environment in isolation? That would be of great help to both of us, I think.

Best, Sebastian

**Comment by vadz** [comment]
Thanks for looking at this, Sebastian! wxWidgets configure doesn't test for/require C99 compiler, so the file is compiled with just `gcc`, without any `-std=xxx` switches, however we do run Expat configure using `AC_CONFIG_SUBDIRS`, but then we don't use the compiler detected by it for compiling Expat... I.e. it's our own fault, finally, sorry for bothering you needlessly, I should have checked Expat configure and noticed the `AC_PROG_CC_C99` line in it myself.

We'll fix this in some way or the other in wx, sorry again for a false alert.

**Comment by hartwork** [comment]
No worries, thanks for taking care! :beers:
