### ISSUE TITLE
Cannot build from source on macOS

### ISSUE THREAD

**Issue by etresoft** [libexpat/libexpat#253]
I am building using "--without-docbook” on configure, but it seems that all makefile installation options imply “dist”, which requires docbook2x-man, which I don’t really need.

**Comment by hartwork** [comment]
Hi John,

I believe your hitting issue #247 that was fixed by #248 after release of 2.2.6. Could you check if a Git clone has the same issue?

Thank you!

Best, Sebastian

**Comment by etresoft** [comment]
Yes. That is the same problem. I had just figured out that I could avoid the issue in 2.2.6 by using “configure --without-docbook --without-xmlwf”. I double-checked in master and it builds there with just "configure --without-docbook”. So never mind.

**Comment by hartwork** [comment]
Thanks for the update!
I'll take this ticket as reminder to make a new release some time — #254.

**Comment by noloader** [comment]
If you have time, please consider a `--disable-docs` option.

I'm like @etresoft. I build on IoT devices, and I don't install document tools like dockbook, pod2man, Perl's TextUtils, etc. Building the docs waste cycles during a build and the IoT devices often lack storage for the docs.

`--disable-docs` is a convenient way for users to disable all docs, and not just some of them. I also wrote the the authors of the [GNU Coding Standards](https://www.gnu.org/prep/standards/) asking the same. A common option honored by all projects would be a welcomed addition.

**Comment by hartwork** [comment]
`--without-docbook` effectively is Expat's `--disable-docs`, unless I'm missing something. `--without-xmlwf` should not be needed just to not build documentation.
