### ISSUE TITLE
/bin/sh: ./../test-driver-wrapper.sh: No such file or directory

### ISSUE THREAD

**Issue by noloader** [libexpat/libexpat#257]
I'm working on OpenBSD. I'm building [ldns](https://www.nlnetlabs.nl/downloads/ldns) which is a library used for DNSSEC. ldns depends on Expat.

Expat's `make check` is failing on OpenBSD:

```
libtool: link: g++ -g2 -O2 -march=native -fPIC -pthread -fno-strict-aliasing -Wl,-R -Wl,/usr/local/lib -Wl,--enable-new-dtags -fno-strict-aliasing -o .libs/runtestspp runtestspp.o  -L/usr/local/lib libruntests.a -L../lib/.libs -lexpat -lpthread -pthread -Wl,-rpath,/usr/local/lib
runtestspp.o: In function `triplet_end_checker':
/home/build/expat-2.2.6/tests/runtests.c:7168: warning: warning: sprintf() is often misused, please use snprintf()
gmake[3]: Leaving directory '/home/build/expat-2.2.6/tests'
gmake  check-TESTS
gmake[3]: Entering directory '/home/build/expat-2.2.6/tests'
gmake[4]: Entering directory '/home/build/expat-2.2.6/tests'
/bin/sh: ./../test-driver-wrapper.sh: No such file or directory
gmake[4]: *** [Makefile:1003: runtests.log] Error 1
gmake[4]: Leaving directory '/home/build/expat-2.2.6/tests'
gmake[3]: *** [Makefile:985: check-TESTS] Error 2
```

However, when I duplicate the error:

```
$ cd expat-2.2.6/tests/
$ /bin/sh ./../test-driver-wrapper.sh
./../test-driver-wrapper.sh[36]: syntax error: `(' unexpected
```

So it looks like `/bin/sh` cannot handle whatever is on line 36.

Now, here's the rub with OpenBSD:

```
$ cat -n ../test-driver-wrapper.sh | head -n 40
     1  #! /bin/bash
      ...
    
    35  # Suck up all dash-dash test-driver arguments
    36  test_driver_args=()
    37  while [[ ${1} != '--' ]]; do
    38      test_driver_args=( "${test_driver_args[@]}" "${1}" )
    39      shift
    40  done
```

OpenBSD places Bash at `usr/local/bin/bash`, not `/bin/bash`. (Bash is an additional install performed by the user after system install):

```
$ command -v bash
/usr/local/bin/bash
```

You should change your shebang to the following. As far as I know this is the portable way to do it:

```
#! /usr/bin/env bash
```

You should do the same for other interpreters, like `#! /usr/bin/env python3`.

**Comment by noloader** [comment]
[This patch](https://github.com/noloader/Build-Scripts/commit/6298807f59bc) tested OK. All self tests passed on OpenBSD:

```
gmake[3]: Entering directory '/home/jwalton/Build-Scripts/expat-2.2.6/tests'
gmake[4]: Entering directory '/home/jwalton/Build-Scripts/expat-2.2.6/tests'
PASS: runtests
PASS: runtestspp
============================================================================
Testsuite summary for expat 2.2.6
============================================================================
# TOTAL: 2
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

A small request...  More self tests. The more self tests we have, the more effective tools like UBsan, Asan and Valgrind are.

**Comment by hartwork** [comment]
Hi!

Are you saying that OpenBSD has `/bin/bash` but it's pointing to something that is not Bash?

Regarding [your patch](https://github.com/noloader/Build-Scripts/commit/6298807f59bc):
- please use `buffer[sizeof(buffer) - 1] = '\0';` rather than hardcoded `buffer[1023] = '\0';`
- please make one commit for the shebang thing and one for `snprintf`
- please submit them as two pull request so that CI is run and we can see if `snprintf` works as-is on Windows (AppVeyor)
- for the shebang one, a git-format patch would work for an alternative, if easier for you

> A small request... More self tests. The more self tests we have, the more effective tools like UBsan, Asan and Valgrind are.

`TOTAL: 2`  is two testrunners, not two tests. Please check code coverage instead, it's rather high. The CI could do more better, still, yes. Polished pull requests in that regard are welcome!

**Comment by noloader** [comment]
> Are you saying that OpenBSD has /bin/bash but it's pointing to something that is not Bash?

Out of the box OpenBSD does not have Bash. If you want Bash then you have to `pkg_add install bash` (or maybe it is  `pkg install bash`). Then, once Bash is installed, it is located at `/usr/local/bin/bash`,

**Comment by hartwork** [comment]
I get the point about `/usr/bin/env` but what is the cause for `/bin/sh: ./../test-driver-wrapper.sh: No such file or directory` on top?

**Comment by hartwork** [comment]
@noloader why did you close this issue?
