### ISSUE TITLE
using xz for released tarballs

### ISSUE THREAD

**Issue by vtorri** [libexpat/libexpat#258]
Hello

bzip2 compresses less than xz. This would allow faster download.

it's quite easy to do so with autotools (if they are used for released tarballs with 'make distcheck')

**Comment by hartwork** [comment]
Hi!

The next release will start providing LZMA compressed archives, see commit above. We'll provide both `.tar.lz` and `.tar.xz`. Article https://www.nongnu.org/lzip/xz_inadequate.html might be of interest to you, since you asked for xz rather than lzip.

Best, Sebastian

**Comment by vtorri** [comment]
i know that page, but honestly, i do not trust this web page. I've tried 2 examples that the author of lzip gives, and which show that xz has bugs. There are no bug anymore for these 2 examples.

xz is used by a lot of projects for tarballs, as important as gtk/gnome or gstreamer. I doubt that they would not use xz if there were major problems with it

**Comment by hartwork** [comment]
The important parts are design/format/container issues rather than xz implementation, to my understanding.

**Comment by vtorri** [comment]
have you asked what the author of xz thinks of this webpage ? for now, you just have the opinion of a concurent of xz :)

**Comment by hartwork** [comment]
Not yet, no. Which of the examples from https://www.nongnu.org/lzip/xz_inadequate.html have you found false when reproducing?
