### ISSUE TITLE
xmlwf is failing while parsing surrogate pair 

### ISSUE THREAD

**Issue by ind1910** [libexpat/libexpat#260]
xmlwf is failing to parse the XML with following node  with error **_reference to invalid character number_**
`<cust-name>Rama &#55357;&#56911; Korada</cust-name>`

Let me know if anyone has inputs on this error.

**Comment by hartwork** [comment]
Hi! The error is legit, I'm afraid. Because:

```
In [1]: hex(55357), hex(56911)
Out[1]: ('0xd83d', '0xde4f')
```
and

> [2] | Char | ::= | #x9 \| #xA \| #xD \| [#x20-#xD7FF] \| [#xE000-#xFFFD] \| [#x10000-#x10FFFF] | /* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */
-- | -- | -- | -- | --

(from https://www.w3.org/TR/2006/REC-xml-20060816/#NT-Char).

Did you mean to use
```
<cust-name>Rama &#x55357;&#x56911; Korada</cust-name>
                  ^        ^
```
with hexadecimal `x`, instead?

Ticket  #171 might be of interest.

**Comment by ind1910** [comment]
Thanks for the reply.  Thinking of using UTF-32 (decimal) equivalent value **128071** instead [https://www.fileformat.info/info/unicode/char/1f447/index.htm]. Parsing is working fine with this value.

**Comment by hartwork** [comment]
Thanks for the update!
