### ISSUE TITLE
With & in filename XML parsing is failing. Using 2.0.0 

### ISSUE THREAD

**Issue by PradhanBangalore** [libexpat/libexpat#272]
With & or  &amp;  in content XML parsing is failing. Using 2.0.0 version. Is there anyway i can resolve this. I cant update the library.

**Comment by hartwork** [comment]
Hi @PradhanBangalore ,

I'm happy to help if you provide enough information to allow me to. If you're not used to reporting bugs, please read an article like https://www.chiark.greenend.org.uk/~sgtatham/bugs.html.
The `&` in filenames would need quotes in Bash but it's not a problem of Expat and I don't know about your environment. I'd also be curious why you have to live on Expat 2.2.0 — that's very old and vulnerable.

**Comment by PradhanBangalore** [comment]
Hi, Thanks for the reply. Below is what i am passing for parsing to expat:
<?xml version="1.0" encoding="UTF-8"?><testevent><testnum>6</testnum><subject>Test job completion; time="2019-Jun-25 09:51 AM (UTC-07:00)" test_name="Test1 & Test2.txt" user="tester" result=success</subject></testevent>

i tried escaping by replacing & with &amp; and that too failed. I tried with single quote too, that is test_name='Test1 & Test2.txt'. That too failed. Any suggestion.?

**Comment by PradhanBangalore** [comment]
It didnt take the xml content in the comment section. Adding the xml file that i am trying to parse. 
[xmlTest.zip](https://github.com/libexpat/libexpat/files/3349076/xmlTest.zip)

**Comment by hartwork** [comment]
`&` needs to be `&amp;` instead in your file. This has little to do with Expat but with XML syntax. Closing.

**Comment by PradhanBangalore** [comment]
I tried that and it failed, That's the reason i had to post a question in here.

**Comment by PradhanBangalore** [comment]
That's what i tried initially, It didn't work and that is the reason i had to post a question in here.

**Comment by hartwork** [comment]
By what definition of "does not work"? Without the right amount of details provided there is little chance I can understand the problem.

Expat comes with a tool called `xmlwf`. As long as `xmlwf < xmlTest.xml` shows well-formedness errors, the XML file needs syntax fixes. That would be a good start.

**Comment by RMJ10** [comment]
@PradhanBangalore did you remember the `;` on the end of `&amp;` ?  Because otherwise your example parses just fine for me.
