### ISSUE TITLE
Out of memory error from "xmlwf filename" (but not "xmlwf < filename")

### ISSUE THREAD

**Issue by archiecobbs** [libexpat/libexpat#28]
`xmlwf` fails with `out of memory` if run on a very large file. However, it suceeds if it takes the file from standard input instead of from the command line:
```
$ ls -l largefile.xml
-rw-r--r-- 1 tomcat tomcat 2602873036 May 20 08:59 largefile.xml

$ cat largefile.xml | xmlwf

$ xmlwf largefile.xml
largefile.xml:1:0: out of memory

$ uname -a
Linux v101.vulcan.ms 4.9.7-x86_64-linode80 #2 SMP Thu Feb 2 15:43:55 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

$ rpm -qf `which xmlwf`
expat-2.1.0-20.1.x86_64

$ cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:42.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
```

**Comment by hartwork** [comment]
Update: xmlwf has an option `-r`:

> Normally  xmlwf  memory-maps  the  XML file before parsing; this can result in faster parsing on many platforms.  -r turns off memory-mapping and uses normal file IO calls instead.

It seems to work as expected:
```
# time xmlwf -r largefile.xml
real    0m33.564s
user    0m32.808s
sys     0m0.738s
```

That being said, what change do you wish for?

**Comment by archiecobbs** [comment]
Well my recommendation would be that `xmlwf` check for `ENOMEM` when it attempts to `mmap(2)` the file, and if it gets that error back, falls back to the `-r` behavior automatically.

In other words, why expect users to be savvy enough to research and solve this problem, when a computer can just do it for them automatically? The latter is much friendlier and seems to come at no cost.

**Comment by hartwork** [comment]
It's not the call to `mmap` that fails: `mmap` succeeds, just checked. `ENOMEN` happens somewhere later. So it's a little trickier than that.

```
# ./configure --disable-shared && make -j2
# strace -ememory ./xmlwf/xmlwf largefile.xml |& fgrep mmap | tail -n 1
mmap(NULL, 2602873037, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fa9020fc000
```

**Comment by archiecobbs** [comment]
Hmm, not quite so easy then.

I think it's a good idea to figure this out, otherwise we're (arguably) punishing the user for an internal optimization, which doesn't seem quite fair.

**Comment by hartwork** [comment]
I agree this default is unfortunate (but one could argue that a slower non-mapping default would be hard to defend, too). As far as I am concerned, dropping memory mapping altogether is up for discussion. So is changing the default and adding a new option. Speed comparison (with page cache dropped) could yield data helpful for guiding the way.

**Comment by hartwork** [comment]
I found the issue. It's this code and the comment says it well (but doesn't do anything about it):
```
/* This implementation will give problems on files larger than INT_MAX. */
static void
processFile(const void *data, size_t size,
            const XML_Char *filename, void *args)
{
  XML_Parser parser = ((PROCESS_ARGS *)args)->parser;
  int *retPtr = ((PROCESS_ARGS *)args)->retPtr;
  if (XML_Parse(parser, (const char *)data, (int)size, 1) == XML_STATUS_ERROR) {
    reportError(parser, filename);
    *retPtr = 0;
  }
  else
    *retPtr = 1;
}
```
So `size_t size` unsigned 64bit `2602873037`/`0x9b24b0cd` goes in and is passed along as `(int)size` signed 32bit `-1692094259` from `(2602873037 & 0x7fffffff) - 0x80000000`. `XML_Parse` is passed a negative length for the text to parse. Very nice 😃

**Comment by hartwork** [comment]
There is #29 for a first take now. I appreciate review and testing.

**Comment by archiecobbs** [comment]
Seems to work for me:
```
$ xmlwf /xx.xml 
/xx.xml: file too large for memory-mapping, switching to streaming
$
```

**Comment by hartwork** [comment]
Okay, thanks. I'll wait with merging until the pull request has received some review but I'm confident this could go into the next release.
