### ISSUE TITLE
Failed installation during 'make'

### ISSUE THREAD

**Issue by jpiechura** [libexpat/libexpat#287]
Hello,

I'm trying to install expat on an AWS EC2 instance so that I can install the perl package XML::Parser. I unpacked libexpat-R_2_2_7 on the instance, ran ./configure, and then tried to run 'make', and I get the following output and error:

make  all-recursive
make[1]: Entering directory '/usr/bin/libexpat-R_2_2_7/expat'
Making all in lib
make[2]: Entering directory '/usr/bin/libexpat-R_2_2_7/expat/lib'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..   -DHAVE_EXPAT_CONFIG_H  -g -O2 -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wlogical-op -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -fvisibility=hidden -DXML_ENABLE_VISIBILITY=1 -MT xmlparse.lo -MD -MP -MF .deps/xmlparse.Tpo -c -o xmlparse.lo xmlparse.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DHAVE_EXPAT_CONFIG_H -g -O2 -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wlogical-op -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -fvisibility=hidden -DXML_ENABLE_VISIBILITY=1 -MT xmlparse.lo -MD -MP -MF .deps/xmlparse.Tpo -c xmlparse.c  -fPIC -DPIC -o .libs/xmlparse.o
In file included from /usr/local/include/assert.h:5:0,
                 from xmlparse.c:39:
/usr/local/include/except.h:5:44: fatal error: config.h: No such file or directory
compilation terminated.
Makefile:516: recipe for target 'xmlparse.lo' failed
make[2]: *** [xmlparse.lo] Error 1
make[2]: Leaving directory '/usr/bin/libexpat-R_2_2_7/expat/lib'
Makefile:570: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/bin/libexpat-R_2_2_7/expat'
Makefile:477: recipe for target 'all' failed
make: *** [all] Error 2

I am not well versed in installing packages like this, so I would appreciate any help in interpreting what exactly has gone wrong in my attempts to install expat.

**Comment by noloader** [comment]
This looks unusual to me:

```
In file included from /usr/local/include/assert.h:5:0,
from xmlparse.c:39:
/usr/local/include/except.h:5:44: fatal error: config.h: No such file or directory
compilation terminated.
```

How did you get `<assert.h>` in `/usr/local/include/`? That is usually a standard header, it is provided as part of the compiler, and usually located at `/usr/include`.

This looks very unusual:

    /usr/local/include/except.h:5:44: fatal error: config.h: No such file or directory

It seems like (to me) `except.>` should be in a package folder, like `/usr/local/include/<foobar>/except.h`. Then, `config.h` would be side-by-side with it, and `except.h` would `#include "config.h"`.

All in all, something looks incorrect with the installation.

**Comment by hartwork** [comment]
I'm with @noloader here — looks like a system setup issue. I will close this issue. Happy to re-open as needed.
