### ISSUE TITLE
Double free of DTD element type

### ISSUE THREAD

**Issue by RMJ10** [libexpat/libexpat#3]
lib/xmlparse.c line 5887: if the allocation of an ElementType's default attribute fails, the element type itself will be freed.  Unfortunately the earlier call to lookup() has already stored the new element type structure in the DTD.  When dtdDestroy() is inevitably called on the DTD, the element type will be freed again.

test_alloc_dtd_copy_default_atts introduced in RMJ10/libexpat commit 4499b07ad83ea29cdd06e95f59bfcff3ab68b75d provokes the problem.

RMJ10/libexpat commit 574766948e576c7a2793469e6cec1bf07442dc78 has the obvious fix of removing the call to ms->free_fcn().  This does not appear to cause problems.

**Comment by hartwork** [comment]
Excellent! The patch is applied on master and a small change log entry was added too.
