### ISSUE TITLE
cppcheck :   [lib/siphash.h:218]: (error) Expression :  depends on order of evaluation of side effects

### ISSUE THREAD

**Issue by kkkunche** [libexpat/libexpat#303]
kkunche@kishore-linux:~/libexpat/issue_new/libexpat/expat$ cppcheck --quiet --error-exitcode=1 --force .
[lib/siphash.h:218]: (error) Expression 'while(p<pe&&H.p<(&(H.buf)[sizeof(H.buf)/sizeof(*H.buf)]))*H.p++' depends on order of evaluation of side effects
[lib/siphash.h:218]: (error) Expression 'while(p<pe&&H.p<(&(H.buf)[sizeof(H.buf)/sizeof(*H.buf)]))*H.p++=*p++' depends on order of evaluation of side effects

**Comment by hartwork** [comment]
Which version of cppcheck are you using?

**Comment by hartwork** [comment]
My cppcheck 1.88 does not report it and the report looks like a false positive to me, from a quick look.

**Comment by kkkunche** [comment]
My version is 1.72.

**Comment by hartwork** [comment]
If neither the version in CI nor the latest release 1.88 show it and it's false positive let's not change the code. Okay?

**Comment by kkkunche** [comment]
Should be fine. thanks
