### ISSUE TITLE
expat_static build not working as expected

### ISSUE THREAD

**Issue by mzimmers** [libexpat/libexpat#311]
I'm trying to create a standalone Windows app. To this end, I'm trying to build a static version of Expat. I see that there is a project named "expat_static" in your VS solution, which produces a file "libexpatMT.lib." This would seem to be what I need. It builds successfully, but when I try to use this library, none of the symbols I need are found.
![expat](https://user-images.githubusercontent.com/1409026/63127069-53805700-bf66-11e9-92f5-d60a9da604fa.png)
Am I somehow building this file incorrectly? Seems fairly turnkey to me.

EDIT:

I was indeed building it incorrectly - I hadn't chosen a 64-bit platform. Now that I've fixed this, though, I'm getting other undefined references:
![expat](https://user-images.githubusercontent.com/1409026/63129885-998ce900-bf6d-11e9-904a-68e1dab41e5b.png)

Anyone got some words of wisdom for this?

EDIT again:

Found the problem: the /GS switch was enabled in the compiler options. Sorry for the spurious issue.

**Comment by hartwork** [comment]
Hi M,
sounds like all your questions found an answer already. Thanks for the update!
I'll close the ticket. Happy to re-open later if needed.
Best!
