### ISSUE TITLE
How can i install expat lib of a particular version in ubuntu ?

### ISSUE THREAD

**Issue by PradhanBangalore** [libexpat/libexpat#320]
I want to install old expat lib version (2.0.0) in ubuntu, how can i do that ?

**Comment by hartwork** [comment]
Expat 2.0.0 is from 2006 — 13 years ago. Why do you want Expat as old (and vulnerable) as that?

You can clone this repository, checkout tag `R_2_0_0`, fix the build system to work with today's tools, compile from sources, install.

```console
# cd "$(mktemp -d)"
# git clone https://github.com/libexpat/libexpat.git
# cd libexpat/expat/
# git checkout R_2_0_0 
# ./buildconf.sh && ./configure && make 
[..]
./configure: line 3482: syntax error near unexpected token `lt_decl_varnames,'
./configure: line 3482: `lt_if_append_uniq(lt_decl_varnames, SHELL, , ,'
```

**Comment by PradhanBangalore** [comment]
Already tried that. I am getting below error. Is that expected ? I was expecting xmlwf (or .exe) to be created under /usr/local/bin.

jdi@ubuntu:~/Desktop/libexpat-R_2_0_0/expat$ ./buildconf.sh && ./configure 
found: autoconf version 2.69 (ok)
found: libtool version 2.4.6
2003

2015 Free Software Foundation, Inc. (ok)
Copying libtool helper files ...
Using libtool.m4 from /usr/share/aclocal/libtool.m4.
Creating expat_config.h.in ...
configure.in:57: warning: LTOPTIONS_VERSION is m4_require'd but not m4_defun'd
conftools/libtool.m4:61: LT_INIT is expanded from...
conftools/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.in:57: the top level
configure.in:57: warning: LTSUGAR_VERSION is m4_require'd but not m4_defun'd
conftools/libtool.m4:61: LT_INIT is expanded from...
conftools/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.in:57: the top level
configure.in:57: warning: LTVERSION_VERSION is m4_require'd but not m4_defun'd
conftools/libtool.m4:61: LT_INIT is expanded from...
conftools/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.in:57: the top level
configure.in:57: warning: LTOBSOLETE_VERSION is m4_require'd but not m4_defun'd
conftools/libtool.m4:61: LT_INIT is expanded from...
conftools/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.in:57: the top level
Creating configure ...
configure.in:57: warning: LTOPTIONS_VERSION is m4_require'd but not m4_defun'd
conftools/libtool.m4:61: LT_INIT is expanded from...
conftools/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.in:57: the top level
configure.in:57: warning: LTSUGAR_VERSION is m4_require'd but not m4_defun'd
conftools/libtool.m4:61: LT_INIT is expanded from...
conftools/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.in:57: the top level
configure.in:57: warning: LTVERSION_VERSION is m4_require'd but not m4_defun'd
conftools/libtool.m4:61: LT_INIT is expanded from...
conftools/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.in:57: the top level
configure.in:57: warning: LTOBSOLETE_VERSION is m4_require'd but not m4_defun'd
conftools/libtool.m4:61: LT_INIT is expanded from...
conftools/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.in:57: the top level
configure.in:56: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:3500: error: possibly undefined macro: m4_ifval
configure:8156: error: possibly undefined macro: LT_INIT
configure:8156: error: possibly undefined macro: _LT_SET_OPTIONS
./configure: line 3355: AC_LIBTOOL_WIN32_DLL: command not found
./configure: line 3362: LTOPTIONS_VERSION: command not found
./configure: line 3363: LTSUGAR_VERSION: command not found
./configure: line 3364: LTVERSION_VERSION: command not found
./configure: line 3365: LTOBSOLETE_VERSION: command not found
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
./configure: line 3498: syntax error near unexpected token `lt_decl_varnames,'
./configure: line 3498: `lt_if_append_uniq(lt_decl_varnames, SHELL, , ,'

**Comment by hartwork** [comment]
> Already tried that. I am getting below error. Is that expected ?

It's the same error that I mentioned above. It's because you try to compile software from 13 years ago on an operating system that does not match that age.

> I was expecting xmlwf (or .exe) to be created under /usr/local/bin.

`.exe` is Windows. You'll need successful `./configure && make && sudo make install` to find `xmlwf` in `/usr/local/bin`.

I'll close this ticket as "not supported in 2019".
