### ISSUE TITLE
 Install the expat-2.2.7,but the apr-util also say the expat.h not found

### ISSUE THREAD

**Issue by mocaibupt** [libexpat/libexpat#327]
I want to install subversion in a server,but I have not the root Permission.Also the apt-get can't be used,and When I try to use dbkg install .deb file ,it tell me that need the superuser privilege,So I must install by SourceCode.tar. 
And I installed apr and apr-util.
When I install apr-util,the screen show that the expat.h not found.
So I install the expat in /data/my/software.
But the screen also tell me that the expat.h not found.
I try to change the file from "#include <expat.h>" to "#include /datamy/software/expat/include/expat.h".Then the apr-util install successful.
But When I ./configure in subversion folder,The “Expat not found”,how can I solve this issue?Can you give me some suggestion?Thanks very much!!!

**Comment by hartwork** [comment]
Hi!

The problem you describe is **not specific to Expat** and this issue tracker is about bugs or supposed bugs in Expat — it's not a generic support forum. To still give some pointers:
- If you don't have root on the server, then why not, and why not fix the actual problem — lack of permissions on the server — ?
- If you insist that you cannot get permissions, why not use package manager that supports unprivileged installation of packages on top of your current GNU/Linux distro? I can think of Linuxbrew, Stow,  Gentoo prefix, Nix for that task right now — there are more. is none of these an option?
- If you want to do every single dependency by hand: Do not change the `#include`s in the code — extend the list of include and libdirs given to the compiler instead using `--with-expat=DIR` of the configure script of apr-util during compilation. Subversion might have a similar build parameter.

If you need help beyond that on this problem, please try something like https://www.linuxquestions.org/ instead. Good luck!
