### ISSUE TITLE
XML_LARGE_SIZE and XML_Parse API.

### ISSUE THREAD

**Issue by loopless** [libexpat/libexpat#348]
It seems to be that if expat is compiled with XML_LARGE_SIZE then the externally visible APIs 
XML_Parse, XML_ParseBuffer,XML_GetBuffer should also be modified to take size_t instead of 'int' for the 'len' parameters when XML_LARGE_SIZE is defined.

**Comment by hartwork** [comment]
I get your point but that cannot be done without breaking backwords-compatibility. On a side note, to parse files bigger than `sizeof(int)`, multiple calls to `XML_Parse*` are an option: The last call has `isFinal` 1, all previous calls `isFinal` 0. What do you think?

**Comment by loopless** [comment]
I see your point - you are right. It's not worth breaking the API when calling the API to process in chunks <2GB is the better way to process a >2GB XML. I was dealing with some source code that tries to gobble the whole file in one call, but clearly it's the callers problem to do things a bit smarter!

**Comment by hartwork** [comment]
Okay great, thank you!
