### ISSUE TITLE
Non-ASCII characters cause compiler warning

### ISSUE THREAD

**Issue by animalize** [libexpat/libexpat#355]
On my Simplified Chinese Windows, compiling the code will get two warnings:

>    d:\dev\cpython\modules\expat\xmltok.c : warning C4819: 
>
>   The file contains a character that cannot be represented in
>    the current code page (936). Save the file in Unicode format
>    to prevent data loss.

This just because of two dashes  `–` (`U+2013`) in the comments (see [location](https://github.com/libexpat/libexpat/blob/R_2_2_9/expat/lib/xmltok.c#L592-L598)): 
```c
  /* 0xD800–0xDBFF first 16-bit code unit or high surrogate (W1) */
  ...
  /* 0xDC00–0xDFFF second 16-bit code unit or low surrogate (W2) */
```
If replace `–` with  ASCII minus sign `-` (looks very similar), these warnings disappear.

**Comment by hartwork** [comment]
Hi @animalize, thanks for the report! Should be fixed now.
