### ISSUE TITLE
Regression testing using fuzzer corpus

### ISSUE THREAD

**Issue by bshastry** [libexpat/libexpat#367]
Hello,

Although continuous fuzzing is very good at catching bugs early, regression testing against fuzzer generated corpus can save fuzzer cycles by essentially forcing the committer to fix obvious issues (e.g., uncovered by fuzzer previously or present in a program path that has already been covered by the fuzzer) even before the oss-fuzz bots pick up the commit.

In this regard, I was wondering if you'd be interested in accepting a PR that essentially 
  - adds a standalone fuzz driver [like this](https://www.sqlite.org/src/artifact/d9f1a6f43e7bab45)
  - compiles this with sanitizer support (asan/msan/ubsan)
  - runs a minimized fuzzer corpus against each sanitizer as part of qa

**Comment by hartwork** [comment]
Hi Bhargava,

> runs a minimized fuzzer corpus against each sanitizer as part of qa

can you elaborate on that part? How much runtime is to be expected from a new CI task like this? are you roughly expecting a few minutes, more then 10 minutes, more then 20 minutes?

**Comment by bshastry** [comment]
Hi,

To be sure, I'll do an experiment and get back to you on how long this might take in total. In theory, if we want to run a full regression that would be `n_f * n_s * n_i` where `n_f` is total number of fuzzers (12 i.e., parse_fuzzer and parsebuffer_fuzzers for 6 different encodings each), `n_s` is total number of sanitizers (3 i.e., ASan, UBSan, and MSan), and `n_i` is the total number of inputs in corpus (have not checked this yet but it should be a few thousand).

If average execution throughput is 100 executions per second and we have a 1000 test case regression corpus, we may be looking at `1000 * 12 * 3 / 100 = 360` or 6 minutes. But in practice I feel we may take somewhere between 10 and 20 minutes in total.

**Comment by bshastry** [comment]
I tried to fetch the current fuzzer corpus, but that led to a 404. My guess is that it is related to https://github.com/google/oss-fuzz/issues/3078

Will update this thread once I have more concrete data about how long CIs may take to finish a full regression test
