### ISSUE TITLE
Broken PNG images inside HTML documentation

### ISSUE THREAD

**Issue by fturco** [libexpat/libexpat#368]
I have dev-libs/expat-2.2.8 on a Gentoo Linux system.

According to pngcheck, the following two PNG images from the HTML documentation are somewhat broken:

```
$ pngcheck /usr/share/doc/expat-2.2.8/html/*.png
/usr/share/doc/expat-2.2.8/html/expat.png  additional data after IEND chunk
ERROR: /usr/share/doc/expat-2.2.8/html/expat.png
/usr/share/doc/expat-2.2.8/html/valid-xhtml10.png  additional data after IEND chunk
ERROR: /usr/share/doc/expat-2.2.8/html/valid-xhtml10.png

Errors were detected in 2 of the 2 files tested.
```

Despite the previous error messages, I can correctly display both images with my web browser.

**Comment by hartwork** [comment]
Interesting! Does #369 look sane to you?

**Comment by fturco** [comment]
On my system `pngcheck` doesn't complain anymore after processing both PNG files with `zopflipng`. Same result after processing them with `convert` (from ImageMagick).

**Comment by hartwork** [comment]
I'll take that as a "good to merge" and go ahead with merging then :smile:

**Comment by fturco** [comment]
OK. Thanks for the fix!
