### ISSUE TITLE
newbie -- parsing question

### ISSUE THREAD

**Issue by dshuman52** [libexpat/libexpat#374]
I managed to compile the library and assembled the attached xmlDump.c file from a couple of sources with some additions of my own.  Please feel free to include it as an example, if desirable.  Please feel free to adjust the code as you see fit.

considering this text from near the bottom of your man page (the file that xmlDump is now set to use).

<
  <refsect1>
    <title>AUTHOR</title>
    <para>
	  This manual page was written by &dhusername; &dhemail; for
      the &debian; system (but may be used by others).  Permission is
      granted to copy, distribute and/or modify this document under
      the terms of the <acronym>GNU</acronym> Free Documentation
      License, Version 1.1.
	</para>
  </refsect1>
>

Why isn't all the text between <para> and </para> not considered text considering the <acronym>GNU</acronym> included in the text to be data and NOT an xml element?  This seems to be more of a markup highlighting issue than an xml element.  It also falsely includes 
<
	  This manual page was written by &dhusername; &dhemail; for
      the &debian; system (but may be used by others).  Permission is
      granted to copy, distribute and/or modify this document under
      the terms of the 
>
    as part of <acronym> instead of part of <para>.

What I believe I should expect is that once text mode is entered because we are not dealing with either of the following constructs
      <element ... />
      <element> {only whitespace} <anotherelement> ...</anotherelement> ...

In the above case the presence of the non-white space character T should keep us in text mode until the </para> terminator is encountered ignoring the fact that <acronym>GNU</acronym> appears to be an xmlElement embedded in the text.

The answer to the first question could answer this one.  If my expectations above are correct then this question makes sense.
Why is the white space between <refsect1> and <title> being returned as text?
     Likewise between </title> and <para>
             and </para> and </refsect1>
             and </refsect1> and </refentry>
In this case any white space between  <element>  and <anotherelement>
                                                      or  </element> and <anotherelement>
                                                      or  </element> and </anotherelement> 
    should be not be reported back as text again if my assumptions are correct.

Last question: I may not have looked the right place but is there a way to have comments returned probably as text elements Identifiable as they would have a  in the last 4 characters.

Thanks

David Shuman

[xmlDump.zip](https://github.com/libexpat/libexpat/files/4087157/xmlDump.zip)

**Comment by dshuman52** [comment]
[text.zip](https://github.com/libexpat/libexpat/files/4087170/text.zip)

Sorry the text got garbled.  Here is a zipped version of the text that should not be garbled.

Thanks again.

**Comment by dshuman52** [comment]
The proper answer to the acronym  /acronym is probably to use escaped &gt; and &lt; instead of the proper characters because these attribute indicators could be at the beginning and/or end of the text for an item like para /para.

**Comment by hartwork** [comment]
Hi! I must say that this easily the hardest to understand ticket I have had in a long time. For the question about white space, https://www.w3.org/TR/REC-xml/#sec-white-space might already give an answer. For the rest I am not even sure what the questions are. While mostly this place is a bug tracker and not a support forum, I'm happy to help provided that I get clear questions with proper [markup syntax](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax). Do we have a deal?

**Comment by dshuman52** [comment]
Question 1 in the following text is the text
                               <              <acronym>GNU</acronym>                 >
part what I believe is a text string as follows or an XML element with a text string of it's own?

<
  <refsect1>
    <title>AUTHOR</title>
    <para>
	  This manual page was written by &dhusername; &dhemail; for
      the &debian; system (but may be used by others).  Permission is
      granted to copy, distribute and/or modify this document under
      the terms of the <acronym>GNU</acronym> Free Documentation
      License, Version 1.1.
	</para>
  </refsect1>
>

If < <acronym>GNU</acronym> > is an XML element embedded in the middle of the para - /para text; how can para - /para have two text strings?  If the above are valid questions and reasoning this is a bug because when this is returned by expat as parsed tokens.  I believe the substututions for < &dhemail; and  &debian; > in addition to < <acronym>GNU</acronym> > have reduced the parsed string for < <para> - </para> > to "Free Documentation
      License, Version 1.1.".  What I interpret as < <para> - </para> > before that becomes part of what appear to be 3 embedded XML elements < <email>, <productname> via substitution and <acronym> directly in the text > that should not have been considered XML elements at all.

Output of parsing the < <para> - </para> > XML element.

    2  para

      3  email

      3  Content of element email's text was


          This manual page was written by Scott Bronson bronson@rinspin.com

      3  productname

      3  Content of element productname's text was
 for
      the Debian GNU/Linux

      3  acronym

      3  Content of element acronym's text was
 system (but may be used by others).  Permission is
      granted to copy, distribute and/or modify this document under
      the terms of the GNU

    2  Content of element para's text was
 Free Documentation
      License, Version 1.1.

**Comment by dshuman52** [comment]
Second question in the following text there is what in a well formed documentation would be considered insignificant white space as noted in the document you sent me.

"In editing XML documents, it is often convenient to use "white space" (spaces, tabs, and blank lines) to set apart the markup for greater readability. Such white space is typically not intended for inclusion in the delivered version of the document. On the other hand, "significant" white space that should be preserved in the delivered version is common, for example in poetry and source code."

<
<refentry>
  <refentryinfo>
    <address>
      &dhemail;
    </address>

>

The line feeds and spaces between each of the following < <refentry> & <refentryinfo>, </refentryinfo> & <address>,  </address> & &dhemail; (that Expands to <email> ... </email>  > are accumulated and reported as part of the text when the results for <  </email> > are returned.  Remove the space trimming code from my app and you can plainly see exactly the line feeds and spaces in the appropriate order being returned in I believe several pieces as the documentation notes xml text can be returned in pieces.

I believe this is an error however the answer to the first question could change that.

My last question was whether or not comments could be returned (optionally of course) . a possible coding specfication could be to return an empty string for element with the entire comment in the text.  Meaning in the end processing the decrement of the depth counter would need to be bypassed when ever there is a blank element or a comment in the text (both mean the same thing in this case).

Thanks

**Comment by dshuman52** [comment]
I tried again to explain this by putting the xml headers and trailers inside of < ... > so they should have been treated like code.  The message got garbled again.  I will try to explain where and xml header referenced in the text will appear as a double quoted string so it does not disappear.  in the following code

<
   <para>
	  This manual page was written by &dhusername; &dhemail; for
      the &debian; system (but may be used by others).  Permission is
      granted to copy, distribute and/or modify this document under
      the terms of the <acronym>GNU</acronym> Free Documentation
      License, Version 1.1.
	</para>
>

NOTE: "(and)dhusername(semicolon)" expands to an "email" and "/email" construct
           "(and)debian(semicolon)"          expands to a "productname" and "/productname" construct
in addition to the explicit "acronym" and "/acronym" construct.

In the output that follows  the text associated with the end tags is as follows:
"/email" - "This manual page was written by Scott Bronson bronson@rinspin.com"
"/productname" - " for
      the Debian GNU/Linux"
"/acronym" -  " system (but may be used by others).  Permission is
      granted to copy, distribute and/or modify this document under
      the terms of the GNU"
"/para" - " Free Documentation
      License, Version 1.1."

I do not believe these are the appropriate values.  The text that arrives because of "/para" should not be broken into 4 pieces with three of those pieces assigned to XML tags NOT NAMED "/para?.  I believe the entire text between "para" an "/para" should be returned as text for the "para" element.  Possibly the "gt" and "lt" symbols should be changed to their XML escaped counterparts so this can happen.  Meaning the XML man document for expat may not be a "well formed document".  I believe the translation of escaped characters could be done after the determination of the correct "para" text content and  before libexpat returns the "para" text to the user app in this case.

Output of the app I included:

<

    2  para

      3  email

      3  Content of element email's text was


          This manual page was written by Scott Bronson bronson@rinspin.com

      3  productname

      3  Content of element productname's text was
 for
      the Debian GNU/Linux

      3  acronym

      3  Content of element acronym's text was
 system (but may be used by others).  Permission is
      granted to copy, distribute and/or modify this document under
      the terms of the GNU

    2  Content of element para's text was
 Free Documentation
      License, Version 1.1.

>


Item 2 -- per the document you referred me to

"In editing XML documents, it is often convenient to use "white space" (spaces, tabs, and blank lines) to set apart the markup for greater readability. **Such white space is typically not intended for inclusion in the delivered version of the document.** On the other hand, "significant" white space that should be preserved in the delivered version is common, for example in poetry and source code."

Consider the following code (I removed a line with a "and...;" variable to simplify the explanation.

The linefeed and spaces between "copyright" and "year" are returned when "/year" is processed in addition to the text "2001"

The linefeed and spaces between "/year" and "/copyright" I believe are returned as a text element for "copyright" when it has NONE.

I believe these both are errors.  My code has white space trimming logic for the end of each segment of text returned by libexpat that eliminated most of that problem.  The insignificant white space seems to be delivered as separate text segments.
<

    <copyright>
      <year>2001</year>
    </copyright>

>

Lastly I asked if optionally XML comments could be returned to the user.  I would suggest the mechanism would be to send a empty string as the element and the entire comment as text possibly in pieces like other text.  This would mean when this happens the depth tracking integer DOES NOT get decremented in the end process.

Thanks 

I hope this is better as I have compensated for the gobbling of text I entered by the processing this window uses.

I almost forgot the following is the subversion link I used to get the library code I compiled.

<

https://github.com/libexpat/libexpat.git/tags/R_2_2_9

>

**Comment by dshuman52** [comment]
This product is already almost what  I considered writing myself ( a less generic version).  It has the potential to be a real timesaver in the project I was considering.

**Comment by hartwork** [comment]
Part of what you mention seems related to https://libexpat.github.io/doc/common-pitfalls/#split-character-data . For handling comments, please see `XML_SetCommentHandler` and file `doc/reference.html`. That's all I can do here, I'll be closing this ticket.

**Comment by dshuman52** [comment]
Item3 above, I found the comment handler and have working, sorry I missed it earlier.
Item2 above - insignificant white space.
Saw the comments from James Clark that he considers all white space to be significant.  I have some code that is fairly effective at eliminating insignificant white space.  Basically it drops the entire array passed to the character handler when it is all white space and there are no non-white space characters already queued to the buffer.  Second I look to clear the buffer in Start and End element and when a comment is received.  I am interpreting it as an error if Start Element or the Comment handler have non whitespace in the queued buffer.  I may have seen a place or two where significant white space may be being dropped but I am close enough to working for my requirements.
Issue 1 -- due to what I learned about XML from the xmlwf.xml (help?) file I created a modified version (attached as xmlwf.mod.xml.  It escapes all the XML-like headers and trailers so the document parses as I believe it should.  Unless I made a typo in terms of content, I believe they are identical.  In practice I do not know what reads and displays this flle so functionally it has NOT been tested.

I will spend a little more time to see if one of your calls process the DOCTYPE and ENTITIES at the start of the file.  If so once I add that to the processing I will submit my final items.

The xmlDump app I assembled and improved in conjunction with the original and modified xmlwf.xml files would be a pretty good initial app to learn about how to use expat functions.  You may consider whether or not my minor contribution merits inclusion in the examples for a library that works far better than the skeletal code I assembled from multiple sources showed me was possible.  I plan on cleaning up the comments and addine the one more function before I send the final copy.

[xmlwf.mod.zip](https://github.com/libexpat/libexpat/files/4093395/xmlwf.mod.zip)

[xmlDump.zip](https://github.com/libexpat/libexpat/files/4093397/xmlDump.zip)

**Comment by dshuman52** [comment]
The split data is not the issue in my case -- review how your version of xmlwf.xml in the doc folder is parsed compared to my version xmlwf.mod.xml.  The differences will be evident when you check the results of the last paragraphs of the document.  They are apparent elsewhere but the tail end of the document is where I was pointing out the problem.  Escaping the tags that are XML-like but not XML based on the rules I understand (xml tags should not appear in the middle of text items and expect to be properly parsed)   eliminated there interfering with what I consider to be the proper parsing of the file..  It is kinda like commenting code and the compiler attempting to compile the comments because they look like code.

If you do not want to consider what I am doing as a possible example I would appreciate knowing so I do not bother you further.

**Comment by hartwork** [comment]
> If you do not want to consider what I am doing as a possible example I would appreciate knowing so I do not bother you further.

>> That's all I can do here, I'll be closing this ticket.

I'm giving up here — I'm not compatible with this style of communication (and/or your ideas) and my energy is limited, sorry. So let's stop here, yes.

**Comment by dshuman52** [comment]
will do.
