### ISSUE TITLE
Support for XML 1.1?

### ISSUE THREAD

**Issue by mforkel** [libexpat/libexpat#378]
Expat currently implements XML 1.0, not XML 1.1. The intention to support XML 1.1 [was expressed about 16 years ago](https://sourceforge.net/p/expat/bugs/292/). Any chance this will ever happen? I'm asking because the limited set of supported characters [breaks XML-RPC in Python](https://bugs.python.org/issue11804).

**Comment by hartwork** [comment]
Hi @mforkel , there is no current plan to support for XML 1.1 or even XML 1.0r5 (#171) and there has been little demand for that feature in practice in the last 15 years that I would be aware of.

**Comment by hartwork** [comment]
I'll close this for lack of a reply. I'm happy to re-open this ticket as needed.

**Comment by kohsuke** [comment]
Just wanted to add my vote for this feature. I needed XML 1.1 to represente xUnit test reports. Those files capture stdout/stderr from tests, and people often use escape sequences to decorate output, which results in control characters.

 I'm using Python's `xml.etree` package to parse them, which in turn use slibexpat underneath, according to https://stackoverflow.com/questions/61228807/parse-xml-1-1-control-characters-with-xml-etree-elementtree

**Comment by mforkel** [comment]
Well, I'd still be happy to see this fixed :-)
