### ISSUE TITLE
Evaluate (already supported) MinGW cross-compilation for future Windows binary releases

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#38]
Is moving Windows binary creation to MinGW cross-compilation something that is worth the trouble and will resulting binaries work for everyone?

**Comment by kwaclaw** [comment]
What would be improved? It seems to me that on Windows the best tool to use
is Visual Studio.
Visual Studio Community edition is free, btw.

**Comment by RMJ10** [comment]
It depends on what you mean by "work for everyone".  `wchar_t` is 16-bits in GCC under MinGW, for instance, but is 32-bits on my Linux box.  Compiling with `XML_UNICODE_WCHAR_T` will produce compatible libraries under MinGW and Visual Studio, but Windows and Linux versions will not be compatible.

On the plus side, MinGW is much easier to script.

**Comment by hartwork** [comment]
It would allow automated creation on non-Windows platforms at some point, yes.

**Comment by ntzrmtthihu777** [comment]
just adding my two cents: using crossdev on gentoo and `x86_64-w64-emerge dev-libs/expat` builds just fine. I personally don't use libexpat in my own projects so I can't say if they built right, but they do build.

**Comment by ntzrmtthihu777** [comment]
@RMJ10 well lets be honest, windows and linux are wholly different beasts anyways, so some incompatibility between the two builds is to be expected.
Is there a case where a simple/sample executable (say, a unit test or sommat) making use of `wchar_t` doesn't work oob with the same source code and compile opts?

**Comment by hartwork** [comment]
Crossdev MinGW seems to work with 2-byte `wchar_t`, which is fortunate. I compared:
```
# /usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3/gcc -dM -E - < /dev/null | fgrep __SIZEOF_WCHAR_T__
#define __SIZEOF_WCHAR_T__ 4

# /usr/x86_64-pc-linux-gnu/i686-w64-mingw32/gcc-bin/4.9.4/i686-w64-mingw32-gcc -dM -E - < /dev/null | fgrep __SIZEOF_WCHAR_T__
#define __SIZEOF_WCHAR_T__ 2
```

For build variations I see:
* `char`/UTF-8 (`expat.dll`) and `wchart`/UTF-16 (`XML_UNICODE_WCHAR_T`, `expatw.dll`) versions
* static and dynamic (static possible?)
* `i686-w64-mingw32-gcc` and/or(?) `x86_64-w64-mingw32`

**Comment by kwaclaw** [comment]
Well, if I am a Windows developer I simply expect that I will able to do a
build using Microsoft's compiler (Visual Studio).

On top of this, the build files have essentially never necessitated manual
intervention, as they were auto-upgraded several times through Visual
Studio. Maintenance work is minimal.

So even if someone wants to contribute a MinGW build we would need to keep
the VS build files.

Karl

**Comment by hartwork** [comment]
> So even if someone wants to contribute a MinGW build we would need to keep the VS build files.

We're on the same page with that.

**Comment by RMJ10** [comment]
> On top of this, the build files have essentially never necessitated manual intervention, as they were auto-upgraded several times through Visual Studio. Maintenance work is minimal.

@kwaclaw That's true until you add files as a Linux developer.  Then you have to manually fix up the .vcxproj files, something I have got wrong in the past.  That said, I completely agree that we need to retain VS as a target.  I just don't want to underestimate the overheads involved.

**Comment by xantares** [comment]
I dont think this is worth the trouble, mingw packages are easily installed through msys or your favorite linux distro (fedora, arch) these days.

**Comment by hartwork** [comment]
The idea is to build "normal" Windows DLLs for use with the current Inno Setup installer for people with "plain" Windows, i.e. no msys, no Linux.

**Comment by xantares** [comment]
right, I forgot that the c abi is msvc compatible so you can use it with microsoft compilers

**Comment by hartwork** [comment]
If we went with MinGW binaries, we would need to ship…

- `libgcc_s_sjlj-1.dll`
- `libwinpthread-1.dll`
- `libstdc++-6.dll`

…as well and so would everyone that wants to use those binaries. I'm unsure if that's a good idea.
