### ISSUE TITLE
Adding additional output of testing results

### ISSUE THREAD

**Issue by Oleksandr-Popovych** [libexpat/libexpat#382]
Hello,

What do you think about adding console output of testing results during execution of **runtests** and **runtestspp** applications, and implementing some tools for turning this output on/off? For example showing detailed list of all tests and results (failed/succeeded/skipped/etc.) and implementing additional arguments that can be passed to testing application. 

On my opinion, this can supply additional information about testing in common. And I think this feature will be a good supplement to already present output of file test name and line in case of test-case failure and will help in determining of failure of test itself or it's setup/tear down phase, etc.
Additionally such kind of log can help user to determine: Is test application stuck because of errors in newly written test-cases, or it's execution is just slowed down by any other reasons?

If you are interested in such kind of a feature, I can supply a Pull Request that implements it. 

Thanks for your attention.

**Comment by hartwork** [comment]
Hi Oleksandr,


thanks for offering to work on the Expat test code. If I get you right, you'd improve the layer between the actual tests and the human running the tests and looking at their output.  That's an area where other C/C++ testing frameworks — e.g. [googletest](https://github.com/google/googletest) — shine brighter than Expat's stripped-down fork of [libcheck](https://github.com/libcheck/check) and come with those features out of the box.  I'm not sure right now if we need to keep tests working in C and without external dependencies right now — that would need an answer, first.

Is there some bigger picture here with something following an improved test runner or is it about contributing to Expat, in general?  If it's about the latter, I would probably see more value with any of these:

- joining with billion laughs attack research — https://github.com/libexpat/libexpat/issues/34
- doing research on the XML 1.0r5 support matter — https://github.com/libexpat/libexpat/issues/171
- hunting the currently implemented XML 1.0r4 spec for things that Expat does wrong with regard to the spec, then testing and fixing it
- implementing UTF-32 support (— least needed but probably fun)

Best


Sebastian

**Comment by Oleksandr-Popovych** [comment]
Hello, Sebastian

Improved test runner for Expat is a part of my work on [Yocto/Openembedded project](https://www.yoctoproject.org/software-overview/). 
In few words this project helps to create, build deploy custom Linux distributives for different platforms and fill it with additional components (different executables, libraries, etc.) Components can be added in form of a 'package', and each package is built separately. It's built from source code, with some additional changes (if needed) that are applied to sources as a set of git patches. There is additional feature for any package called [Ptest](https://wiki.yoctoproject.org/wiki/Ptest). Ptest is just a simple building and running internal (for each sources) tests on target platform.

I hope this backstory will help in understanding what is my current work about. Expat library is present in Yocto project as a package. It has internal tests, so I decided to implement Ptest for this package. But there is one additional [requirement](https://wiki.yoctoproject.org/wiki/Ptest#What_constitutes_a_ptest.3F): each test included in Ptest needs to have an output (RESULT: NAME). And the easiest way to add such kind of an output is making changes into the source code (adding several prints in test runner code). For now these changes exist in form of a patch. But patches are not very suitable for long term support: it is better to try to contribute them upstream instead. So now my task is to find out can such kind of changes be contributed upstream, and contribute them (of course only if they are suitable for your project and do not change something that you are going to remove from library in the near future).

If I understand your explanation right:

>  That's an area where other C/C++ testing frameworks — e.g. googletest — shine brighter than Expat's stripped-down fork of libcheck and come with those features out of the box. I'm not sure right now if we need to keep tests working in C and without external dependencies right now — that would need an answer, first.

current version of your testing framework is not perfect, but it is doing it's job and even if you decide to change testing framework this will not be an urgent task, and it will not happen soon. According do this info, at least for now I can not recognise any barriers for contributing. If I'm wrong I'll be happy to hear why, and what alternatives can be proposed to satisfy everyone.

Thanks for your attention.

**Comment by hartwork** [comment]
Hello Oleksandr,

what you describe sounds a lot like packaging in Gentoo — it also has in-package testing and the [Yocto Expat package source](https://git.yoctoproject.org/cgit.cgi/poky/tree/meta/recipes-core/expat/expat_2.2.9.bb) could hardly be closer to a Gentoo ebuild.

They way I read [Implementing ptest in a package recipe](https://wiki.yoctoproject.org/wiki/Ptest#Implementing_ptest_in_a_package_recipe) you could probably use a `run-ptest` file similar to this one:
```console
# cat run-ptest
#! /usr/bin/env bash
make check >&/dev/null  # or to some log file
error=$?
result=$([[ ${error} -eq 0 ]] && echo PASS || echo FAIL)
echo "${result}: make-check"
exit ${error}
```
In packaging context, that's probably good enough? In a development context for Expat itself, I would consider format `result: testname` too limited to be of real value. If we want a better runner we should migrate to something C-based, existing, capable, self-contained, and integrate it into both the CMake and Autotools build systems while we have both... rather than pimping the current fork with more custom code and complexity. Given your Yocto context, this project would be quite overkill probably but if you find a good candidate and provide a pull request that's easy to review and passes the current pile of CI checks, okay. What do you think?

**Comment by hartwork** [comment]
@Oleksandr-Popovych what do you think?

**Comment by Oleksandr-Popovych** [comment]
Hello @hartwork,

Thank you for your advice about `run-ptest` script. This will help me in writing some starter version of testing package.

And about testing runner migration: Indeed, with this migration, my task seems to be getting much larger than I expected. And I'm sorry to say this, but currently I am not ready to provide a PR suitable for your requirements... At least for now. 
Maybe in near future I'll take up this task and/or find somebody for help, or even anyone else will be inspired to do it.

Anyway, thank you for your attention and support.

**Comment by hartwork** [comment]
Okay good. I'll close the ticket for now then.
