### ISSUE TITLE
VS2010 and above support without solution upgrades

### ISSUE THREAD

**Issue by noloader** [libexpat/libexpat#384]
This may be an enhancement Expat is interested in...  I was reading the comment for [Commit 309ad17f97fe](https://github.com/libexpat/libexpat/commit/309ad17f97fe). The 309a commit concerns itself with Visual Studio and project upgrades due to Visual Studio versions.

Those forced upgrades are annoying as hell. Users expect things to "just work" and I consider them a Microsoft UI bug. User should not have to do anything special to open a project. The upgrades also fail on occasion so projects like Expat catch Microsoft bugs. The upgrades are a lose-lose any way you slice them.

You can avoid the broken workflows and forced upgrades by setting the minimum Visual Studio version to 2010 like so in your *.vcxproj files. Someone with a higher version of Visual Studio will "just work" without upgrade prompts. It "just works" because VS2012 and above set `DefaultPlatformToolset`, which avoids the forced upgrade. VS2010 does not set `DefaultPlatformToolset`, which is why you need to import `Microsoft.Cpp.Default.props` and provide a default value for `DefaultPlatformToolset` if not set.

```
  <!-- Use DefaultPlatformToolset after Microsoft.Cpp.Default.props -->
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <!-- Set DefaultPlatformToolset to v100 (VS2010) if not defined -->
  <PropertyGroup Label="EmptyDefaultPlatformToolset">
    <DefaultPlatformToolset Condition=" '$(DefaultPlatformToolset)' == '' ">v100</DefaultPlatformToolset>
  </PropertyGroup>
  <PropertyGroup Label="PlatformToolset">
    <PlatformToolset>$(DefaultPlatformToolset)</PlatformToolset>
  </PropertyGroup>
```

Also, your *.sln file should be changed to:

```
Microsoft Visual Studio Solution File, Format Version 11.00
# Visual Studio 2010
```

[Crypto++](https://github.com/weidai11/cryptopp) switched to the pattern above because so many users were complaining about Visual Studio versions, the useless prompts and failed upgrades due to some custom build steps the upgrade wizard could not handle. Crypto++ has four projects, and all of them have been using the pattern for about 4 or 5 years now. We have not gotten one complaint since switching. Also see project files like [`cryptlib.vcxproj`](https://github.com/weidai11/cryptopp/blob/master/cryptlib.vcxproj#L48).

----

And to be clear, this is what is getting you in trouble with the project files and leading to the useless prompts and upgrades. It is the hard-coded Visual Studio version number:

```
<PlatformToolset>v120</PlatformToolset>
```

Don't hard-code the version. Use `$(DefaultPlatformToolset)` instead.

**Comment by hartwork** [comment]
There are no more `.sln` or `.vcxproj` files in Expat since 2.2.8 — they were dropped in 71485dcf8b2b32ece2852d2c35831b102c6568b7 . Is there anything more to do here or can this ticket be closed?

**Comment by noloader** [comment]
Oh, my bad. No, nothing else to be done.
