### ISSUE TITLE
MUST_CONVERT bit test on an address?

### ISSUE THREAD

**Issue by noloader** [libexpat/libexpat#390]
Hi Everyone,

I wandered into `MUST_CONVERT` while examining `xmlparse.c`. This test caught my eye:

```
# define MUST_CONVERT(enc, s) \
    (! (enc)->isUtf16 || (((char *)(s) - (char *)NULL) & 1))
```

I _think_ that test should convert `s` to a `intptr_t` or `uintptr_t` and then mask off-the upper bits. I also see a fair amount of code that converts to `size_t`, but I think `intptr_t` or `uintptr_t` is the correct way to do it.

As written, that may be undefined behavior. I don't recall bit operations being defined for pointers. About all you can do is add, subtract, compare for equality (`==`) and compare for ordering (`<`, `<=`, etc).

So maybe the test should use something like the following. On the bright side, Posix says `uintptr_t` is [located in `<stdint.h>`](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdint.h.html), so it is mostly ubiquitous.

```
((uintptr_t)(char *)(s)) & 1
```

**Comment by hartwork** [comment]
> I wandered into `MUST_CONVERT` while examining `xmlparse.c`. This test caught my eye:
> 
> ```
> # define MUST_CONVERT(enc, s) \
>     (! (enc)->isUtf16 || (((char *)(s) - (char *)NULL) & 1))
> ```

Interesting catch!

> As written, that may be undefined behavior. I don't recall bit operations being defined for pointers.

The bit operation is not done on a pointer but on an integer of type `ptrdiff_t` of [guaranteed size >=16 bits](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdint.h.html). 16 bits might be too hold results of a self-made cast of arbitrary pointers so I agree we have a problem in the current code.

Related commits of interest:
- c71f27573bd0205558a78792b554764f9c962179
- c7880974e682c20e23737108548a094f777eff08

> So maybe the test should use something like the following. On the bright side, Posix says `uintptr_t` is [located in `<stdint.h>`](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdint.h.html), so it is mostly ubiquitous.
> 
> ```
> ((uintptr_t)(char *)(s)) & 1
> ```

I'd be with you on `uintptr_t` but it's marked optional, e.g. at https://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdint.h.html , so we might need something more portable if all we require is a C99 compiler. What do you think?

**Comment by noloader** [comment]
> The bit operation is not done on a pointer but on an integer of type ptrdiff_t of guaranteed size >=16 bits.

It took some searching but [here's the problem](https://stackoverflow.com/a/51220772)... Pointer subtraction does yield a `ptrdiff_t`, but only if the same array. `(char*)s` and `(char*)NULL` point to different objects, so it is undefined behavior.

> uintptr_t but it's marked optional

Ugh, yeah....

Finding `ptrdiff_t` and `uintptr_t` in a header caused me problems over the years. I *think* I found one of the ways to assemble the puzzle ([from here](https://github.com/weidai11/cryptopp/blob/master/stdcpp.h#L75)):

```
// uintptr_t and ptrdiff_t
#if defined(__SUNPRO_CC)
# if (__SUNPRO_CC >= 0x5100)
#  include <stdint.h>
# endif
#elif defined(_MSC_VER)
# if (_MSC_VER >= 1700)
#  include <stdint.h>
# else
#  include <stddef.h>
# endif
#elif (__cplusplus < 201103L)
# include <stdint.h>
#endif
```

The code above is tested on the Unixes (AIX, BSDs, Linux, OS X, Solaris). But it is also tested on Windows XP and above using Visual Studio 2002 and above.

Given Expat is Autotools and CMake, this would probably suffice after feature testing:

```
#ifdef HAVE_STDINT_H
#include <stdint.h>
#endif
#ifdef HAVE_STDDEF_H
#include <stddef.h>
#endif
```

**Comment by hartwork** [comment]
I notice now that if (1) casting to smaller types causes truncation and (2) we're only interested in the lowest bit, why not just:
```
((unsigned int)s) & 1
```
or
```
(unsigned int)s & 1
```
?
