### ISSUE TITLE
Travis: Cache xmlts.zip

### ISSUE THREAD

**Issue by yukiisbored** [libexpat/libexpat#40]
On https://github.com/libexpat/libexpat/blob/master/.travis.yml#L12, xmlts.zip can be cached to prevent redownloading and build failures due to networking issues (which is pretty common in Travis)

**Comment by hartwork** [comment]
Hi! Can you help out with a link on how to best do that or a pull request?

**Comment by yukiisbored** [comment]
@hartwork https://docs.travis-ci.com/user/caching/#Arbitrary-directories

**Comment by hartwork** [comment]
I gave it a try now, non-master commit df9f2c09cb0f43307ce2345f8c75b0cc7ccdc90f. With protection against partial/broken downloads it's rather ugly.
Looking at the [related Travis build](https://travis-ci.org/libexpat/libexpat/builds/243035944), I see [`could not download cache`](https://travis-ci.org/libexpat/libexpat/builds/243035944#L307). Any ideas on how to continue?

**Comment by hartwork** [comment]
Closing, but feel free to re-open as needed.
