### ISSUE TITLE
Expat target interface include directories seems to be missing

### ISSUE THREAD

**Issue by vmo6trl** [libexpat/libexpat#416]
Hello,

It seems Expat target does not define an INTERFACE_INCLUDE_DIRECTORIES in the generated cmake-noconfig.cmake file. 

When expat is used as a dependency with cmake, there is no include directory associated. In some cases it works because when it is installed in a common include directory of the system, other dependencies might already set this directory as included. But I encountered cases in which the "expat.h" header cannot be found because the include directory of expat was not exported and no other dependency included the directory to find it.

The message was the following whereas expat was correctly found with the find_package command previously:
```
In file included from <file>.c:24:0:
<file>.h:27:19: fatal error: expat.h: No such file or directory
 #include "expat.h"
                   ^
compilation terminated.
```

The easiest reproducer should be to install Expat in a custom path and try to build a project pointing to the CMake config file in the custom path ("expat.h" should not be present elsewhere to avoid another is found). It requires to set the path in `CMAKE_PREFIX_PATH` or define `expat_DIR` to the custom install path.

I thinks something like the following line is missing in the generated cmake-noconfig.cmake:
```
set_target_properties(expat::expat PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  ....
)
```

I guess it is due to the fact following property is not defined in the CMakeLists.txt file of Expat.
Something like that should do the trick:
```
target_include_directories(${_EXPAT_TARGET} PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/lib>
  $<INSTALL_INTERFACE:include>
)
```

Best regards,
Vincent

**Comment by hartwork** [comment]
Hi Vincent,

have you seen this code on `master` in `CMakeLists.txt`?:
https://github.com/libexpat/libexpat/blob/1bb22cd03ab1ad48efb2bdee08cb805b5b593ea5/expat/CMakeLists.txt#L314-L319

If that doesn't already fix the issue, I'll need your help understanding this in more detail. Can you make a minimal reproducable example that I can run in a sandbox then to see things with my own eyes?

Best, Sebastian

**Comment by vmo6trl** [comment]
Hi Sebastian,

Thank you for your answer. I did not indicate I was using the 2.2.9 version and indeed I did not check the current CMakeLists.txt version on master. I'll check this fixes the issue when next libexpat version is released but it looks good to me. 
Sorry about that, I close the issue then.

Best regards,
Vincent

**Comment by hartwork** [comment]
Thanks for the update!
