### ISSUE TITLE
GPG signed releases

### ISSUE THREAD

**Issue by zaolin** [libexpat/libexpat#42]
Hey,

Please sign your releases so that other projects can verify them.
More information can be found on:

https://help.github.com/articles/generating-a-new-gpg-key/

Kind Regards, Philipp

**Comment by hartwork** [comment]
Here you go: https://github.com/libexpat/libexpat/releases/tag/R_2_2_1

The command used for tagging was:
```
# GIT_COMMITTER_EMAIL=sping@gentoo.org git tag -m '' -u 3D7E959D89FACFEE38371921B00BC66A401A1600 R_2_2_1 c4446687cfc6c5fd7f6371aeaf24c69402a3589e
```
Without `GIT_COMMITTER_EMAIL` complained that the mail addresses did not match and did not label the tag as "verified".

**Comment by hartwork** [comment]
More recent usage with 2.2.8:
```
# GIT_COMMITTER_EMAIL=sping@gentoo.org git tag -m '' -u 3176EF7DB2367F1FCA4F306B1F9B0E909AF37285 R_2_2_8 release-2-2-8
```
