### ISSUE TITLE
Expat(2.2.9 or 2.2.10) ) support for MacOS Big Sur(Cross compilation for ARM architecture/Apple silicon)?

### ISSUE THREAD

**Issue by vinaykumarlaxman** [libexpat/libexpat#427]
Hi All,

As Apple is moving from Intel to ARM architecture, does Expat(2.2.9 or 2.2.10) support cross-compiling(using Xcode 12.2) on MacOS Big Sur for Apple silicon(ARM architecture)?
If not, any expected date?

Thanks,
Vinay

**Comment by hartwork** [comment]
Well, have you tried? [CMake has an XCode generator](https://cmake.org/cmake/help/v3.0/generator/Xcode.html) it seems. If you run into issues please open a bug report and we'll see what can be done. Thanks!
