### ISSUE TITLE
expat-config.cmake not created

### ISSUE THREAD

**Issue by Waner98** [libexpat/libexpat#429]
Hi,

I need to use the "expat-config.cmake" file for another programm but when i make all the compilation steps for expat, I do not see this file generated in /expat/cmake/ . 

Do someone knows how to solve my problem?

Thank you :)

**Comment by hartwork** [comment]
Hi @Waner98 an explicit need for `expat-config.cmake` sounds odd, more context would definitely help to understand the problem better. If this is one of your first bug reports to a project, a good description of context, environment (e.g. platform and relevant versions), what you did, what you expected, what you got instead — those things make a great bug report and enable the other side to be of actual help, while not wasting their and your time.

Without more context, all I can give you right now is this:
```console
# cd "$(mktemp -d)"
# git clone --depth 1 https://github.com/libexpat/libexpat
# cd libexpat/expat/
# mkdir build
# cd build
# cmake ..
# make 
# find -name expat-config.cmake
./cmake/expat-config.cmake

# make DESTDIR="${PWD}/ROOT" install
# find -name expat-config.cmake
./ROOT/usr/local/lib64/cmake/expat-2.2.10/expat-config.cmake
./cmake/expat-config.cmake
```

Does that answer your question? If not, please provide more information. Thank you!

**Comment by Waner98** [comment]
Hi @hartwork,  and thank you for your quick answer. 

Now I have the file that I wanted with your method. The only problem that I have right now is with dockbook but I do not know if you already felt on this bug. 

When I process to my make / make install command, there is the following error which appear :  

```bash
#/tmp/tmp.EDaHFsC8xd/libexpat/expat/build$ make DESTDIR="${PWD}/ROOT" install
Scanning dependencies of target xmlwf-manpage
I/O error : Attempt to load network entity http://docbook2x.sf.net/latest/xslt/man/docbook.xsl
warning: failed to load external entity "http://docbook2x.sf.net/latest/xslt/man/docbook.xsl"
cannot parse http://docbook2x.sf.net/latest/xslt/man/docbook.xsl

no element found at line 1, column 0, byte 0 at /usr/lib/x86_64-linux-gnu/perl5/5.26/XML/Parser.pm line 187.
CMakeFiles/xmlwf-manpage.dir/build.make:57: recipe for target 'CMakeFiles/xmlwf-manpage' failed
make[2]: *** [CMakeFiles/xmlwf-manpage] Error 255
CMakeFiles/Makefile2:279: recipe for target 'CMakeFiles/xmlwf-manpage.dir/all' failed
make[1]: *** [CMakeFiles/xmlwf-manpage.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Waner98** [comment]
For the context, I try to compile a stack which use dependencies, including Expat, and the script which compile the lib is using this "expat-config.cmake"

**Comment by hartwork** [comment]
I think your docbook to manpage converter is misconfigured or you're missing some packages in your distribution, i.e. you could check for packages providing file `docbook.xsl`. You could also disable man page compilation with option `EXPAT_BUILD_DOCS` or you could use one of the other converters that are theoretically supported, see this list at https://github.com/libexpat/libexpat/blob/0f6d2dbd73568eafc79f182a983209ca65d4590d/expat/CMakeLists.txt#L61

**Comment by Waner98** [comment]
Ok I get it, thank you for your time @hartwork  :)
