### ISSUE TITLE
static compilation for use with emscripten

### ISSUE THREAD

**Issue by chisqr** [libexpat/libexpat#431]
I am compiling expat static library and trying to link it with emscripten, but I am running into issues. Here is how I have compiled the library:

CC=clang CXX=clang++ LD=clang++ cmake .. -DEXPAT_SHARED_LIBS=OFF

I am working in Ubuntu and the make command produces the libexpat.a file.
When I use the library with emcc I get the following error:

wasm-ld: error: unknown file type: xmlparse.c.o

How do I fix this error ? Thanks!

**Comment by hartwork** [comment]
I am sorry, but this is not the right place for Emscripten support. In case you can pin it down to a bug in the way that Expat is built later, please open a new issue with all details needed. Thanks for your understanding.
