### ISSUE TITLE
Create XML with Expat

### ISSUE THREAD

**Issue by thahgr** [libexpat/libexpat#433]
Can Expat be used to create an XML? I havent found any relative examples..
Can it be done for C++? If yes, please provide a simple example like how to create this and write it to a char[4096] for example

`<manager>
<name>John</name>
  <list_employees>
    <employee>Nick</employee>
    <employee>Anna</employee>
  </list_employees>
</manager>
`

Kind Regards

**Comment by hartwork** [comment]
Expat is a _parser_, only reading, no writing, sorry.
