### ISSUE TITLE
Website: Remake https://libexpat.github.io/ website once more

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#45]
The current https://libexpat.github.io/ website is rendered from Markdown using Pelican. The current (default) theme doesn't work well on mobile devices and Pelican may not be the best generator, either. Hence, if you want to help remake the site once more, we need to
* find a better [static site generator](https://www.staticgen.com/) and/or
* find a better Pelican theme and
* get a demo ready for review.

For a generator, the requirements are:
* Written in Python or C
* First class support for Markdown or AsciiDoc for pages/articles
* Not mess with scrolling speed (MkDocs does; can be disabled?)
* Software libre with Linux support of course

Generator *non*-candidates to me so far:
* Acrylamid
* Hyde
* (Pelican)

If this sounds like fun to you, please get in touch.

Best, Sebastian

**Comment by yukiisbored** [comment]
Pelican has a lot of themes that looks really well on mobile what are the criteria for themes? Because Most of them are targeted for blogs.

**Comment by hartwork** [comment]
It's not something easy to qualify. They need to fit a project website enough, be not annoying to look at, style would be a sure plus :) Do you have a candidate in mind?

**Comment by freddrake** [comment]
On Mon, Jun 19, 2017 at 2:31 PM, Sebastian Pipping
<notifications@github.com> wrote:
> It's not something easy to qualify. They need to fit a project website enough,
> be not annoying to look at, style would be a sure plus :) Do you have a
> candidate in mind?

You noted markdown and asciidoc as requirements; is reStructuredText
out?  There's Sphinx, which is powerful, and allows reStructuredText,
which is somewhat more expressive than markdown (though it's not an
unqualified improvement).


  -Fred

-- 
Fred L. Drake, Jr.    <fred at fdrake.net>
"A storm broke loose in my mind."  --Albert Einstein

**Comment by hartwork** [comment]
In my personal opinion reStructuredText is out, yes. It has a few properties that makes me avoid it where I can.

**Comment by hartwork** [comment]
Switched the theme now, way better support on mobile. For the curious, please click https://libexpat.github.io/ 😄
