### ISSUE TITLE
[pkg-config, CMake] The exec_prefix is unconditionally added to libdir

### ISSUE THREAD

**Issue by rffontenelle** [libexpat/libexpat#458]
## Description

When `-DCMAKE_INSTALL_LIBDIR` CMake flag is set with a absolute path, the resulting pkg-config `expat.pc` will result in libdir receiving ${exec_prefix} + the given absolute path.

This issue prevents software that depends on expat to find expat's library. See [FS#70244](https://bugs.archlinux.org/task/70244 ) on Arch Linux bug tracker.

## Steps to reproduce

1. Build expat with -DCMAKE_INSTALL_LIBDIR set. E.g.:
   ```
   cmake -DCMAKE_INSTALL_PREFIX=/usr \
         -DCMAKE_INSTALL_LIBDIR=/usr/lib \
   ```
2. Install the newly-built expat
3. See "libdir" entry in `/usr/lib/pkgconfig/expat.pc`:
   ```
   $ cat /usr/lib/pkgconfig/expat.pc | grep '^libdir='
   libdir=${exec_prefix}//usr/lib
   ```
## Environment

Arch Linux, 64-bit, expat 2.3.0, cmake 3.20.0

**Comment by hartwork** [comment]
PS: With my Linux packaging downstream hat on, I should note that unless your context is packaging for a distribution, `/usr` is reserved to the distro's package manager and hence you may want `/usr/local` instead. Ignore me, if you're aware.

**Comment by hartwork** [comment]
PPS: I missed a key sentence above and now checked https://github.com/archlinux/svntogit-community/blob/84885f25353c55193e55b325a47078dcaf2e848c/trunk/PKGBUILD#L34 . It's a bug in packaging as far as I'm concerned, but I'm happy to discuss upstream fixes if you have ideas and consider something broken here.

**Comment by rffontenelle** [comment]
> Hi @rffontenelle,
> 
> I'm happy to learn something new here but to my understanding that is known (see
> 
> https://github.com/libexpat/libexpat/blob/a44c3dee4046d8fb411bedfc58c466cde9d72953/.github/workflows/autotools-cmake.yml#L50
> ) and how `CMAKE_INSTALL_LIBDIR` from [`GNUInstallDirs`](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) works. Does `-DCMAKE_INSTALL_LIBDIR=lib` not work for you?
> 
> Best, Sebastian

Yes, using a relative path like "lib" works. I filed this issue because it is my understanding that an absolute path should be recognized accordingly. At least, this possibility is what I interpreted when reading [GNUInstallDirs in CMake docs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) that does not specify CMAKE_INSTALL_LIBDIR as relative path only.

I also tested setting CMAKE_INSTALL_FULL_LIBDIR with full path following the same page above, but it without success.

> PS: With my Linux packaging downstream hat on, I should note that unless your context is packaging for a distribution, `/usr` is reserved to the distro's package manager and hence you may want `/usr/local` instead. Ignore me, if you're aware.

I'm aware of it, thanks. What I omitted is that I was debugging Arch Linux package when I found this issue.

> PPS: I missed a key sentence above and now checked https://github.com/archlinux/svntogit-community/blob/84885f25353c55193e55b325a47078dcaf2e848c/trunk/PKGBUILD#L34 . It's a bug in Arch's packaging as far as I'm concerned, but I'm happy to discuss upstream fixes if you have ideas and consider something broken here.

I would agree with you if CMAKE_INSTALL_LIBDIR **must not** be set with an absolute library path, which I am not sure is a thing (kind of go back to my first reply above). Do you know?

**Comment by hartwork** [comment]
I did some experiments with `CMAKE_INSTALL_LIBDIR` now to re-check my memory about it. It turns out that libexpat is indeed at fault here, see this code:
https://github.com/libexpat/libexpat/blob/a44c3dee4046d8fb411bedfc58c466cde9d72953/expat/CMakeLists.txt#L385-L387

The way I read…

> The absolute path generated from the corresponding CMAKE_INSTALL_<dir> value. If the value is not already an absolute path, an absolute path is constructed [..]
> (from https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#special-cases)

…the non-full paths can either be relative or absolute.

We could check `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR` for leading slashes and only prepend things if missing. Should I make a pull request for you to review?

**Comment by rffontenelle** [comment]
> We could check CMAKE_INSTALL_LIBDIR and CMAKE_INSTALL_INCLUDEDIR for leading slashes and only prepend things if missing. Should I make a pull request for you to review?

Sure, go ahead.

**Comment by rffontenelle** [comment]
Thanks a lot for the fast reply and fix for this issue!
