### ISSUE TITLE
Find artificial limits on entity expansion (nesting depth, size, ..)

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#46]
First: **If you are using Expat with "crazy nested entities" XML files please get in touch, so we don't break your scenario by mistake later. Thank you!**

When we introduce protection against billion laugh attack (issue #34), that protection needs to be enabled by default to really protect users. Since we want to keep benign XML with nested/large entities working at the same time, we need to find the place to draw the line between benign and malicious.

Could help: 
* Check what limits do other XML parsers impose by default if any, e.g. have a closer look at `XML_ERR_ENTITY_LOOP` in libxml2
* Play with [existing defusedexpat code](https://github.com/libexpat/libexpat/commits/defusedexpat-2.1.0)
* Search the internet for benign crazy entity XML files
* ...

If any of that sounds like fun to you, please get in touch.

Best, Sebastian

**Comment by kwaclaw** [comment]
A long time ago we thought about a redesign  where one could replace the
allocation functions (which one can already do) in a way that they can
track memory usage based on parser instance. That way one can simply
trigger an out of memory error when a set limit is exceeded. The problem
was that the parser instance is currently not accessible from the
allocation functions, if I remember correctly.

On Fri, Jun 16, 2017 at 4:29 PM, Sebastian Pipping <notifications@github.com

**Comment by RMJ10** [comment]
`libxml2` has several different heuristics for deciding if something is an attack or not.  One of the more complicated ones appears to be:

  * Nesting depths of files: if the parser is nested 40 files or more deep (1024 files or more if the `XML_PARSE_HUGE` flag is set), an error is raised.
  * Nesting depths of entities: if the parser is nested 40 entities or more deep (1024 or more if `XML_PARSE_HUGE`), an error is raised.
  * Ratio of replacement text to data parsed to get it: if the replacement text for an entity is more than ten million characters long _and_ more than ten times the length of the text parsed to get it (the entity name, I think), an error is raised.
  * Ratio of number of entities to data parsed to get it: if three times the number of entities in the replacement text is more than ten times the length of the text parsed to get them, an error is raised.

Exactly which tests are made under which circumstances is not terribly clear.

**Comment by kwaclaw** [comment]
I would probably choose a simpler approach: track memory allocations by the
parser and stop at a configurable limit.

**Comment by hartwork** [comment]
Closing as fixed by #466
