### ISSUE TITLE
expat-win32bin-2.3.0.exe showing virus warnings

### ISSUE THREAD

**Issue by RPORTNOFF** [libexpat/libexpat#461]
expat-win32bin-2.3.0.exe is showing virus warnings in VirusTotal.

I previously reported this for the 2.2.9 exe.

Any chance you can post the WIN32 binaries as a ZIP file instead of an EXE?

**Comment by hartwork** [comment]
CC #376

Do you still have the link for the VirusTotal results?

I sort of kept the installer alive so far for historic reasons. I wish I had a way of asking the user base if there is some need left for the installer. Probably not. In was thinking about dropping it myself already :thinking:

**Comment by hartwork** [comment]
> Any chance you can post the WIN32 binaries as a ZIP file instead of an EXE?

PS: Do you mean in general in the future or also for 2.3.0 — the past — in particular?

**Comment by RPORTNOFF** [comment]
>Do you still have the link for the VirusTotal results?

https://www.virustotal.com/gui/file/6493ffe620c6661f970f706155418c656bd147a33a5a620903b34796e914e4da/detection

>I sort of kept the installer alive so far for 
>historic reasons. I wish I had a way of asking 
>the user base if there is some need left for the 
>installer. Probably not. In was thinking about dropping it myself already ð¤

Ideally, simpler instructions on how to build 
from sources would be great - If not, perhaps if 
you include the WIN32 binaries in ZIP format it 
may not throw the virus warnings.

>PS: Do you mean in general in the future or also 
>for 2.3.0  tthe past  in particular?

In general, if the binaries were available in a 
ZIP format it might avoid the virus warnings 
(unless the warnings are coming from the binary files themselves).

**Comment by RPORTNOFF** [comment]
...regarding last point, for 2.3.0 would be appreciated.


>Do you still have the link for the VirusTotal results?

https://www.virustotal.com/gui/file/6493ffe620c6661f970f706155418c656bd147a33a5a620903b34796e914e4da/detection

>I sort of kept the installer alive so far for 
>historic reasons. I wish I had a way of asking 
>the user base if there is some need left for the 
>installer. Probably not. In was thinking about dropping it myself already ð¤

Ideally, simpler instructions on how to build 
from sources would be great - If not, perhaps if 
you include the WIN32 binaries in ZIP format it 
may not throw the virus warnings.

>PS: Do you mean in general in the future or also 
>for 2.3.0  tthe past  in particular?

In general, if the binaries were available in a 
ZIP format it might avoid the virus warnings 
(unless the warnings are coming from the binary files themselves).

**Comment by hartwork** [comment]
> ...regarding last point, for 2.3.0 would be appreciated.

Okay, done.

I have attached a new file [expat-win32bin-2.3.0.zip](https://github.com/libexpat/libexpat/releases/download/R_2_3_0/expat-win32bin-2.3.0.zip) to [release 2.3.0 on GitHub](https://github.com/libexpat/libexpat/releases/tag/R_2_3_0) for download just now.
For its creation, this is what I did on my Linux box:
```console
# cd "$(mktemp -d)"
# wget https://github.com/libexpat/libexpat/releases/download/R_2_3_0/expat-win32bin-2.3.0.exe
# sha256sum expat-win32bin-2.3.0.exe
6493ffe620c6661f970f706155418c656bd147a33a5a620903b34796e914e4da  expat-win32bin-2.3.0.exe
# innoextract -e expat-win32bin-2.3.0.exe
# ( cd app && zip -9 -r ../expat-win32bin-2.3.0.zip . )
# sha256sum expat-win32bin-2.3.0.zip
37f6f65c905c5ebe3dc7a607300610c8499962ff972bbc0f1f0d952317ec2877  expat-win32bin-2.3.0.zip
```

> https://www.virustotal.com/gui/file/6493ffe620c6661f970f706155418c656bd147a33a5a620903b34796e914e4da/detection

Thanks for the link!

> Ideally, simpler instructions on how to build from sources would be great

Is this about native compilation on a Windows terminal with Visual Studio, msbuild and CMake available? Please help me understand your scenario better. Thanks!

> - If not, perhaps if you include the WIN32 binaries in ZIP format it may not throw the virus warnings.

That's a good point.

Unless the AI changes its mind again in the future (like we had with #376 earlier), VirusTotal likes the zip file better, it seems:
https://www.virustotal.com/gui/url/9522b33d04d7393737af56f05e92e1b3a078b5961b134bcf1337a8a2ec276ba9/detection

**Comment by hartwork** [comment]
PS: I have [added the new zip to SourceForge as well now](https://sourceforge.net/projects/expat/files/expat_win32/2.3.0/) and made it the default download for Windows. I have some hope that as a result the installer downloads will go down to zero OR reveal that people keep doing explicit manual downloads of the installer. Let's see.

**Comment by RPORTNOFF** [comment]
>PS: I have 
><https://sourceforge.net/projects/expat/files/expat_win32/2.3.0/>added 
>the new zip to SourceForge as well now and made it the default 
>download for Windows. I have some hope that as a result the 
>installer downloads will go down to zero OR reveal that people keep 
>doing explicit manual downloads of the installer. Let's see.

>I have attached a new file 
><https://github.com/libexpat/libexpat/releases/download/R_2_3_0/expat-win32bin-2.3.0.zip>expat-win32bin-2.3.0.zip 
>to 
><https://github.com/libexpat/libexpat/releases/tag/R_2_3_0>release 
>2.3.0 on GitHub for download just now.
>For its creation, this is what I did on my Linux box:

That works - No more warnings... and easy to use... Thanks! :-)

>Ideally, simpler instructions on how to build from sources would be great
>
>Is this about native compilation on a Windows terminal with Visual 
>Studio, msbuild and CMake available? Please help me understand your 
>scenario better. Thanks!

I use Windows with Visual Studio and nmake or gnumake

**Comment by RPORTNOFF** [comment]
>PS: I have 
><https://sourceforge.net/projects/expat/files/expat_win32/2.3.0/>added 
>the new zip to SourceForge as well now and made it the default 
>download for Windows. I have some hope that as a result the 
>installer downloads will go down to zero OR reveal that people keep 
>doing explicit manual downloads of the installer. Let's see.

Not a fair test since people will usually select the option with the 
most downloads and the EXE is way ahead of the ZIP - For a true test, 
you need to start both the EXE and ZIP with 0 downloads each.

**Comment by hartwork** [comment]
The zip is the default download on SourceForge now so only people how crawl into the file tree to manually pick the exe will get it: Numbers will not have an impact before you crawled down to that folder. So if the exe does not go down to zero that would say something as the system is largely in favor of the zip now.

> I use Windows with Visual Studio and nmake or gnumake

I guess you would need CMake generator "NMake Makefiles" or "MinGW Makefiles" then.
Is this about building Expat in isolation or as one piece of a tree of CMake projects?
Have you figured how to build Expat by now or is it about being able to build (and not "just" about extending documentation)?

**Comment by RPORTNOFF** [comment]
>I guess you would need CMake generator "NMake Makefiles" or "MinGW 
>Makefiles" then.
>Is this about building Expat in isolation or as one piece of a tree 
>of CMake projects?
>Have you figured how to build Expat by now or is it about being able 
>to build (and not "just" about extending documentation)?

I am fine working with the (clean!) ZIP file. I was just letting you 
know that (IMO) the build process could be simplified/automated a bit 
more for those that want to build from source.

**Comment by hartwork** [comment]
> I am fine working with the (clean!) ZIP file. I was just letting you know that (IMO) the build process could be simplified/automated a bit more for those that want to build from source.

I was hoping to learn more about what would be needed there because I don't really know. Personally, I try to trust as few binaries as possible so if I can help more people to move from binaries to sources that would be good in my view.

**Comment by RPORTNOFF** [comment]
Sure, I am happy to work with you if that would 
help the project. Perhaps we should take this 
off-line to private email? Feel free to contact 
me directly and we can work through this.

At 4/14/2021 09:19 AM, you wrote:

**Comment by hartwork** [comment]
> Sure, I am happy to work with you if that would help the project. Perhaps we should take this off-line to private email? Feel free to contact me directly and we can work through this.

Sounds good but I don't have your e-mail address and it doesn't seem public on GitHub. Can you drop me a oneliner to my e-mail? It's on my profile page. Thanks!

**Comment by RPORTNOFF** [comment]
I sent you private email - Let me know (here) if you don't receive it.

At 4/14/2021 09:34 AM, you wrote:

**Comment by hartwork** [comment]
Got your mail and will reply soon, thanks! I'll close the ticket here for now: We can make a new ticket when it's clear that the installer is going to go away about installer removal, easily. If you'd rather have the ticket re-open, just let me know.
