### ISSUE TITLE
How to parse an XML document from the command line?

### ISSUE THREAD

**Issue by dominic01** [libexpat/libexpat#462]
This is not an issue or a bug. Certain other GIT projects have a board called "Discussion" and I dont see it in this project. Hence I am posting it here.

Is it possible to parse a XML document from command line? One of our legacy system uses NSGMLs parser and wondering how to replace with latest one. I tried libxml and see some difference in errors reporting. 

Appreciate any pointers.

**Comment by hartwork** [comment]
Hi @dominic01,

> Is it possible to parse a XML document from command line?

It sounds like you may be looking for command `xmlwf` that comes with libexpat. Or `xmllint` of libxml2.

> One of our legacy system uses NSGMLs parser and wondering how to replace with latest one. I tried libxml and see some difference in errors reporting.
> 
> Appreciate any pointers.

NSGML seems to be for SGML, libexpat is for XML 1.0 fourth edition only. SGML is not my topic and I'd need a more concrete question to be of help.

Best, Sebastian

**Comment by hartwork** [comment]
Closing for no reply for 7 days
