### ISSUE TITLE
reference.html is slightly malformed

### ISSUE THREAD

**Issue by TomasKorbar** [libexpat/libexpat#464]
Hi libexpat developers,
i am maintainer of the expat package in Fedora and RHEL.
Once in a while, the package gets scanned with static code analysis
tool and there is this warning that always occurs.
```
1) File /usr/share/doc/expat-devel/reference.html is a malformed XML file on x86_64
Details:
Element ul is not declared in p list of possible children
```
Could you please merge my PR to stop this from happening?

**Comment by hartwork** [comment]
Hi Tomas, nice to meet you, thanks for taking this upstream and for the pull request! :pray:

**Comment by hartwork** [comment]
PS: Do you have a pointer how you're calling that tool and which one it is? I was thinking about adding the same thing to GitHub Actions CI to avoid similar issues in the future.

**Comment by TomasKorbar** [comment]
Well this tool is designed for rpm packages specifically. https://github.com/rpminspect/rpminspect
To use it in your CI you would have to most likely use https://packit.dev/docs/packit-as-a-service/ so you would have available built rpm packages and create test which uses rpminspect. To be honest i do not think that i have ever seen someone using rpminspect in upstream CI. If you would like to implement some Fedora related CI then we would have to most likely synchronize a little because that would mean that you will need spec file.

**Comment by hartwork** [comment]
I was hoping the XML part was isolated for reuse or easy to mimic. rpminspect is not calling out to some other command for the XML job?

**Comment by TomasKorbar** [comment]
rpminspect is a C program and it is using libxml for its xml checks so if you want to isolate xml check then you will have to unfortunately use some other tool.

**Comment by hartwork** [comment]
Okay. If you run into ideas for a specific easy substitute later that would have caught the same error, I'm happy to get back to that.
