### ISSUE TITLE
[2.3.0] .so references in cmake/autotools/expat-noconfig.cmake.in incorrect for MinGW builds

### ISSUE THREAD

**Issue by brechtsanders** [libexpat/libexpat#485]
When building expat 2.3.0 with MinGW-w64 on Windows the file generated based on `cmake/autotools/expat-noconfig.cmake.in` contains references to files that are not generated on Windows.

In particular files like `libexpat.so.@SO_MAJOR@.@SO_MINOR@.@SO_PATCH@` and `libexpat.so.@SO_MAJOR@` will look more like `libexpat.dll.a` (or `libexpat.a` for static builds) and `libexpat.dll` on Windows.

This will cause detection of expat to fail on this platform (one example of a package that can't find it because it's looking for the .so files is OpenColorIO-2.0.0).

I can imagine the same issue might also exist for Apple macOS where the shared library extension is `.dylib`.

**Comment by 1480c1** [comment]
Perhaps that file is only supposed to be used for people still using autotools and want to try to detect libexpact through cmake packages? It probably is preferred to use the CMakeLists.txt in all cases though as the autotools is still there because of cmake bootstrapping

**Comment by hartwork** [comment]
@brechtsanders I understand, that makes perfect sense and… is unfortunate.

So for a fix it takes getting access to files generated by CMake on platform X, compare and study them, and then come up with support for more platforms. The only good thing right now: These files do not break any existing support, they "just" fail to make "something new" on those platforms.

**Comment by hartwork** [comment]
PS: For the record to anyone else who find this ticket: To CMake, package "EXPAT" and package "expat" are two different things. This ticket is about the lowercase version, detection of the uppercase package is unaffected, the readme has a few more words on those two.

**Comment by hartwork** [comment]
PS: Here's what the diff looks like in practice for MinGW:
```diff
diff -u0 -r ../cmake/autotools/expat-config-version.cmake DESTDIR/usr/local/lib/cmake/expat-2.3.0/expat-config-version.cmake
--- ../cmake/autotools/expat-config-version.cmake       2021-05-04 17:45:29.115790595 +0200
+++ DESTDIR/usr/local/lib/cmake/expat-2.3.0/expat-config-version.cmake  2021-05-19 23:25:16.000000000 +0200
@@ -58 +58 @@
-if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
+if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "4" STREQUAL "")
@@ -63,2 +63,2 @@
-if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
-  math(EXPR installedBits "8 * 8")
+if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "4")
+  math(EXPR installedBits "4 * 8")
diff -u0 -r ../cmake/autotools/expat-noconfig.cmake DESTDIR/usr/local/lib/cmake/expat-2.3.0/expat-noconfig.cmake
--- ../cmake/autotools/expat-noconfig.cmake     2021-05-04 17:45:29.142790798 +0200
+++ DESTDIR/usr/local/lib/cmake/expat-2.3.0/expat-noconfig.cmake        2021-05-19 23:25:16.000000000 +0200
@@ -11,2 +11,2 @@
-  IMPORTED_LOCATION_NOCONFIG "${_IMPORT_PREFIX}/lib/libexpat.so.1.7.0"
-  IMPORTED_SONAME_NOCONFIG "libexpat.so.1"
+  IMPORTED_IMPLIB_NOCONFIG "${_IMPORT_PREFIX}/lib/libexpat.dll.a"
+  IMPORTED_LOCATION_NOCONFIG "${_IMPORT_PREFIX}/bin/libexpat.dll"
@@ -16 +16 @@
-list(APPEND _IMPORT_CHECK_FILES_FOR_expat::expat "${_IMPORT_PREFIX}/lib/libexpat.so.1.7.0" )
+list(APPEND _IMPORT_CHECK_FILES_FOR_expat::expat "${_IMPORT_PREFIX}/lib/libexpat.dll.a" "${_IMPORT_PREFIX}/bin/libexpat.dll" )
```

**Comment by brechtsanders** [comment]
I can confirm that building expat 2.3.0 with `cmake/autotools/expat-config-version.cmake.in` and `cmake/autotools/expat-noconfig.cmake.in` patched as mentioned above does allow building OpenColorIO 2.0.0 with MinGW-w64.

**Comment by hartwork** [comment]
> I can confirm that building expat 2.3.0 with `cmake/autotools/expat-config-version.cmake.in` and `cmake/autotools/expat-noconfig.cmake.in` patched as mentioned above does allow building OpenColorIO 2.0.0 with MinGW-w64.

@brechtsanders thanks!

Interestingly, GNU Autotools produces file `libexpat-1.dll` (with `-1`) while CMake produces `libexpat.dll` (without `-1`).
Pull request #486 uses `libexpat-1.dll` to truly match GNU Autotools artifacts. If you could give that pull request a spin, that would be plain awesome. :pray:

**Comment by brechtsanders** [comment]
I gave pull request #486 a spin with MinGW-w64 (both 64-bit and 32-bit separately). It builds fine. Then I build some projects depending on expat (including OpenColorIO) and I had no issues at all.

**Comment by hartwork** [comment]
@brechtsanders thank you!
