### ISSUE TITLE
compiler cannot find -libexpat

### ISSUE THREAD

**Issue by Russ-Nasrallah** [libexpat/libexpat#487]
Hello all, 
First off, I'm quite the novice and am coming here as a last result for some guidance. I do not have lots of experience with compiling code or unix. Alright, with that out of the way, here is my issue. 

I have been tasked with installing the following software on the following HPC 
https://oss.deltares.nl/web/delft3d/source-code
https://www.erdc.hpc.mil/index.html

One of the tools that is required to install the software (Delft3D) is expat. I used SVN to download the git repository and followed the instructions listed to compile the code. I've attached a text file with all results from the compile. 
[expat_compile.txt](https://github.com/libexpat/libexpat/files/6523674/expat_compile.txt)

I believe the error may be when I run the ./configure portion of the code I see the following warning:

_libtool: warning: '../lib/libexpat.la' has not been installed in '/p/home/russnas/apps/lib'_

Is there something I am possibly doing wrong? 

Later, when I go to install the software the depends on expat for XML parsing, I get the following message:

`Checking for XML_parse in -lexpat
Configure: Error: compiler cannot find libexpat`

I am wondering is this is possibly an error I am making during the compilation or some guidance any of y'all can offer that might help my compiler find expat. 

Apologies if this is outside of the scope of what I should post in Issues. 

One other note, when I see similar issues on the forum for the Delft3D software, they mention that it is due to having the wrong distribution of expat and recommend using the libexpat1-dev. I am not sure what this means, or if this could be my problem. 

If you need any other info I will be happy to provide.

**Comment by Russ-Nasrallah** [comment]
Thank you for the quick and detailed reply @hartwork ! 

I am going to read through this link you sent and see if I can try this method. 

Perhaps it has something to do with the way I modified my bashrc or profile files on our HPC Cluster (See below). 

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/p/home/russnas/apps/expat/lib
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/p/home/russnas/apps/expat/lib/pkgconfig
export PATH=$PATH:/p/home/russnas/apps/expat/bin`

I will send you an email if this doesn't solve the problem and we will chat. Thank you for the offer.

**Comment by hartwork** [comment]
> ```
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/p/home/russnas/apps/expat/lib
> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/p/home/russnas/apps/expat/lib/pkgconfig
> export PATH=$PATH:/p/home/russnas/apps/expat/bin
> ```

Please note that these lines:
- are missing quoting (thinking of current values containing spaces) and
- may end up putting empty leading string segments — as in `fourth:entry:empty:` — into those color-separated flat lists which will be evaluated as "current working directory" with is a security risk, e.g. see https://www.reddit.com/r/linux/comments/77egd9/nasty_empty_directory_trick_with_ld_library_path/ . At least the first two variables are likely unset at Bash sourcing time.

To take the first line as an example, to be secure you could do either of:
- `export LD_LIBRARY_PATH=/p/home/russnas/apps/expat/lib`
- `export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}${LD_LIBRARY_PATH:+:}/p/home/russnas/apps/expat/lib"`

If syntax `${LD_LIBRARY_PATH:+:}` is unfamiliar, `man bash` has a few words about it.

> I will send you an email if this doesn't solve the problem and we will chat. Thank you for the offer.

Good, I will then close this ticket.
