### ISSUE TITLE
expat-win32bin-2.4.1.zip shows a virus warning

### ISSUE THREAD

**Issue by RPORTNOFF** [libexpat/libexpat#493]
expat-win32bin-2.4.1.zip shows 1 virus warning in VirusTotal.

Note: yesterday's expat-win32bin-2.4.0.zip was clean.

**Comment by hartwork** [comment]
Hi! It does? This looks clean: https://www.virustotal.com/gui/url/e6af775d8bdcebdb01a152d87279762a83d6a571d82541ae8a617fcaa8bd745f/detection
SHA256 sum is `6586dbe52f5a721abe1f8a4369727187bcea34dc4e2049357a413a06824bb79f`.
Can you share your link?

**Comment by RPORTNOFF** [comment]
Here ya go...

https://www.virustotal.com/gui/file/6586dbe52f5a721abe1f8a4369727187bcea34dc4e2049357a413a06824bb79f/detection


At 5/23/2021 04:47 PM, you wrote:

**Comment by hartwork** [comment]
So the checksum is identical but the set of engines run is not the same ("0 / 88" versus "1 / 62"), and the engine detecting `Program:Win32/Wacapew.C!ml` — Windows Defender apparently — is only in one of those two sets. I don't know what to make of that :man_shrugging: :smile:

Any ideas how to proceed from here?

**Comment by RPORTNOFF** [comment]
So, I uploaded each of the binary files (from the 
BIN\ folder) separately to see which one was 
causing the problem, but they all passed so it's 
probably just a false positive caused by a matching hash signature.

You could try adding an unused variable or unused 
function to the build which will change the hash 
signature and may prevent this false positive... or may cause others :-/

I'm fine ignoring the warning since all the binaries show as clean.


At 5/23/2021 05:18 PM, you wrote:

**Comment by hartwork** [comment]
Thank you! I'll close the ticket as "nothing more to do" for now then.
