### ISSUE TITLE
Current use of float for maximumAmplificationFactor 

### ISSUE THREAD

**Issue by amadvance** [libexpat/libexpat#494]
Hi,

I see that the latest release introduced the use of float for handling the maximumAmplificationFactor protection. 

Is using float really necessary ? This is a strong dependency in some environments.

Considering that the default maximum factor is 100, using a simple "int" instead of a "float" seems a simple way to remove this dependency losing only a bit of precision in the computation.

Thanks!

**Comment by hartwork** [comment]
Hi @amadvance ,

could you elaborate what you mean by `float` being a strong dependency in some environments, given a C99 compiler?

The idea of using `float` originates from:

1. amplification being a ratio by nature
2. lack of need for double precision
3. lack of an incentive to degrade to integers
4. being able to report and test with values like 1.03

**Comment by amadvance** [comment]
Some old processors don't have a floating point unit, and the compiler needs to link a software emulation library for that.

**Comment by hartwork** [comment]
`float` is already in the API so there is no way to get it out of the interface.
With regard to internals, I don't really see Expat not using float just for the these processors and it should be easy to patch out on your end, if your case wants to avoid float in 2021. Expat is not a museum, let me be clear about that. We could do minor (non-semantic) refactorings to reduce the size of your patch if it makes a difference, but I don't see much else I can do about it. What do you think?

**Comment by amadvance** [comment]
No problem, I'll patch the code :)
