### ISSUE TITLE
Compile error: Invalid conversion from `void*` to `XML_Char*`

### ISSUE THREAD

**Issue by scouten** [libexpat/libexpat#497]
When building [libexpat 2.4.1 for linux](https://github.com/adobe/xmp-toolkit-rs/pull/19/checks?check_run_id=2738840033), I get the following error:

```
    cargo:warning=external/xmp_toolkit/third-party/expat/lib/xmlparse.c: In function ‘XML_Char* copyString(const XML_Char*, const XML_Memory_Handling_Suite*)’:
398
    cargo:warning=external/xmp_toolkit/third-party/expat/lib/xmlparse.c:7222:32: error: invalid conversion from ‘void*’ to ‘XML_Char*’ {aka ‘char*’} [-fpermissive]
399
    cargo:warning= 7222 |   result = memsuite->malloc_fcn(charsRequired * sizeof(XML_Char));
400
    cargo:warning=      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
401
    cargo:warning=      |                                |
402
    cargo:warning=      |                                void*
403
```

I can (and will) work around this by using `-fpermissive`, but I'd prefer not to. Can you add an explicit cast here to satisfy the compiler?

**Comment by scouten** [comment]
Actually, this is a blocker as I don't seem to have a compile flag I can use on MacOS to silence this error. This prevents me from responding to adobe/xmp-toolkit-rs#18.

See [this build log](https://github.com/adobe/xmp-toolkit-rs/pull/19/checks?check_run_id=2739417720).

**Comment by hartwork** [comment]
Seems like an easy fix: I can do a pull request or you can make one and have a commit in here, as you prefer.
The current macOS CI is running AppleClang 12. If this is a different compiler, than that would explain why it didn't show up earlier. From a quick look I couldn't see any compiler identification in the log — are we dealing with Apple GCC here? Is the version known?

**Comment by hartwork** [comment]
PS: Could it be that you're compiling C code with a C++ compiler? There are people who argue that adding the cast is not a good idea (e.g. at https://stackoverflow.com/questions/605845/do-i-cast-the-result-of-malloc) so I'd want to be sure that we don't put the band-aid in the wrong place. I'm looking forward to analyze and discuss this further with you.

**Comment by scouten** [comment]
I am away for a couple of days starting now, but will attempt to circle back on this early next week.

**Comment by hartwork** [comment]
Thanks for the heads-up, see you soon :pray:

**Comment by scouten** [comment]
@hartwork yes, it is compiling C code with a C++ compiler.

I don't believe I have a choice in this context. Please look at https://github.com/adobe/xmp-toolkit-rs/blob/main/build.rs#L249 and let me know if there's a way to specify C++ compilation on a per-file basis. I've looked and not found it.

Absent that, I don't think I can take the upgrade unless the expat source is modified.

**Comment by hartwork** [comment]
@scouten I see use of cc-rs with a broad `.cpp(true)` at https://github.com/adobe/xmp-toolkit-rs/blob/c5aa9b461a8a06552c9ba54c347b4f53a0f1446e/build.rs#L131 that affects both C and C++ files. If the file list beneath is split into C files with `.cpp(false)` and C++ files with `.cpp(true)` I am optimistic that the problem may go away cheap. Is anything standing in your way doing that split?

**Comment by scouten** [comment]
@hartwork that is not true. The build engine in the cc crate is much simpler than that. If you look at the implementation of the `Build` struct (https://github.com/alexcrichton/cc-rs/blob/19320dddcd7b801558dfc9d6225b31019b9bd8ec/src/lib.rs#L92-L126), `cpp` is a single bool value and there is a vector list of `PathBuf` for the files to be compiled. There doesn't appear to be any provision for customizing the build process on a per-file basis.

I would welcome a PR that implements the update and passes all of the existing validation runs (and, of course, feel free to us my existing PR in xmp-toolkit-rs as a starting point), but I don't know that I can devote much more time to this on my own at this point.

**Comment by hartwork** [comment]
> @hartwork that did not work.
> 
> If you look at the implementation of the `Build` struct (https://github.com/alexcrichton/cc-rs/blob/19320dddcd7b801558dfc9d6225b31019b9bd8ec/src/lib.rs#L92-L126), `cpp` is a single bool value and there is a vector list of `PathBuf` for the files to be compiled. There doesn't appear to be any provision for customizing the build process on a per-file basis.

A single bool yes, but is anything keeping your from using two instances of `Build`, one with `.cpp(false)` and the other with `.cpp(true)`?

> I would welcome a PR that implements the update and passes all of the existing validation runs (and, of course, feel free to us my existing PR in xmp-toolkit-rs as a starting point), but I don't know that I can devote much more time to this on my own at this point.

I am not at home with Rust. I have a hard time believing that it would take me to get the xmp-toolkit-rs fixed. I can do a pairing video call with someone who both has push permissions and is at home with Rust more than I am. If needed, that I can do.

**Comment by hartwork** [comment]
@scouten let me re-summarize:
- xmp-toolkit-rs is compiling C code using a C++ compiler
- using a C compiler instead would fix the issue in xmp-toolkit-rs
- there is nothing to fix in Expat with regard to this error
- I do not have resources to fix xmp-toolkit-rs myself
- I hope that Adobe cares enough about security that it will allocate time to upgrade its vulnerable copies of Expat

With that said, I'll close this ticket as "not a bug in Expat".
