### ISSUE TITLE
[2.2.1] Issues with getrandom on Debian GNU/kFreeBSD

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#50]
```
[..]
checking for getrandom (Linux 3.17+, glibc 2.25+)... yes
[..]
./.libs/libexpat.so: undefined reference to `getrandom'
[..]
```
Full logs:
* i386: https://buildd.debian.org/status/fetch.php?pkg=expat&arch=kfreebsd-i386&ver=2.2.1-1&stamp=1497747068&raw=0
* amd64: https://buildd.debian.org/status/fetch.php?pkg=expat&arch=kfreebsd-amd64&ver=2.2.1-1&stamp=1497747212&raw=0

**Comment by jacmet** [comment]
This is not specific to kfreebsd, also triggers here when building against older glibc versions. You need AC_LINK_* for robust function tests.

**Comment by hartwork** [comment]
Yes, 602e6c78ca750c082b72f8cdf4a38839b312959f fixes that.

**Comment by hartwork** [comment]
I'm still wondering what to do about entropy on Debian GNU/kFreeBSD. Any ideas?
