### ISSUE TITLE
XML_GetBuffer(parser, 0) may return NULL

### ISSUE THREAD

**Issue by Batchyx** [libexpat/libexpat#502]
I discovered that on libexpat 2.4.1, calling XML_GetBuffer with size 0 can return a NULL pointer with a fresh XML_Parser:

```c
#include <expat.h>
#include <stdio.h>
int main() {
        XML_Parser parser = XML_ParserCreate(NULL);
        if (!parser)
                return 1;
        printf("XML_GetBuffer(0): %p\n", XML_GetBuffer(parser, 0));
        XML_ParserFree(parser);
        return 0;
}
```

This behavior is not documented and does not appear to be deliberate.  It returns NULL because `XML_GetBuffer()` simply returns `m_bufferEnd` and it is initialized to NULL in `parserInit()`. Callers that checks for NULL may be confused by this.

I know that opinions diverges on whether malloc(0) may/should return NULL or a non-NULL value, but here i suggest that either the documentation should state that XML_GetBuffer() may return NULL for size 0, or it should be modified to return something like `m_dataBuf` instead.

**Comment by hartwork** [comment]
Hi @Batchyx I confirm that `XML_GetBuffer` _may_ return 0. This code…

```c
#include <assert.h>
#include <stdio.h>
#include <expat.h>

int main() {
  XML_Parser parser = XML_ParserCreate(NULL);
  assert(parser);
  printf("XML_GetBuffer(0): %p\n", XML_GetBuffer(parser, 0));
  printf("XML_GetBuffer(1): %p\n", XML_GetBuffer(parser, 1));
  printf("XML_GetBuffer(0): %p\n", XML_GetBuffer(parser, 0));
  XML_ParserFree(parser);
  return 0;
}

```

…gets me:

```console
# gcc -std=c99 -Wall -Wextra -pedantic -lexpat question502.c && ./a.out
XML_GetBuffer(0): (nil)
XML_GetBuffer(1): 0x5632f079c220
XML_GetBuffer(0): 0x5632f079c220
```

While the internal code, the sample code and the docs are clear about possible return of `NULL` _in general_, I agree that there is no explicit mention of size 0. (I can neither proof nor deny whether return of `NULL` was deliberate for size 0. The alternative seems to be to pump up 0 to e.g. 1024 (`INIT_BUFFER_SIZE`) but that would mean more allocations than strictly necessary.)

My local `man 3 malloc` says:

> `NULL` may also be returned by a successful call to `malloc()` with a `size` of zero[.]

That seems to fit current `XML_GetBuffer` well. We could enrich current Expat doc sentence in file `doc/reference.html`…

> A `NULL` value is returned if Expat can't allocate enough memory for this buffer.

…with a `malloc`-like note. What do you think? Would you rather make a pull request or be in the review seat for one?

Best, Sebastian
