### ISSUE TITLE
Redefinition warning of `HAVE_STDINT_H`

### ISSUE THREAD

**Issue by Krzmbrzl** [libexpat/libexpat#521]
We have received a build error of our software (Mumble) that seems to be caused by libexpat redefining the `HAVE_STDINT_H` macro (creates a warning and that is treated as an error in our environment): https://forums.mumble.info/topic/5721-windows-build-error/?do=findComment&comment=12226

The redefinition happens here:
https://github.com/libexpat/libexpat/blob/59d5c6eacd96731eb01868d7eaf6ab5997b2c5f4/expat/expat_config.h.cmake#L37

I am not entirely sure as to where and how we arrive at a duplicate define but from looking at that header file, it seems like it is missing include guards? So maybe it gets included twice somehow :thinking: 

Note that I am not using libexpat directly but rather I am using the Poco XML library which appears to be built on top of libexpat.

**Comment by hartwork** [comment]
Hi @Krzmbrzl , I have used Mumble myself before, very nice project. We had a similar case with libexpat user CPython — issue #513 and pull request #514 — and so `master` slightly improved in the latest release, but it likely does not affect your case and I should mention that arguably it was not libexpat who was "at fault" there but CPython and we just made things a little easier for them, to be fair.

Given that libexpat's `expat_config.h` is either generated by GNU Autotools or by CMake, adding something like an "unless already defined" pre-processor guard seems easy for the CMake half, but not the GNU Autoheader one (without looking into it deeper), and they would remain in sync, ideally.

What do you think?

**Comment by Krzmbrzl** [comment]
> I have used Mumble myself before, very nice project.

Thanks! :D

Hm, yeah that seems like a problem. I am wondering whether the redefinition error is caused by a different project already havin defined that macro or because the config header of expat is included twice at some point. If it was the latter, it might be possible to solve the issue by using include-guards :thinking: 

Unfortunately, I have absolutely zero experience with autotools, so I am not really qualified to comment on that topic.

**Comment by hartwork** [comment]
@Krzmbrzl maybe the scope of https://github.com/mumble-voip/mumble/blob/7419dbf28899f64f8a6e5b59d33815776a845c06/src/mumble/CMakeLists.txt#L678-L681 is too broad.
Are you running into this when celt is enabled at build time?

Do you agree that this should be fixed outside of libexpat?

PS: Here's one way to see the `expat_config.h.in` template generated by GNU autoheader (that a later run to `./configure` will turn into eventual rendered file `expat_config.h:
```console
cd "$(mktemp -d)"
git clone --depth 1 https://github.com/libexpat/libexpat
cd libexpat/expat/
autoheader
cat expat_config.h.in 
```

**Comment by Krzmbrzl** [comment]
> maybe the scope of https://github.com/mumble-voip/mumble/blob/7419dbf28899f64f8a6e5b59d33815776a845c06/src/mumble/CMakeLists.txt#L678-L681 is too broad.

Oh yes indeed. That's probably what is causing the issues. Thanks for pointing this out! I somehow missed that when the error was reported to us. Guess I was too eager to blame an external library for this xD

> Do you agree that this should be fixed outside of libexpat?

Yes - I'll close this issue
