### ISSUE TITLE
[>=2.4.0][docs] Mistaken return value in documention of XML_SetBillionLaughsAttackProtection* functions

### ISSUE THREAD

**Issue by pointsman** [libexpat/libexpat#522]
The file reference.html documents XML_SetBillionLaughsAttackProtectionMaximumAmplification() with:

"Sets the maximum tolerated amplification factor for protection against billion laughs attacks (default: 100.0) of parser p to maximumAmplificationFactor, and returns XML_TRUE upon success and XML_TRUE upon error. "

Errr ..., wait... does this say the function always return XML_TRUE? Or is this just an editorial mistake and should read "and XML_ERROR upon error"? If yes, under what circumstances may that happen?

Same in the documentation of XML_SetBillionLaughsAttackProtectionActivationThreshold() below.

Clarification welcome.

**Comment by hartwork** [comment]
Hi @pointsman , you found a bug, thanks for the report. One of these should be `XML_FALSE` of course. The related code is about as readbable as it get, so I will answer your question with (1) code, (2) a high level summary, and (3) a note about the future, below.

### Code

https://github.com/libexpat/libexpat/blob/59d5c6eacd96731eb01868d7eaf6ab5997b2c5f4/expat/lib/xmlparse.c#L2526-L2546

### Summary

`XML_FALSE` is returned when:
- the parser is NULL
- the parser has a parent parser (and hence the parent does the actual work about billion laughs protection)
- the given target value does not meet the requirements, e.g. it's below 1.0 or NaN

### Future

For the future, the is a chance that `XML_FALSE` will also be returned whenever DTD support has been disabled at compile time. Currently, the whole function would be absent in that case, but it's one potential way to go forward with related issue #512.

**Comment by hartwork** [comment]
@pointsman the key issues is fixed by pull request #523 now. Regarding your question "under what circumstances may that happen" I have elaborated above and after re-checking personally consider the current docs (with the fix) good enough now.
