### ISSUE TITLE
GnuPG key used for creating release signatures has expired

### ISSUE THREAD

**Issue by Bonnietwin** [libexpat/libexpat#537]
I have just downloaded expat-2.4.2.tar.bz2 and its signature file to update IPFire with it.
I ran gpg --verify and got the message that the signature from Sebastian Pipping was good but with a note that the key used to create the signature had expired.

**Comment by hartwork** [comment]
Hi @Bonnietwin,

my pubkey can be inspected online at https://keys.gentoo.org/pks/lookup?op=vindex&search=0x1F9B0E909AF37285 . The key used for signing the release tarball is the last subkey on that page (`FBD3AEC6`). It looks non-expired up there. My guess is that (1) I have not uploaded a refreshed key elsewhere and (2) you have fetched my pubkey from a keyserver that is not the Gentoo one (which ideally would still work, I guess). To allow me to test things "through your eyes" over here, what is your current keyserver for GPG, how did you fetch the pubkey last time?

Best, Sebastian

**Comment by hartwork** [comment]
PS: @Bonnietwin I have updated my pubkey at these three keyservers now:

- `keys.gentoo.org` — https://keys.gentoo.org/pks/lookup?op=vindex&search=0x1F9B0E909AF37285
- `keys.openpgp.org` — https://keys.openpgp.org/search?q=sping%40gentoo.org
- `keyserver.ubuntu.com` — https://keyserver.ubuntu.com/pks/lookup?search=0x1F9B0E909AF37285&fingerprint=on&exact=on&op=index

**Comment by hartwork** [comment]
PPS: @Bonnietwin is https://git.ipfire.org/?p=ipfire-3.x.git;a=blob;f=expat/expat.nm;hb=HEAD the packaging you are about to update?

**Comment by Bonnietwin** [comment]
Hi @hartwork
I am using keys.openpgp.org as my key server, although I have changed the key server over time as previous ones, such as the keyserver.ubuntu.com one, sometimes failed to find certain keys at all.
I wasn't aware of the gentoo one. I will have to look if I can have more than one key server set in the gpg.conf file.

I tried the verify again and it still showed key expired but then I realised that I needed to re-download the key again. I did that and then the verify worked with no problems.

Sorry for the noise. I have learnt something further about keys and gpg, so shouldn't make that mistake again.

Re the packaging I am updating it is not the ipfire-3.x version as that is still under development, It is the ipfire-2.x version

https://git.ipfire.org/?p=ipfire-2.x.git;a=blob;f=lfs/expat;h=7627447f3819160725f790daac5fc5aa562d1c30;hb=refs/heads/next

**Comment by hartwork** [comment]
@Bonnietwin no worries about noise, you did point out a missing upload, and I learned a few things about GnuPG in the process myself, too (e.g. `--with-subkey-fingerprints`, `--export-options export-minimal` and re-finding `--list-packets`). PS: I added IPFire to the list of Linux distros with libexpat packaging at https://libexpat.github.io/doc/packages/ just now.
