### ISSUE TITLE
CMake: Kindly add installation of Windows debugger files (pdb)?

### ISSUE THREAD

**Issue by emmenlau** [libexpat/libexpat#542]
This is a kind feature request. Thanks for this great library! I've seen that when built on Windows, it generates debugger information (in file `libexpat.pdb`). However this file is not installed with `make install`. Therefore it can not be found during debugging, and i.e. it is lost when the build tree is removed.

Would it be possible to add this file to the install target on Windows? I guess something like this may be a good start for shared library builds:
```
if(MSVC AND BUILD_SHARED_LIBS)
    install(FILES $<TARGET_PDB_FILE:${PROJECT_NAME}>
        DESTINATION "${CMAKE_INSTALL_BINDIR}"
        OPTIONAL)
endif()
```
It works a bit different for static libraries, though, and I do not have copy-paste-instructions for that case. See https://stackoverflow.com/a/40860436/7200132 for a good start...

**Comment by emmenlau** [comment]
I just wanted to add that its also possible to generate and store `pdb` files for static library builds. However requires that the `COMPILE_PDB_NAME` is set in cmake for the target. So something along those lines would need to be added in addition to the install command from above, too:
```
if (MSVC AND NOT BUILD_SHARED_LIBS)
    # Set the output name for debugger files, otherwise they are not generated:
    set_target_properties(${PROJECT_NAME}
        PROPERTIES
        COMPILE_PDB_NAME_DEBUG ${PROJECT_NAME}
        COMPILE_PDB_NAME_RELEASE ${PROJECT_NAME}
        COMPILE_PDB_NAME_MINSIZEREL ${PROJECT_NAME}
        COMPILE_PDB_NAME_RELWITHDEBINFO ${PROJECT_NAME})
endif()
```
Then the install command should work for the static and the shared case.

PS: I'm assuming here that the library target is called `${PROJECT_NAME}`. Otherwise please replace this with the library target(s).

**Comment by hartwork** [comment]
Hi @emmenlau to be realistic, with me not using Windows any more I cannot implement this myself in the next few days before release of 2.4.3. After that remains to be seen. Also, it seems that build type `RELWITHDEBINFO` may need special handling and a closer look, as well as split-debug files for Linux. A well-tested clean pull request could make a difference, but its behavior will need to show in the CI to be reviewable by someone who's not on Windows. I'm adding label `help wanted` for now.

**Comment by emmenlau** [comment]
Thanks a lot for the quick and kind response! I very much understand.

About the `RELWITHDEBINFO` case, I'd be more than ok to leave this away for now since its not used by me. If the request comes up in the future it should be easier to add after having some initial support for PDB files now, so I would not see this as a problem.

If you want to go some way before the 2.4.3 release, I've been successfully installing PDB's for the shared library build with something like this patch. Feel free to give it a try if you like?
```
diff --git a/expat/CMakeLists.txt b/expat/CMakeLists.txt
index 7e5b9590..a0abbd06 100644
--- a/expat/CMakeLists.txt
+++ b/expat/CMakeLists.txt
@@ -425,6 +425,11 @@ expat_install(TARGETS expat EXPORT expat
 
 expat_install(FILES lib/expat.h lib/expat_external.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
 
+if(MSVC AND BUILD_SHARED_LIBS)
+  expat_install(FILES $<TARGET_PDB_FILE:expat>
+                DESTINATION ${CMAKE_INSTALL_BINDIR} OPTIONAL)
+endif()
+
 #
 # pkg-config file
 #
```

**Comment by hartwork** [comment]
Note to self: Also needs a check for impact/applicability on the current Windows installer

**Comment by hartwork** [comment]
It seems like this feature is not strong on value, has many bits to research and consider to become sound and complete, the current CI does not cover installation with MSVC so we would need to extend CI first to not add something born broken without knowing, and there has been no related pull request for about two months with someone jumping in to help. To summarize: The cost benefit-to-ratio is quite unhealthy.

I'll be closing this as "probably won't fix". If someone really cares about this feature, is up to do 90% of the work and do voice chat meetings to save on a pile of ping pong and more efficient use of time, please check my profile for contact info. Thanks for your understanding. Closing.
