### ISSUE TITLE
macOS: dylib compatibility/current version inconsistency between CMake and Autotools

### ISSUE THREAD

**Issue by AmirIHz** [libexpat/libexpat#55]
compatibility version and current version of the Mach-O shared library libexpat.dylib built using the Autoconf build system are different from compatibility version and current version of the dylib built using the CMake build system (on macOS).

configure + make link the dylib with `-compatibility_version 8 -current_version 8.3` (see [gist](https://gist.github.com/AmirIHz/2577262b60abc11b0f8a5cae8f09117b))
_After `make install`:_
```
$ otool -L /usr/local/lib/libexpat.dylib
/usr/local/lib/libexpat.dylib:
	/usr/local/lib/libexpat.1.dylib (compatibility version 8.0.0, current version 8.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

CMake + make link the dylib with `-compatibility_version 1.0.0 -current_version 1.6.3` (see [gist](https://gist.github.com/AmirIHz/0001e7e1348c4722fa4b93483056bf5f))
_After `make install`:_
```
$ otool -L /usr/local/lib/libexpat.dylib
/usr/local/lib/libexpat.dylib:
	libexpat.1.dylib (compatibility version 1.0.0, current version 1.6.3)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
```
Version number 1.6.3 is part of the dylib filename in either case: libexpat.1.6.3.dylib (both libexpat.dylib and libexpat.1.dylib are symbolic links pointing to libexpat.1.6.3.dylib)

Any binary that depends on the expat library will fail (crash) if they were linked against the dylib that was built using the "configure way", e.g. tar (bsdtar), which I compiled myself:
```
dyld: Library not loaded: /usr/local/lib/libexpat.1.dylib
  Referenced from: /usr/local/bin/tar
  Reason: Incompatible library version: tar requires version 8.0.0 or later, but libexpat.1.dylib provides version 1.0.0
[1]    45316 abort      tar --version
```

In _CMakeLists.txt_:
```
set(LIBCURRENT 7)   # sync
set(LIBREVISION 3)  # with
set(LIBAGE 6)       # configure.ac!
math(EXPR LIBCURRENT_MINUS_AGE "${LIBCURRENT} - ${LIBAGE}")

if(NOT WIN32)
    set_property(TARGET expat PROPERTY VERSION ${LIBCURRENT_MINUS_AGE}.${LIBAGE}.${LIBREVISION})
    set_property(TARGET expat PROPERTY SOVERSION ${LIBCURRENT_MINUS_AGE})
    set_property(TARGET expat PROPERTY NO_SONAME ${NO_SONAME})
endif(NOT WIN32)
```

_So..._ `${LIBCURRENT_MINUS_AGE}.${LIBAGE}.${LIBREVISION})` → `1.6.3`

In _configure.ac_:
```
dnl
dnl Increment LIBREVISION if source code has changed at all
dnl
dnl If the API has changed, increment LIBCURRENT and set LIBREVISION to 0
dnl
dnl If the API changes compatibly (i.e. simply adding a new function
dnl without changing or removing earlier interfaces), then increment LIBAGE.
dnl 
dnl If the API changes incompatibly set LIBAGE back to 0
dnl

LIBCURRENT=7   # sync
LIBREVISION=3  # with
LIBAGE=6       # CMakeLists.txt!
```
Somewhere in the process this apparently ends up as `8.3.0`?...

Incidentally, I used the tarball from downloads.sourceforge.net, so there was already a `configure`. Cloning this git repository and running `buildconf.sh` first didn't change anything to the end result.

**Comment by hartwork** [comment]
Interesting! The Autotools build system still remains the primary one (i.e. not CMake) so if the configure way is the one causing problems, that's something cool to have fixed. Was bsdtar built in any particular way? Do you have ideas on how to approach this topic for fix?

**Comment by AmirIHz** [comment]
> Interesting! The Autotools build system still remains the primary one (i.e. not CMake) so if the configure way is the one causing problems, that's something cool to have fixed, in particular.

Yep. The only problem is that if the fixed Autotools-built dylib gets compatibility_version **1**.0.0 instead of **8**.0.0 it will break many packages that have libexpat as a dependency. They will need to be recompiled. The official system libexpat.dylib of macOS 10.12.5 has compatibility version **7**.0.0 and current version **8**.0.0 btw:
```
$ otool -L /usr/lib/libexpat.dylib
/usr/lib/libexpat.dylib:
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
> Was bsdtar built in any particular way?

Not really. It was just an example. I'm not sure why libexpat ~is~ was used by my bsdtar as it ~is~ was already compiled with libxml2. Hmmm... I just recompiled libarchive (bsdtar) and now it's not linked against libexpat... strange.
> Do you have ideas on how to approach this topic for fix?

I will investigate and see how I can help.

_PS - Sorry about the issue title changes btw lol_ 😳

**Comment by hartwork** [comment]
Further investigation is welcome. PS: Don't worry about the title changes: I'm not a big fan of the resulting noise but the bug is GitHub's rendering, if anything: Let's not have poor titles because no-one dares to improve them just for noise reduction. Cheers 🍻

**Comment by dmacks** [comment]
The autotools approach is based on libtool, and is doing the Right Thing according to the documented flags. The versioning in compatibility_version is about interface additions (c_v gets bumped when APIs are added so that something compiled against the "newer interface" (symbols added) version will give a saner error message when someone tries to run it against an "older interface" (missing symbols) version. Last I knew, cmake didn't understand that at all. c_v is never allowed to decrease because it will cause anything compiled against the higher one to fail (as noted). And decreasing c_v technically means symbols were removed from the interface, which is a type of backward-incompatible ABI break. That sort of break demands a bump of the number in the install_name of the .dylib itself.

**Comment by RJVB** [comment]
I'm not so certain about that "doing the right thing". Libtool has always had a rather convoluted (read, incomprehensible) way of converting the human-readable version to a library version. Cmake uses a 1:1 mapping: for a project that has version 1.2.3, the actual library will be libFoo.1.2.3.dylib with current_version=1.2.3 and compatibility_version 1.0.0 (or possibly 1.2.0). I think that follows the criteria you describe.

The problem that occurs when migrating from autoconf to cmake without taking Darwin (= Mac OS) into consideration is that the compatibility_version often decreases. And that's the one thing that the runtime loader will reject. Only 1 way around that if you don't want to have to relink all dependents: use SOVERSION when you define the library target in your cmake file. You may end up with surprising versions in the files, e.g. "libfoo.dylib -> libfoo.12.dylib -> libfoo.1.15.dylib"  when I updated popper-qt5 from 0.57.0 (autoconf) to 0.68.0 and made sure the compatibility version remained ... compatible (without that I would have gotten compatibility_version 1.0.0, which in itself would make perfect sense).

Cf. https://webcache.googleusercontent.com/search?q=cache:5gvZ0tlWbx8J:https://cmake.org/Bug/view.php%3Fid%3D4383+&cd=1&hl=en&ct=clnk&gl=fr

**Comment by MacgradyHuang** [comment]
same question.

### question
dyld: Library not loaded: @rpath/libexpat.1.dylib
  Referenced from: /Users/huangpengbo/Projects/GridsumProjects/ticket/venv/bin/uwsgi
  Reason: Incompatible library version: uwsgi requires version 8.0.0 or later, but libexpat.1.dylib provides version 7.0.0
Abort trap: 6

### show the version
$ otool -L /anaconda3/lib/libexpat.1.dylib /usr/lib/libexpat.1.dylib 
/anaconda3/lib/libexpat.1.dylib:
	@rpath/libexpat.1.dylib (compatibility version 8.0.0, current version 8.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
/usr/lib/libexpat.1.dylib:
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

**Comment by hartwork** [comment]
@MacgradyHuang looks like a different (downstream) issue to me. If you have two binaries that depend on expat in different versions, it's not a problem caused by expat: It's a problem with binary distros and re-compiling one or both dependees should fix the problem. What do you think?

**Comment by ShiqinHuo** [comment]
$ uwsgi --version       
dyld: Library not loaded: @rpath/libexpat.1.dylib
  Referenced from: /Users/DoubleHUO/Desktop/Others/University_Admin_app/flaskvenv/bin/uwsgi
  Reason: Incompatible library version: uwsgi requires version 8.0.0 or later, but libexpat.1.dylib provides version 7.0.0
Abort trap: 6

**Comment by hartwork** [comment]
I just re-checked with current CI logs for macOS:

GNU Autotools
- `-version-info 9:7:8` (yields 1.8.7)
- `-compatibility_version 10`
- `-current_version 10.7`
- https://github.com/libexpat/libexpat/runs/5428393156?check_suite_focus=true

CMake
- `-mmacosx-version-min=11.6`
- `-compatibility_version 1.0.0`
- `-current_version 1.8.7`
- https://github.com/libexpat/libexpat/runs/5428393101?check_suite_focus=true

The two build systems have close to zero parts specific to macOS, so to me the question if this needs a fix inside of Expat or outside or even needs a fix at all, is not completly clear to me.  If this situation does need improvement, we will need a well-understood proposed solution. If there was any above that I overlooked, please point me to it.  I have added label `help-wanted` now.

**Comment by thesamesam** [comment]
See also: https://github.com/libsndfile/libsndfile/commit/0cbfc93a3e1a08136a15eb9ced2054402dff6233 (https://github.com/libsndfile/libsndfile/pull/743).

**Comment by hartwork** [comment]
@thesamesam thanks!

Their math seems different: `10.7` above seems to originate from `<current + 1>.<revision>` (thinking libbtool) i.e. `<9 + 1>.<7>` but libsndfile's maths would do `<current + age + 1>.<revision>.0` at https://github.com/libsndfile/libsndfile/commit/0cbfc93a3e1a08136a15eb9ced2054402dff6233#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR33-R35 . 

Also, are we sure that the CMake side is the one that needs changing and not the Autotools side? What I read further up sounded like the other way around.

**Comment by hartwork** [comment]
@thesamesam I checked the local libtool 2.4.6 code and found this:

```bash
        darwin)
          # Like Linux, but with the current version available in
          # verstring for coding it into the library header
          func_arith $current - $age
          major=.$func_arith_result
          versuffix=$major.$age.$revision
          # Darwin ld doesn't like 0 for these options...
          func_arith $current + 1
          minor_current=$func_arith_result
          xlcverstring="$wl-compatibility_version $wl$minor_current $wl-current_version $wl$minor_current.$revision"
          verstring="-compatibility_version $minor_current -current_version $minor_current.$revision"
          # On Darwin other compilers
          case $CC in
              nagfor*)
                  verstring="$wl-compatibility_version $wl$minor_current $wl-current_version $wl$minor_current.$revision"
                  ;;
              *)
                  verstring="-compatibility_version $minor_current -current_version $minor_current.$revision"
                  ;;
          esac
          ;;
```

When I'm translating that 1:1 to Python and put it in IPython I get this:

```
In [1]: def libtool_darwin_ldflags(current, revision, age):
   ...:     minor_current = current + 1
   ...:     verstring = f'-compatibility_version {minor_current} -current_version {minor_current}.{revision}'
   ...:     return verstring
   ...: 
   ...: libtool_darwin_ldflags(9, 7, 8)  # i.e. Expat 2.4.7
Out[1]: '-compatibility_version 10 -current_version 10.7'
```

Note how value `minor`/`age` doesn't go anywhere, despite name `minor_current` implying that it would combine `minor` and `current`.

That matches with I see in Expat CI logs but not what I see in https://github.com/libsndfile/libsndfile/pull/743 .
@evpobr do you have a minute help figure this out?

**Comment by hartwork** [comment]
PS: There is a pull request #582 now. I have a feeling this may already be the right thing to do, but I'll depend on help with review and testing.

**Comment by evpobr** [comment]
Hi. Thanks for the information, we'll see if we have a problem with this.

**Comment by hartwork** [comment]
@evpobr I just noticed that any issues would go unnoticed if ago/minor is zero. Turns out that's indeed the case: https://github.com/libsndfile/libsndfile/blob/77acc6d3623b06c75461a8bfdeff0066278c2eea/configure.ac#L92 . So my impression is: There is a bug and it doesn't show now but it will in the future. I'll make a pull request for libsndfile.
