### ISSUE TITLE
Cover Expat at OWASP article "XML External Entity (XXE) Prevention Cheat Sheet"

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#56]
A section on Expat is missing at [OWASP.org: XML External Entity (XXE) Prevention Cheat Sheet](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet).

Tasks:
1. Evaluate if there are good reasons it's missing
1. Else, get it added 😄

**Comment by amelie-renard-sonarsource** [comment]
Hello,
I'm not going to give a solution to this issue as I am no expert in the security domain, but I just wanted to bring some elements that could help.

From my understanding, for libraries like Xml2 or Xerces, the developer just needs to create a parser, gives it the xml file and run the parsing on this file. By setting (or not) particular options, he can allow the parser to resolve external entities and that would lead to potential vulnerabilities.

On the other hand, Expat works with a mechanism of callbacks. So for external entities for example, the developer will have to attach to the parser an appropriate handler which will be called for each external entity the parser finds. It will then be in this callback that the developer can choose to process the external entity or not (for example par running another XMLParser on it).

All of that to say that it seems to me that Expat is more robust to this particular kind of attack than the libraries listed in the Cheat Sheet as the developer is more aware of what is done.
(even though I would never dare to say that Expat is invulnerable 😅 )

**Comment by hartwork** [comment]
Hi @amelie-renard-sonarsource, I somehow missed your reply — sorry!

Full ack about your point :+1: I'll close the ticket as "okay as it is" then.
