### ISSUE TITLE
Solaris and error: 'NAN' was not declared in this scope

### ISSUE THREAD

**Issue by noloader** [libexpat/libexpat#569]
Hi Everyone,

I'm updating OpenSSH on Solaris 11.4 i86. libexpat is a dependency. libexpat 2.4.5 is having a little trouble:

```
$ make check -k
...
/bin/g++ -DHAVE_CONFIG_H -I. -I..   -DXML_ENABLE_VISIBILITY=1 -I./../lib -I/opt/ssh/incl
ude -DNDEBUG -Wall   -fexceptions -fno-strict-aliasing -g2 -O2 -m64 -march=native -fPIC
-pthread -MT runtestspp.o -MD -MP -MF .deps/runtestspp.Tpo -c -o runtestspp.o runtestspp
.cpp
In file included from runtestspp.cpp:36:0:
runtests.c: In function 'void test_billion_laughs_attack_protection_api()':
runtests.c:11712:32: error: 'NAN' was not declared in this scope
          parserWithoutParent, NAN)
                               ^
runtests.c:11734:32: error: 'INFINITY' was not declared in this scope
          parserWithoutParent, INFINITY)
                               ^
*** Error code 1
```

This patch appears to clear the issue. The self tests build and run without problems:

```diff
$ cat expat.patch 
--- tests/runtests.c
+++ tests/runtests.c 
@@ -60,6 +60,16 @@
 #  include <stdbool.h>
 #endif
 
+#if defined(__sun__)
+#  include <sunmath.h>
+#  if ! defined(INFINITY)
+#    define INFINITY (__builtin_huge_val())
+#  endif
+#  if ! defined(NAN)
+#    define NAN (__builtin_nan(""))
+#  endif
+#endif
+
 #include "expat.h"
 #include "chardata.h"
 #include "structdata.h"
@@ -6636,7 +6646,8 @@
   XML_Char **elemstr = (XML_Char **)userData;
   if (xcstrcmp(elemstr[0], name) != 0) {
     char buffer[1024];
-    sprintf(buffer, "unexpected end string: '%" XML_FMT_STR "'", name);
+    snprintf(buffer, sizeof(buffer), "unexpected end string: '%" XML_FMT_STR "'", name);
+    buffer[sizeof(buffer)-1] = '\0';  /* ensure NULL termination */
     fail(buffer);
   }
   triplet_end_flag = XML_TRUE;
```

**Comment by hartwork** [comment]
PS: `snprintf` proved to be trouble already at #259 and https://ci.appveyor.com/project/libexpat/libexpat/builds/24465804/job/wm13h1k8ru4buslj#L240 .

**Comment by hartwork** [comment]
> GCC bounds checker warning. It was done to squash the warning.

@noloader there are 16 other places with `sprintf` in the test suite. Can you help understand why this and only this one produces bounds check warnings?

**Comment by hartwork** [comment]
@noloader can you confirm that patch [0001-tests-Resolve-use-of-macros-NAN-and-INFINITY-for-GNU.patch.txt](https://github.com/libexpat/libexpat/files/8126880/0001-tests-Resolve-use-of-macros-NAN-and-INFINITY-for-GNU.patch.txt) makes GNU G++ 4.8.2 happy on Solaris?

**Comment by noloader** [comment]
@hartwork,

This is what I see with libexpat 2.4.5:

```
$ make check 2>&1 | fold -w 80
Making check in lib
Making check in examples
Making check in tests
Making check in .
make  runtests runtestspp
`runtests' is up to date.
/bin/g++ -DHAVE_CONFIG_H -I. -I..   -DXML_ENABLE_VISIBILITY=1 -I./../lib -I/expo
rt/home/jwalton/tmp/ok2delete/include -DNDEBUG -Wall   -fexceptions -fno-strict-
aliasing -g2 -O2 -m64 -march=native -fPIC -pthread -MT runtestspp.o -MD -MP -MF 
.deps/runtestspp.Tpo -c -o runtestspp.o runtestspp.cpp
In file included from runtests.c:49:0,
                 from runtestspp.cpp:36:
runtests.c: In function 'float portableINFINITY()':
runtests.c:11699:32: error: 'isinf' was not declared in this scope
   assert(isinf(handmadeINFINITY));
                                ^
```

**Comment by hartwork** [comment]
Hi @noloader , thanks for trying it out. Does that mean it has `isnan` but not `isinf`?

**Comment by noloader** [comment]
> Does that mean it has isnan but not isinf?

According to [Sun docs | The Math Libraries](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_lib.html) Table 3.1, `isnan` is available in `libm`, but `isinf` is not listed. Table 3.2 lists `isinf` as part of The Sun Math Library. `<sunmath.h>` and `libsunmath`.

**Comment by noloader** [comment]
@hartwork,

What do you think about [this from MySQL](https://bugs.mysql.com/bug.php?id=14862) folks:

> Add the following two lines to strings/strtod.c:
> #include <ieeefp.h>
> int isinf(double x) { return !finite(x) && x==x; }
> 
> I got this from the web:
>  Why do I get isinf undefined when linking with libdps on Solaris 2.3?
> 
> That's a bug in libdps (fixed in 2.4). Sun compiles and links its
> software with its own compilers. The isinf() function is shipped
> with the SunPRO compilers, but not defined in any Solaris 2.3
> library.
> 
> A workaround exists, and consists of adding the following to
> your program:
> 
> #include <ieeefp.h>
> 
> int isinf(double x) { return !finite(x) && x==x; }

**Comment by noloader** [comment]
> #include <ieeefp.h>
>
> int isinf(double x) { return !finite(x) && x==x; }

Ah, that just kicks the can down the road:

```
runtests.c: In function 'int isinf(double)':
runtests.c:11689:46: error: 'finite' was not declared in this scope
 static int isinf(double x) { return !finite(x) && x==x; }
                                              ^
```

**Comment by hartwork** [comment]
@noloader I have dropped use of `isinf` now. How about this version:
[0001-tests-Resolve-use-of-macros-NAN-and-INFINITY-for-GNU.patch.txt](https://github.com/libexpat/libexpat/files/8127880/0001-tests-Resolve-use-of-macros-NAN-and-INFINITY-for-GNU.patch.txt)

**Comment by noloader** [comment]
@hartwork,

Yes, the last patched compiled and successfully completed its self tests. I did not know that's the portable way to get infinity and nan.

There were some minor warnings during build:

```
/bin/gcc -DHAVE_CONFIG_H -I. -I..  -DXML_ENABLE_VISIBILITY=1 -I./../lib -I/export/home/jwalton/tmp/ok2delete/include -DNDEBUG -Wall   -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wlogical-op -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -fvisibility=hidden -g2 -O2 -m64 -march=native -fPIC -pthread -std=c99 -MT runtests.o -MD -MP -MF .deps/runtests.Tpo -c -o runtests.o runtests.c
runtests.c:11689:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 portableNAN() {
 ^
runtests.c:11694:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 portableINFINITY() {
 ^
cc1: warning: unrecognized command line option "-Wno-pedantic-ms-format" [enabled by default]
```

**Comment by hartwork** [comment]
> Yes, the last patched compiled and successfully completed its self tests.

@noloader cool, thank you!

> I did not know that's the portable way to get infinity and nan.

It's one way that felt worth trying.

> That seems like something that should be in Gnulib. Do you use it?

Only once. But's let focus on Expat for now.

> There were some minor warnings during build:
> 
> ```
> /bin/gcc -DHAVE_CONFIG_H -I. -I..  -DXML_ENABLE_VISIBILITY=1 -I./../lib -I/export/home/jwalton/tmp/ok2delete/include -DNDEBUG -Wall   -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wlogical-op -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -fvisibility=hidden -g2 -O2 -m64 -march=native -fPIC -pthread -std=c99 -MT runtests.o -MD -MP -MF .deps/runtests.Tpo -c -o runtests.o runtests.c
> runtests.c:11689:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>  portableNAN() {
>  ^
> runtests.c:11694:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>  portableINFINITY() {
>  ^
> cc1: warning: unrecognized command line option "-Wno-pedantic-ms-format" [enabled by default]
> ```

That could be about missing `void`in the braces or so, and it may be legacy by now. I'll only address that if the CI says it too. We have `-Werror` in there.

**Comment by noloader** [comment]
Thank you very much!
