### ISSUE TITLE
Add license file to repository root

### ISSUE THREAD

**Issue by tbeu** [libexpat/libexpat#585]
Would be nice if the repository's root directory contains a LICENSE or COPYING file as recommended by GitHub for greater transparency, Additionally, it would be correct if the existing license file reflects the current development:

https://github.com/libexpat/libexpat/blob/bccf36869d4fb683fc01842e0d5d967cfcbcd039/expat/COPYING#L2

Thanks.

**Comment by hartwork** [comment]
Hi @tbeu, so it seems to take:
- a bump from "2001-2019" to "2001-2022"
- a new symlink a la `ln -s expat/COPYING COPYING` similar to what we have for `README.md`.

Can you make a pull request?

**Comment by tbeu** [comment]
I would not mess with symlinks as it does not work cross-platform.

**Comment by hartwork** [comment]
@tbeu why does it need to work cross-platform? The release archives do not include that file so it's sole purpose is display on GitHub.

**Comment by tbeu** [comment]
OK, I'll give it a try.

**Comment by tbeu** [comment]
Checkout https://github.com/tbeu/libexpat and click the "View license" link:

![image](https://user-images.githubusercontent.com/5444067/158677402-9909b717-7d7d-4688-b41e-a3053c7c46ee.png)

**Comment by hartwork** [comment]
@tbeu be honest, you added a plain text file saying "expat/COPYING" :wink:
Okay, so symlink does not work too well. Sigh.
Regarding the change in line order in the header of of https://github.com/tbeu/libexpat/commit/261da9139396fbf91869ad9ef99503fdcb023169 I don't think we should do that.

**Comment by tbeu** [comment]
No, I created the symlink in WSL and added/commited using TortoiseGit. It looks identically when you click on the README symlink on GitHub.

**Comment by Miles-Davies-HORIBA** [comment]
Hi, I use a FOSS management tool called Mend, was WhiteSource. This tool scans my repo looking for open source software and then compares my repo with a database of know open source projects. It can then be used to produce a SBOM or an Open Source Attribution report. There are several tools like this and all of them get license and copyright information from GitHub using the standard COPYRIGHT and LICENSE files. You could symlink your readme.txt which has a copyright but I would suggest following the GitHub 'best practice' guidelines so external tools can better process your repository. 

Thanks for maintaining this code

**Comment by tbeu** [comment]
Not sure how to proceed here ❓

**Comment by tbeu** [comment]
> I would not mess with symlinks as it does not work cross-platform.

Thanks for following my advice and finally have it resolved.
