### ISSUE TITLE
Always initialize pointer with NULL

### ISSUE THREAD

**Issue by orbitcowboy** [libexpat/libexpat#592]
Here is an example where a pointer should be initialized to `NULL`

https://github.com/libexpat/libexpat/blob/3bab6c09bbe8bf42d84b81563ddbcf4cca4be838/expat/xmlwf/win32filemap.c#L110

I can provide a pull request if needed.

Thanks

**Comment by hartwork** [comment]
I have checked the [docs of function `FormatMessage`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage) that this pointer is used with. How would initializing this pointer to `NULL` make a practical difference?

**Comment by hartwork** [comment]
@orbitcowboy is there some tool that warns you about this single variable and nothing else? If yes, let's set it to `NULL` to get the noise out of your day, if not, we leave as is. What do you think?
