### ISSUE TITLE
building expat 2.4.8 on windows using static runtime fails

### ISSUE THREAD

**Issue by fbergmann** [libexpat/libexpat#597]
Trying to upgrade to the latest version of expat using MSVC 2022, I find it impossible to link against expat, when compiled with the static runtime options. Here my cmake variables: 

```
  set (EXPAT_SHARED_LIBS OFF)
  set (EXPAT_BUILD_EXAMPLES OFF)
  set (EXPAT_BUILD_TESTS OFF)
  set (EXPAT_BUILD_TOOLS OFF)
  set (EXPAT_BUILD_TOOLS OFF)
  if (WITH_STATIC_RUNTIME)
    #expat is overriding this, so enforce it to be
    set(EXPAT_MSVC_STATIC_CRT ON CACHE BOOL "Use /MT flag (static CRT) when compiling in MSVC" FORCE)
  endif()
```

Unfortunately, when trying to link against the library, i get an undefined symbol:

```
libexpat.lib(xmlparse.c.obj) : error LNK2019: unresolved external symbol __imp_rand_s referenced in function generate_hash_secret_salt
```

additionally there are warnings, that indicate that the static runtime seems to be ignored: 

```
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
LINK : warning LNK4217: symbol '_errno' defined in 'libucrt.lib(errno.obj)' is imported by 'libexpat.lib(xmlparse.c.obj)' in function 'ENTROPY_DEBUG'
LINK : warning LNK4217: symbol '__acrt_iob_func' defined in 'libucrt.lib(_file.obj)' is imported by 'libexpat.lib(xmlparse.c.obj)' in function 'ENTROPY_DEBUG'
LINK : warning LNK4217: symbol '__stdio_common_vfprintf' defined in 'libucrt.lib(output.obj)' is imported by 'libexpat.lib(xmlparse.c.obj)' in function '_vfprintf_l'
LINK : warning LNK4217: symbol 'free' defined in 'libucrt.lib(free.obj)' is imported by 'libexpat.lib(xmlparse.c.obj)' in function 'parserCreate'
LINK : warning LNK4217: symbol 'malloc' defined in 'libucrt.lib(malloc.obj)' is imported by 'libexpat.lib(xmlparse.c.obj)' in function 'parserCreate'
LINK : warning LNK4217: symbol 'realloc' defined in 'libucrt.lib(realloc.obj)' is imported by 'libexpat.lib(xmlparse.c.obj)' in function 'parserCreate'
LINK : warning LNK4217: symbol 'strtoul' defined in 'libucrt.lib(strtox.obj)' is imported by 'libexpat.lib(xmlparse.c.obj)' in function 'ENTROPY_DEBUG'
LINK : warning LNK4217: symbol 'getenv' defined in 'libucrt.lib(getenv.obj)' is imported by 'libexpat.lib(xmlparse.c.obj)' in function 'ENTROPY_DEBUG'
```

**Comment by hartwork** [comment]
@fbergmann PS: I found that builds with earlier releases of MSVC already show the LNK4217 link errors your mention and despite `/WX` they do not make the link fail. If you have insights/ideas on those warnings, that would help. The CI log I inspected is online at https://ci.appveyor.com/project/libexpat/libexpat/builds/43180854/job/o4yu4rfu7g01qrtc .

**Comment by hartwork** [comment]
@fbergmann PPS:
- AppVeyor does have MSVC 2022, they introduced it at https://www.appveyor.com/blog/2021/11/10/visual-studio-2022-image/ .
- When I make AppVeyor build with your config, I get no error, see:
  - the changes I did at https://github.com/libexpat/libexpat/commit/27810a2ea8e8ac99759ea141151bd475e4f776c4
  - log at https://ci.appveyor.com/project/libexpat/libexpat/builds/43217670
- I'm adding some general (non-static-CRT coverage) to MSVC 2022 in pull request #598 now.

How should we continue from here?

**Comment by fbergmann** [comment]
I believe the first thing to do would be to change from the `set` command to the `option`. That is instead of: 

```
set(EXPAT_MSVC_STATIC_CRT OFF CACHE BOOL "Use /MT flag (static CRT) when compiling in MSVC")
```

to have an option for that case. With an option in can be sure that my previously set value takes priority to the changing of the value. I'll be sure to do more testing tomorrow, as i want this to work.

**Comment by fbergmann** [comment]
In the end my problem went away using the option command instead: 

```diff

diff --git a/expat/CMakeLists.txt b/expat/CMakeLists.txt
index 6797fd43..7a392c8e 100644
--- a/expat/CMakeLists.txt
+++ b/expat/CMakeLists.txt
@@ -150,7 +150,7 @@ mark_as_advanced(EXPAT_LARGE_SIZE)
 option(EXPAT_MIN_SIZE "Get a smaller (but slower) parser (in particular avoid multiple copies of the tokenizer)" OFF)
 mark_as_advanced(EXPAT_MIN_SIZE)
 if(MSVC OR _EXPAT_HELP)
-    set(EXPAT_MSVC_STATIC_CRT OFF CACHE BOOL "Use /MT flag (static CRT) when compiling in MSVC")
+    option(EXPAT_MSVC_STATIC_CRT "Use /MT flag (static CRT) when compiling in MSVC" OFF)
 endif()
 if(NOT _EXPAT_HELP)
     set(_EXPAT_M32 OFF CACHE BOOL "(Unofficial!) Produce 32bit code with -m32")

```

and the additional linking warnings by changing the expat find module to see whether the `XML_STATIC` define was needed or not.

**Comment by hartwork** [comment]
> In the end my problem went away using the option command instead:

So that is disabling caching of the option? Before I understand the full picture here, this seems like something that is not suited for applying upstream.

> and the additional linking warnings by changing the expat find module to see whether the `XML_STATIC` define was needed or not.

Could you elaborate? If there something needs fixing upstream, I don't understand yet how, what, and why.

**Comment by fbergmann** [comment]
> 



> > In the end my problem went away using the option command instead:
> 
> So that is disabling caching of the option? Before I understand the full picture here, this seems like something that is not suited for applying upstream.
> 

No .. it just means, that currently a user defined value of `EXPAT_MSVC_STATIC_CRT ` is just overridden by the `set` command. using the `option` statement, the value is still cached, however if it was previously set to a specific value, that value would be honored. 

> > and the additional linking warnings by changing the expat find module to see whether the `XML_STATIC` define was needed or not.
> 
> Could you elaborate? If something needs fixing in that regard, I don't understand yet how, what, and why.

The warnings that were mentioned above as indicated by your [link](https://ci.appveyor.com/project/libexpat/libexpat/builds/43180854/job/o4yu4rfu7g01qrtc) are due to the fact that `XML_STATIC` was not defined.

**Comment by hartwork** [comment]
> No .. it just means, that currently a user defined value of `EXPAT_MSVC_STATIC_CRT ` is just overridden by the `set` command. using the `option` statement, the value is still cached, however if it was previously set to a specific value, that value would be honored.

The set command in Expat has no `FORCE` but `CACHE` so if it's changing the value that indicates that you had file `CMakeCache.txt` around prior to the call to CMake and then use of a cached value would be expected behavior. Please confirm or help me understand what I am missing here.


> > > and the additional linking warnings by changing the expat find module to see whether the `XML_STATIC` define was needed or not.
> > 
> > 
> > Could you elaborate? If something needs fixing in that regard, I don't understand yet how, what, and why.
> 
> The warnings that were mentioned above as indicated by your [link](https://ci.appveyor.com/project/libexpat/libexpat/builds/43180854/job/o4yu4rfu7g01qrtc) are due to the fact that `XML_STATIC` was not defined.

I don't follow. I don't understand why and when we should be setting `XML_STATIC` any more places. Please elaborate on the bug and the fix.

**Comment by fbergmann** [comment]
> > No .. it just means, that currently a user defined value of `EXPAT_MSVC_STATIC_CRT ` is just overridden by the `set` command. using the `option` statement, the value is still cached, however if it was previously set to a specific value, that value would be honored.
> 
> The set command in Expat has no `FORCE` but `CACHE` so if it's changing the value that indicates that you had file `CMakeCache.txt` around prior to the call to CMake and then use of a cached value would be expected behavior. Please confirm or help me understand what I am missing here.
> 

for me it is just an inconsistency, for all other configuration options i can just call

```
  set (EXPAT_SHARED_LIBS OFF)
  set (EXPAT_BUILD_EXAMPLES OFF)
  set (EXPAT_BUILD_TESTS OFF)
  set (EXPAT_BUILD_TOOLS OFF)
  set (EXPAT_BUILD_TOOLS OFF)
``

before including expat. It is only for the CRT configuration choice (which really should be an option) that i have to use: 

```
set(EXPAT_MSVC_STATIC_CRT ON CACHE BOOL "Use /MT flag (static CRT) when compiling in MSVC" FORCE)
```

so that the value is honored. There is no reason to treat it other than any other configuration option. 

> > > > and the additional linking warnings by changing the expat find module to see whether the `XML_STATIC` define was needed or not.
> > > 
> > > 
> > > Could you elaborate? If something needs fixing in that regard, I don't understand yet how, what, and why.
> > 
> > 
> > The warnings that were mentioned above as indicated by your [link](https://ci.appveyor.com/project/libexpat/libexpat/builds/43180854/job/o4yu4rfu7g01qrtc) are due to the fact that `XML_STATIC` was not defined.
> 
> I don't follow. I don't understand why and when we should be setting `XML_STATIC` any more places. Please elaborate on the bug and the fix.

It was a warning in your own test cases, i'm ok with them not being fixed. both your runtests and runtestcpp project you linked were missing the XML_STATIC define, thus you got the warnings issued during linking.

**Comment by hartwork** [comment]
> for me it is just an inconsistency, for all other configuration options i can just call
> 
> ```
>   set (EXPAT_SHARED_LIBS OFF)
>   set (EXPAT_BUILD_EXAMPLES OFF)
>   set (EXPAT_BUILD_TESTS OFF)
>   set (EXPAT_BUILD_TOOLS OFF)
>   set (EXPAT_BUILD_TOOLS OFF)
> ```
> 
> before including expat. It is only for the CRT configuration choice (which really should be an option) that i have to use:
> 
> ```
> set(EXPAT_MSVC_STATIC_CRT ON CACHE BOOL "Use /MT flag (static CRT) when compiling in MSVC" FORCE)
> ```
> 
> so that the value is honored. There is no reason to treat it other than any other configuration option.

@fbergmann I have done some research on the behavior and difference of `option(..)` and `set(.. CACHE ..)` now.
For my local experiment, my `CMakeLists.txt` was this:
```CMake
project(p1)

option(P1_A "option A")
option(P1_B "option B" OFF)
set(P1_C OFF CACHE BOOL "set C")
set(P1_D OFF CACHE BOOL "set D" FORCE)
```

Then on the shell I did:

```console
# rm -Rf build/

# cmake -B build
[..]

# fgrep P1 build/CMakeCache.txt 
P1_A:BOOL=OFF
P1_B:BOOL=OFF
P1_C:BOOL=OFF
P1_D:BOOL=OFF

# cmake -B build -DP1_{A,B,C,D}=ON 
[..]

# fgrep P1 build/CMakeCache.txt 
P1_A:BOOL=ON
P1_B:BOOL=ON
P1_C:BOOL=ON
P1_D:BOOL=OFF
```

As you can see, both `option(..)` and `set(.. CACHE ..)` (1) use a cache entry and (2) can be overridden, unless `FORCE` is added.

Based on these results and [StackOverflow "What is the difference between "option" and "set CACHE BOOL" for a CMake variable?"](https://stackoverflow.com/questions/36358217/what-is-the-difference-between-option-and-set-cache-bool-for-a-cmake-variabl) my impression is that:
- There is a small difference between `set(.. CACHE ..)` and `option(..)` but none that would matter to your case.
- Your use of `FORCE` is cache problem, not an Expat problem.
- Expat uses `set(.. CACHE ..)` 5 times and  `option(..)` 18 times, today. That's an inconsistency that could be be fixed two ways (with arguments for both sides). It's not a bug.

**Comment by hartwork** [comment]
> It was a warning in your own test cases, i'm ok with them not being fixed. both your runtests and runtestcpp project you linked were missing the XML_STATIC define, thus you got the warnings issued during linking.

Thanks for elaborating. I'm not sure why, but adding `XML_STATIC` to the test runners does not fix those LNK4217 warnings, see:
- My work-in-progress commits on the matter at https://github.com/libexpat/libexpat/compare/master...185c9d8bc986944a1a959e5ee01ec367e0153b78
- A run with those commits applied https://ci.appveyor.com/project/libexpat/libexpat/builds/43254188/job/oa4jjr50i28bolvg

Any ideas?

**Comment by hartwork** [comment]
@fbergmann update on that^^: I fixed something and now LNK4217 seems indeed gone. That's pull request #599 now.

**Comment by fbergmann** [comment]
> @fbergmann I have done some research on the behavior and difference of `option(..)` and `set(.. CACHE ..)` now. For my local experiment, my `CMakeLists.txt` was this:
> 
> ```cmake
> project(p1)
> 
> option(P1_A "option A")
> option(P1_B "option B" OFF)
> set(P1_C OFF CACHE BOOL "set C")
> set(P1_D OFF CACHE BOOL "set D" FORCE)
> ```

In my usecase, i use expat as one of several projects, my solutions builds on. We used to use a quite old version of expat, but going forward i wanted to use a submodule of the official repository. That's when i noticed, that just setting `EXPAT_MSVC_STATIC_CRT ` as the other options failed. So i filed this issue to let you know. For me now: 

```
if (WITH_EXPAT)
  set (EXPAT_SHARED_LIBS OFF)
  set (EXPAT_BUILD_EXAMPLES OFF)
  set (EXPAT_BUILD_TESTS OFF)
  set (EXPAT_BUILD_TOOLS OFF)
  set (EXPAT_BUILD_TOOLS OFF)
  if (WITH_STATIC_RUNTIME)
    #expat is overriding this
    set(EXPAT_MSVC_STATIC_CRT ON CACHE BOOL "Use /MT flag (static CRT) when compiling in MSVC" FORCE)
  endif()

  add_subdirectory(expat/expat)
endif()
```

works, I'd have preferred to set the variable another way (as it would have saved me some hours trying to figure out why my settings were not honored), but if you are uncomfortable with changing this, that is fine with me. It is just, that it made no sense for me to treat the crt variable any other way, then the other build variables.

**Comment by hartwork** [comment]
@fbergmann I cannot confirm that `FORCE` would be needed with `add_subdirectory` in my own experiments. My `CMakeLists.txt` is this:

```CMake
cmake_minimum_required(VERSION 3.23)

project(p1)

set(WIN32 ON)
set(EXPAT_SHARED_LIBS OFF)
set(EXPAT_BUILD_EXAMPLES OFF)
set(EXPAT_BUILD_TESTS OFF)
set(EXPAT_BUILD_TOOLS OFF)
set(EXPAT_MSVC_STATIC_CRT ON)

add_subdirectory(libexpat/expat)

foreach(var WIN32 EXPAT_SHARED_LIBS EXPAT_BUILD_EXAMPLES EXPAT_BUILD_TESTS EXPAT_BUILD_TOOLS EXPAT_MSVC_STATIC_CRT)
    message(STATUS "${var}")
    message(STATUS "  parent: ${${var}}")
    get_directory_property(_value DIRECTORY libexpat/expat DEFINITION "${var}")
    message(STATUS "  child:  ${_value}")
endforeach()
```

And then on the shell:

```console
# rm CMakeCache.txt 

# git clone --depth 1 https://github.com/libexpat/libexpat

# cmake .
[..]
-- WIN32
--   parent: ON
--   child:  ON
-- EXPAT_SHARED_LIBS
--   parent: OFF
--   child:  OFF
-- EXPAT_BUILD_EXAMPLES
--   parent: OFF
--   child:  OFF
-- EXPAT_BUILD_TESTS
--   parent: OFF
--   child:  OFF
-- EXPAT_BUILD_TOOLS
--   parent: OFF
--   child:  OFF
-- EXPAT_MSVC_STATIC_CRT
--   parent: ON
--   child:  ON
[..]
```

So to me that looks like all values are forwarded, properly. Please prove with a minimal example how `FORCE` is really needed for you.

PS: I'm setting `WIN32=ON` only to fake Windows on my local Linux box, if that matters.

**Comment by fbergmann** [comment]
That test is incomplete, please add `grep MSVC_STATIC CMakeCache.txt` after the cmake run. When just setting the variable, the cache variable defined later will override it. In my case by using the cache force option the resulting CMakeCache.txt file has the property set to ON, while without FORCE it is set to OFF.

**Comment by hartwork** [comment]
@fbergmann I confirm the behavior you describe when adding `set(MSVC ON)`:

```console
# rm -f CMakeCache.txt ; cmake .
[..]
-- EXPAT_MSVC_STATIC_CRT
--   parent: ON
--   child:  OFF
[..]
```

I also confirm that the patch below results in `child:  ON` when running again:

```diff
 if(MSVC OR _EXPAT_HELP)
-    set(EXPAT_MSVC_STATIC_CRT OFF CACHE BOOL "Use /MT flag (static CRT) when compiling in MSVC")
+    option(EXPAT_MSVC_STATIC_CRT "Use /MT flag (static CRT) when compiling in MSVC" OFF)
 endif()
```

**Comment by hartwork** [comment]
@fbergmann it seems like we have to choose between (a) losing type information with mass-migrating to `option(..)` or (b) requiring force everywhere with mass-migrating to `set(.. CACHE ..)`. Seems like pest or cholera to me. Why pest (a) in your eyes?

**Comment by hartwork** [comment]
@fbergmann PS: With (a) we'll take away control that the user had and give it to the project using Expat. With (b) we give more control to the user but force projects to use `FORCE` now where previously not needed. Either change has potential to cause breakage to someone. A build system is not a stable API, but I felt that this _cost_ of increasing consistency deserves mention.

**Comment by fbergmann** [comment]
I obviously prefer a):

* it is consistent with the other options defined
* it resolves the (to me surprising change of the variable)
* for me it does not take away anything: if a variable is already defined it will be honored, otherwise option will create a cache boolean variable, that will appear in cmake gui tools for people to easily change. So can you elaborate what control was taken away?
* it does not break anyone else's code: if a variable or cache variable with the name of the option exists, it will be honored, otherwise a new cache variable with the desired default value is created.

**Comment by hartwork** [comment]
Hi @fbergmann,

time flies, sorry it took me so long to get back to this topic! You do have a point about the inconsistency, about the user experience, and about the advantage we get from `option()` being "shy". I have put more thought and research into this problem now and would like to suggest pull request #627 for a fix. Your review and testing would be greatly appreciated. Thanks in advance! :pray: 

PS: From your point of view, is there anything left in this issue here that is *not* covered by any of pull requests…

- #598
- #599
- #627

…?

**Comment by hartwork** [comment]
@fbergmann any chance you could check out PR #627?

**Comment by AsifKhan-78** [comment]
@fbergmann How did you resolve this issue 

libexpat.lib(xmlparse.c.obj) : error LNK2019: unresolved external symbol __imp_rand_s referenced in function generate_hash_secret_salt

**Comment by hartwork** [comment]
@AsifKhan-78 did you see https://github.com/libexpat/libexpat/issues/597#issuecomment-1097056095 ? Which version of Expat and which compiler on which operating system are you using?

**Comment by hartwork** [comment]
@AsifKhan-78 it should be noted that Expat >=2.5.9 includes related pull request #599 so that the above should not be needed with recent Expat 2.5.0. For security fixes also use of Expat >=2.5.0 is recommended, 2.4.8 and 2.4.9 should not be used by anyone in 2024.

**Comment by hartwork** [comment]
@AsifKhan-78 PS: In case you are using Expat through pkg-config on Windows, ongoing pull request #805 could be of interest.

**Comment by AsifKhan-78** [comment]
@hartwork Thanks for your input, yes I am using it on windows. I can switch to the recommended versions
