### ISSUE TITLE
Unnecessarily complex allocation

### ISSUE THREAD

**Issue by RMJ10** [libexpat/libexpat#6]
xmlparse.c lines 1630-1632 are unnecessarily complex if reallocation functions are required to match realloc()'s semantics (I couldn't find a definitive statement).  `realloc(NULL, size)` should be equivalent to `malloc(size)`, so there's no need to dance around checking that buffer is not NULL.

A low priority issue, I think.

**Comment by hartwork** [comment]
For the record, this comment applied to [`xmlparse.c` as of 64dca0bf4b71764a140694d5eec42fc34b15a219](https://github.com/libexpat/libexpat/blob/64dca0bf4b71764a140694d5eec42fc34b15a219/expat/lib/xmlparse.c#L1630).
