### ISSUE TITLE
sip24_valid function call missing?

### ISSUE THREAD

**Issue by micheleselea** [libexpat/libexpat#605]
Hi all, I have a question about  function

```
static unsigned long FASTCALL
hash(XML_Parser parser, KEY s) {
```
there's this line of code `(void)sip24_valid;`
I understand from the code sip24_valid it's a function, should be called as `(void)sip24_valid();` or was intentional written as is?

**Comment by hartwork** [comment]
Hi @micheleselea `(void)sip24_valid();` is marking the function as used to silence warnings, there was no intention of calling the function at that place. `sip24_valid` is a self-test function of the siphash header library. Does that answer the question?

**Comment by micheleselea** [comment]
ok thanks, was just to be sure was not a type error, that just because VisualStudio point that line as warnig.
Ok  so it's all ok, thanks
