### ISSUE TITLE
unfinished m_declAttributeType allocation in ->m_tempPool can corrupt following allocation

### ISSUE THREAD

**Issue by thejh** [libexpat/libexpat#612]
When DTD processing inside a parameter entity encounters a reference to an undefined entity, it will clear the `dtd->keepProcessing` flag but keep parsing.
If `dtd->keepProcessing` is cleared between `XML_ROLE_ATTRIBUTE_ENUM_VALUE` and `XML_ROLE_REQUIRED_ATTRIBUTE_VALUE` because an undefined entity is encountered in the middle of the `<!ATTLIST` declaration, then the `XML_ROLE_ATTRIBUTE_ENUM_VALUE` handler will have started writing data into the `&parser->m_tempPool`, but that allocation has not been finalized with `poolFinish()` yet. But the `XML_ROLE_REQUIRED_ATTRIBUTE_VALUE` handler doesn't touch `&parser->m_tempPool` if `dtd->keepProcessing` has been cleared, so the unfinished allocation stays in the `&parser->m_tempPool` beyond the end of the `<!ATTLIST` declaration.

However, other parts of the codebase assume that `&parser->m_tempPool` does not contain any unfinished allocations; otherwise, for example, `reportComment()` will misbehave and wrongly report that part of the `<!ATTLIST` declaration is part of the comment.

How to reproduce:

Patch expat's `xmlwf` like this to trigger the `m_attlistDeclHandler` codepath:

```
diff --git a/expat/xmlwf/xmlwf.c b/expat/xmlwf/xmlwf.c
index 471f2a20..d6e44889 100644
--- a/expat/xmlwf/xmlwf.c
+++ b/expat/xmlwf/xmlwf.c
@@ -534,6 +534,19 @@ nopStartElement(void *userData, const XML_Char *name, const XML_Char **atts) {
   UNUSED_P(atts);
 }
 
+// dummy handler, need to have one to trigger broken codepath
+static void XMLCALL
+attlist_decl_handler(void* userData, const XML_Char* elname,
+                     const XML_Char* attname, const XML_Char* atttype,
+                     const XML_Char* dflt, int isrequired) {
+  UNUSED_P(userData);
+  UNUSED_P(elname);
+  UNUSED_P(attname);
+  UNUSED_P(atttype);
+  UNUSED_P(dflt);
+  UNUSED_P(isrequired);
+}
+
 static void XMLCALL
 nopEndElement(void *userData, const XML_Char *name) {
   UNUSED_P(userData);
@@ -1119,6 +1132,8 @@ tmain(int argc, XML_Char **argv) {
       exit(XMLWF_EXIT_INTERNAL_ERROR);
     }
 
+    XML_SetAttlistDeclHandler(parser, attlist_decl_handler);
+
     if (attackMaximumAmplification != -1.0f) {
 #ifdef XML_DTD
       XML_SetBillionLaughsAttackProtectionMaximumAmplification(
```

Then build, and run `xmlwf` against these inputs:

```
$ cat test_comment_inject/test.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foo [
  <!ELEMENT foo ANY>
  <!ENTITY % entp SYSTEM "external.dtd">
  %entp;
]>
<a></a>

$ cat test_comment_inject/external.dtd 
<!ELEMENT barf ANY>
<!ATTLIST barf my_attr (blah|%blah;a|foo) #REQUIRED>
<!--COMMENT-->
$ expat/xmlwf/xmlwf -n -p -x -m -d test_comment_inject/out test_comment_inject/test.xml
$ cat test_comment_inject/out/test.xml 
<document>
<startdoctype name="foo" uri="test_comment_inject/test.xml" byte="53" nbytes="1" line="2" col="14"/>
<entity name="entp" system="external.dtd" uri="test_comment_inject/test.xml" byte="115" nbytes="0" line="4" col="39"/>
<comment data="(blahCOMMENT" uri="test_comment_inject/external.dtd" byte="73" nbytes="14" line="3" col="0"/>
<enddoctype uri="test_comment_inject/test.xml" byte="127" nbytes="1" line="6" col="1"/>
<starttag name="a" uri="test_comment_inject/test.xml" byte="129" nbytes="3" line="7" col="0"/>
<endtag name="a" uri="test_comment_inject/test.xml" byte="132" nbytes="4" line="7" col="3"/>
</document>
```

Note this part of the `xmlwf` output:
```
<comment data="(blahCOMMENT" [...]>
```

**Comment by hartwork** [comment]
Hello @thejh, thanks for the report! :+1: I hope to find spare time for a closer look at this matter soon-ish.

**Comment by RMJ10** [comment]
It looks like all that needs doing is to clear m_tempPool at line 5406 of xmlparse.c, and probably the same at line 5363.  I think all the other code paths are exiting with an error code rather than struggling on, though an unfinished allocation might still cause problems elsewhere.

I'll see if I can turn @thejh 's example into a regression test.

**Comment by hartwork** [comment]
@thejh from your point of view, is there anything needed beyond @RMJ10's pull request #615 to fully fix this issue?

**Comment by thejh** [comment]
After staring at this for the bit, I think it's incomplete. With the fix commit applied, the original testcase behaves correctly:

```
$ expat/xmlwf/xmlwf -n -p -x -m -d test_comment_inject/out test_comment_inject/test.xml && cat test_comment_inject/out/test.xml
<document>
<startdoctype name="foo" uri="test_comment_inject/test.xml" byte="53" nbytes="1" line="2" col="14"/>
<entity name="entp" system="external.dtd" uri="test_comment_inject/test.xml" byte="115" nbytes="0" line="4" col="39"/>
<comment data="COMMENT" uri="test_comment_inject/external.dtd" byte="73" nbytes="14" line="3" col="0"/>
<enddoctype uri="test_comment_inject/test.xml" byte="127" nbytes="1" line="6" col="1"/>
<starttag name="a" uri="test_comment_inject/test.xml" byte="129" nbytes="3" line="7" col="0"/>
<endtag name="a" uri="test_comment_inject/test.xml" byte="132" nbytes="4" line="7" col="3"/>
</document>
```

But if I introduce one more level of indirection, it still goes wrong:
```
$ cat test_comment_inject2/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foo [
  <!ELEMENT foo ANY>
  <!ENTITY % entp SYSTEM "external.dtd">
  <!ENTITY % entp2 SYSTEM "external2.dtd">
  %entp;
]>
<a></a>

$ cat test_comment_inject2/external.dtd
<!ELEMENT barf ANY>
<!ATTLIST barf my_attr (blah|%entp2;a|foo) #REQUIRED>
<!--COMMENT-->
$ cat test_comment_inject2/external2.dtd
%blah;
$ expat/xmlwf/xmlwf -n -p -x -m -d test_comment_inject2/out test_comment_inject2/test.xml && cat test_comment_inject2/out/test.xml
<document>
<startdoctype name="foo" uri="test_comment_inject2/test.xml" byte="53" nbytes="1" line="2" col="14"/>
<entity name="entp" system="external.dtd" uri="test_comment_inject2/test.xml" byte="115" nbytes="0" line="4" col="39"/>
<entity name="entp2" system="external2.dtd" uri="test_comment_inject2/test.xml" byte="158" nbytes="0" line="5" col="41"/>
<comment data="(blahCOMMENT" uri="test_comment_inject2/external.dtd" byte="74" nbytes="14" line="3" col="0"/>
<enddoctype uri="test_comment_inject2/test.xml" byte="170" nbytes="1" line="7" col="1"/>
<starttag name="a" uri="test_comment_inject2/test.xml" byte="172" nbytes="3" line="8" col="0"/>
<endtag name="a" uri="test_comment_inject2/test.xml" byte="175" nbytes="4" line="8" col="3"/>
</document>
$ 
```

I think a more complete (and less complex in terms of possible states) approach would be to move the `poolClear()` call in the `XML_ROLE_REQUIRED_ATTRIBUTE_VALUE` handler down by 2 lines, out of the `if (!dtd->keepProcessing)` clause.

**Comment by hartwork** [comment]
@thejh thanks for your review and feedback! :pray: The patch that I understood you are proposing is this:

```diff
--- a/expat/lib/xmlparse.c
+++ b/expat/lib/xmlparse.c
@@ -4975,10 +4975,10 @@ doProlog(XML_Parser parser, const ENCODING *enc, const char *s, const char *end,
               parser->m_handlerArg, parser->m_declElementType->name,
               parser->m_declAttributeId->name, parser->m_declAttributeType, 0,
               role == XML_ROLE_REQUIRED_ATTRIBUTE_VALUE);
-          poolClear(&parser->m_tempPool);
           handleDefault = XML_FALSE;
         }
       }
+      poolClear(&parser->m_tempPool);
       break;
     case XML_ROLE_DEFAULT_ATTRIBUTE_VALUE:
     case XML_ROLE_FIXED_ATTRIBUTE_VALUE:
```

I confirm that the current patch in #615 leaves the [second scenario with additional nesting](https://github.com/libexpat/libexpat/issues/612#issuecomment-1246812499) unfixed while your proposed patch seems to fix both cases. @RMJ10 what do you think?

**Comment by thejh** [comment]
Yeah, that's the change I was thinking of. (Whoops, I said 2 lines but meant 3...)

**Comment by RMJ10** [comment]
I've no objection to that.  I had wondered about doing it that way, but thought the more specific version was safer.  Clearly I was wrong!

**Comment by hartwork** [comment]
@RMJ10 many thanks for your review and quick response! :+1: 

I have squash-combined all test-related commits from #615 with the fix above as a new PR #645 now. In a way, I'm putting word in your mouth in the PR, in particular with with the commit message and the Google mail for an author for @thejh's commit. If any of that looks wrong please let me know how to adjust and I'll be happy to. What do you think?

**Comment by hartwork** [comment]
@thejh any chance you could have a look at PR #645 today or tomorrow?

**Comment by hartwork** [comment]
@thejh any chance you could have a look at PR #645?

**Comment by hartwork** [comment]
@thejh excellent, thank you!
