### ISSUE TITLE
MinGW DLL name: Inconsistency between CMake and GNU Autotools build systems

### ISSUE THREAD

**Issue by vtorri** [libexpat/libexpat#622]
with autotools: libexpat-1.dll
with cmake: libexpat.dll

**Comment by vtorri** [comment]
you can use something like

```
if (MINGW)
  set_target_properties(libexpat PROPERTIES SUFFIX -${LIBEXPAT_VERSION_MAJOR}.dll)
endif()
```

also maybe something similar on UNIX (.so.1, etc...)

**Comment by hartwork** [comment]
Hi @vtorri I belive this only affects MinGW. I guess we could make CMake append `-<major>` for MinGW but I'm not sure who that will improve things for and who it will worsen things for. What do you think?

**Comment by vtorri** [comment]
this kind of number in the DLL is, imho, important when there is API or ABI breakage, for the DLL to coexist in the same bin/ dir. In that case, there would be libexpat-1.dll and libexpat-2.dll for example

If you don't plan to break libexpat API or ABI, then forget about my comment

**Comment by hartwork** [comment]
There is no plan to break ABI but if there ever is Expat 3 with backwards-incompatible changes, then we'll be in that situation. It would be easy to adjust in CMake, and the changes from PR #608 would allow someone to get the `-<major>` out again, if they need to. I'm currently tending towards getting the two in sync. Let me think about it more.
