### ISSUE TITLE
xmlwf gives bogus 'no element found' error

### ISSUE THREAD

**Issue by archiecobbs** [libexpat/libexpat#63]
Valid XML is declared invalid by `xmlwf` when memory mapped:

    $ xmlwf bigfile.xml
    bigfile.xml:3633808:9687: no element found
    $ xmlwf -r bigfile.xml
    $ cat bigfile.xml | xmlwf
    $

You can access `bigfile.xml` [here](https://s3.amazonaws.com/archie-public/temp/bigfile.xml.gz).

**Comment by hartwork** [comment]
Hi!

I get `access denied (403)` for that download.
On the error, does it happen with both Expat 2.2.0 and 2.2.1?
Also, was `-n` meant to be `-r` to disable memory mapping?

Thanks, Sebastian

**Comment by hartwork** [comment]
> Sorry, permissions were not set right. Please try again.

Download in progres...

> expat version is 2.1.0.

2.1.0? Can you try with 2.2.1?

> And yes I meant `-r` instead of `-n`. Using `-r` I get no error.

Could you extend/adjust the first post in this thread accordingly? I think that would help the ticket for people joining after us.

**Comment by archiecobbs** [comment]
It's not convenient for me to test with 2.2.1 right now, so that may take a while.

If/when I get to it I'll update this ticket. Thanks.

**Comment by hartwork** [comment]
> It's not convenient for me to test with 2.2.1 right now, so that may take a while.

What OS and distribution are you running?

Using the file that you provided and xmlwf of Expat 2.2.1+ I cannot reproduce this issue:
```
# ./xmlwf/xmlwf bigfile.xml ; echo $?
bigfile.xml: file too large for memory-mapping, switching to streaming
0
```

For preparation I did:
```
# git describe --tags
R_2_2_1-20-g85bc132

# ./configure --disable-shared && make clean all check
[..]

# ldd ./xmlwf/xmlwf
        linux-vdso.so.1 (0x00007fff3b3fd000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd841fb4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd84234b000)
```
My current understanding is that it got fixed with the fixes done for #28 that you reported earlier.

**Comment by archiecobbs** [comment]
OK I tested it with the latest in git. Thanks for the build instructions, that helped.

It's fixed in the latest version I built from git:

    $ xmlwf bigfile.xml 
    bigfile.xml:3633808:9687: no element found
    $  ./xmlwf/xmlwf bigfile.xml 
    bigfile.xml: file too large for memory-mapping, switching to streaming
    $

Thanks & sorry for the dup.

**Comment by hartwork** [comment]
No worries, thanks for the update!
