### ISSUE TITLE
Migrate Makefile.in and make-release.sh to GNU Automake?

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#65]
Pros (of using GNU Automake):
* `make dist` out of the box, no more need for hand-made `make-release.sh`
* `make distcheck` out of the box
* Automatic discovery of inter-source-file dependencies
* Option for less verbose builds, e.g. `CC lib/xmlparse.c` rather than the full compile command line
* Adding new source files becomes a bit easier

Cons:
* ???

Side notes:
* We have a few custom targets in `Makefile.in` that need to be copied/migrated, too

Feedback and pull requests welcome, ideally feedback first :)

**Comment by freddrake** [comment]
We initially started using the GNU autotools with a contribution from Greg Stein, who understood them, at least at the time.  I don't think I ever understood them very well, and things certainly decayed as I tried to deal with GNU autotools updates.

If these are still considered best practice for C libraries, I'm all for using them, but we should probably have a section in the contributor's guide on how to deal with updates (how & when, especially).

**Comment by hartwork** [comment]
I'm unsure what updates you refer to. Is this about adding new files? Please elaborate.

**Comment by freddrake** [comment]
Sorry; that was in reference to autotools updates.

**Comment by hartwork** [comment]
Okay. I'm not too afraid of those, personally. Just work :)

**Comment by RMJ10** [comment]
My problem with automake, and indeed libtool, cmake and all these fine systems for making life easier, is that when things go wrong it is very hard to figure out what happened, never mind why.  The sheer incomprehensibility of the system is a very big "con" to me.

**Comment by hartwork** [comment]
I get that but does it apply as much to Automake?

**Comment by RMJ10** [comment]
You're the one who's going to be fighting it :-)

**Comment by hartwork** [comment]
Pull request #118 is related.
