### ISSUE TITLE
CMake & make build vs libexpat version

### ISSUE THREAD

**Issue by Sebultura666** [libexpat/libexpat#679]
Hey dudes, when I try to build libexpat 2.5.0 via CMake + make, I get the "libexpat.so.1.8.10" generated library: am I missing something or shouldn't it be "libexpat.so.2.5.0" instead?

**To reproduce (at the libexpat cloned source code) :**
mkdir Build
cd Build
cmake . ../expat
make

**Comment by hartwork** [comment]
Hi @Sebultura666 ,

those two versions are not in sync and that's correct and intended: they are independent. One could could say that `libexpat.so.1.8.10` is the [soname](https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html#AEN49) of Expat 2.5.0. You can think of the `1.8.10` side as [semver](https://semver.org/) from a time when software versions where far from semver but semver properties were already needed on shared library filename level.

The code that produces `.so.1.8.10` is this:

https://github.com/libexpat/libexpat/blob/0476f9cb841202ab233193e0e022006fd3069ae4/expat/CMakeLists.txt#L439-L447

Changes to the soversion are document in the change log e.g.:

https://github.com/libexpat/libexpat/blob/0476f9cb841202ab233193e0e022006fd3069ae4/expat/Changes#L33-L34

The format used there is the one understood by libtool. If you would like to play with the transformation from `9:10:8` to `1.8.10` live, web tool https://verbump.de/ could be of help.

Does that answer the question?

**Comment by Sebultura666** [comment]
Hi @hartwork,
This makes sense: thanks for the quick reply ( I'm closing the topic)!
