### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [libexpat/libexpat#690]
Would you like to add more error handling for return values from functions like the following?
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [main](https://github.com/libexpat/libexpat/blob/f1a444ef64680ebd4ff89091a2c388cd046ece2d/expat/tests/benchmark/benchmark.c#L101)
* [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [printTabs](https://github.com/libexpat/libexpat/blob/7f7da50d9c7013af6462953c0785253b17051027/expat/gennmtab/gennmtab.c#L399)

**Comment by hartwork** [comment]
Hi @elfring! Regarding these tools, neither gennmtab nor benchmark get installed on user machines.  Regarding the functions, with printf it would depend on the case, with malloc, clean and deliberate pull request would definitely be welcome. What do you think?

**Comment by hartwork** [comment]
It seems like I misread this as an offer to provide pull request. Without a pull request and seemingly little importance, I'll close this as "good enough". If that assessment seems off, please comment or re-open this ticket as needed. Thank you! :pray:

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by hartwork** [comment]
@elfring we have cppcheck for static analysis already today, and there is no end to doing more on static analysis if you have infinite time and volunteers. The question for AOP is either trolling or lack of familiarity with Expat, or I fail to get why you're bringing it up here. In any case it seems out of place in a ticket that is focused on additional handling of errors. I'll leave this closed for now.

**Comment by elfring** [comment]
>The question for AOP is …, or I fail to get why you're bringing it up here.

:thinking: Can you become more aware that [error detection](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Documentation") belongs to known cross-cutting concerns?

**Comment by hartwork** [comment]
@elfring frankly I don't like your tone here. I'll stop here, I don't consider AOP relevant to Expat.

**Comment by elfring** [comment]
:thought_balloon: I am trying to point out that additional methodologies can be helpful.

:eyes: [Some development approaches are worth for another look](https://www.aspectc.org/ "Software development with AspectC++"), aren't they?

**Comment by hartwork** [comment]
> I don't consider AOP relevant to Expat.

@elfring I already answered that. Let's stop here.
