### ISSUE TITLE
XML_Parse() limits its input to 2^31 length

### ISSUE THREAD

**Issue by pointsman** [libexpat/libexpat#691]
From the prototype of XML_Parse (https://libexpat.github.io/doc/api/latest/#XML_Parse) it is clear that the user can only feed an XML string up to 2 GByte length at once to the function.

In the use case "read from file" there is typically already a read loop and XML_Parse() fits nicely.

If the XML data to parse is already a char * from elsewhere it is unnecessary laborious to have to loop over the char * and feed it in chunks < 2^31 bytes to XML_Parse.

Especially since I see no parsing speed degeneration with larger input chunks.

**Comment by hartwork** [comment]
Hi @pointsman I don't see a way to fix this without either breaking API or adding a new function *and* making the required changes under the hood. There is risk and effort involved for something that was good enough for over a decade. I'm afraid we'll have to close this as wontfix. Thanks for your understanding.
