### ISSUE TITLE
Confusing references to travis

### ISSUE THREAD

**Issue by hannob** [libexpat/libexpat#698]
Some of expat's CI logic is in a script called .travis.sh and some of the github workflow files also have this in their description (e.g. linux.yml: "name: Run Linux Travis CI tasks").

However it appears expat hasn't been using Travis CI for quite a while, and all is implemented in Github actions. To avoid confusion I recommend renaming / changing those descriptions. In order to not have that problem again, I would also recommend to use a more generic name (i.e. "Run Linux CI tasks" should be fine, no need to mention which CI tech one is using, the script could be named something like ci.sh or runci.sh), so that problem does not show up again in case at some point github actions is replaced with something else.

**Comment by hartwork** [comment]
It's a leftover from migration that kept failing to make the "needs to be fixed now" bar. There's more in the CI that could be cleaned up.
