### ISSUE TITLE
Add `AM_MAINTAINER_MODE` to `configure.ac`

### ISSUE THREAD

**Issue by zedseven** [libexpat/libexpat#726]
Would it be possible to add `AM_MAINTAINER_MODE` to `configure.ac`?

This disables the reconfigure rules in the generated `Makefile`, which make it so that Make tries to run `autoconf`/`automake` whenever it thinks the files are out of date.

These rules cause problems for end users when they try to use source code that has timestamps updated (like checking out from Git). Make tries to run the `autoconf`/`automake` tools, which most users don't have installed.

I burned 2 hours on this until I found the arcane sequence of files to touch so that it wouldn't think it was out of date, so I would appreciate it if this wasn't required anymore.

References:
- https://stackoverflow.com/a/76166041
- https://stackoverflow.com/a/934087

**Comment by zedseven** [comment]
Hi @hartwork, thank you for your swift reply.

My use case isn't to use the Git repo directly—I'm using `expat-2.5.0.tar.gz` of https://github.com/libexpat/libexpat/releases/tag/R_2_5_0. As part of some internal build automation, this unpacked `tar` archive is committed to another repo along with the necessary build automation to compile it with another build system.

This `tar` archive contains the following files that I had to `touch` in a specific order:
1. `aclocal.m4`
2. `Makefile.in`
3. `configure`
4. `expat_config.h.in`
5. `expat_config.h`

I found that the comparison *seems* to be between `aclocal.m4` and `configure`, and then between `configure` and `expat_config.h.in`/`expat_config.h`. I didn't need to `touch` `configure.ac` at all.

The reason they need to be `touch`ed is because Git doesn't keep the timestamps on the files.

I agree that these files shouldn't be stored in Git in a development environment, but in this case, the entire `tar` is stored as-is.

Personally, I think it should be opt-in to have these timestamp checks since most systems don't have `autoconf`/`automake` installed—that said, even having an opt-out would be much better than having to fiddle with timestamps.

**Comment by hartwork** [comment]
> Personally, I think it should be opt-in to have these timestamp checks since most systems don't have `autoconf`/`automake` installed—that said, even having an opt-out would be much better than having to fiddle with timestamps.

The current default works well during development, but I'll add `AM_MAINTAINER_MODE([enable])` as a pull request in a second…

**Comment by zedseven** [comment]
Thank you!
