### ISSUE TITLE
Provide option to avoid call bcryptprimitives!ProcessPrng rather than rand_s on Windows

### ISSUE THREAD

**Issue by quidity** [libexpat/libexpat#731]
Hello Expat.

Expat is included in Chrome as a dependency of Skia & other things - this means it runs in Chrome's renderer sandbox.

On Windows we're trying to remove DLL dependencies & unnecessary handles from the renderer (see https://crbug.com/74242 and https://docs.google.com/document/d/13n1t5ak0yofzcadQCF7Ew5TewSUkNfQ3n-IYodjeRYc/edit?usp=sharing for our motivation).

expat calls rand_s in some circumstances (https://source.chromium.org/search?q=file:expat%20rand_s&ss=chromium%2Fchromium%2Fsrc) and we'd like to have the option to instead directly call brcryptprimitives!ProcessPrng (https://learn.microsoft.com/en-us/windows/win32/seccng/processprng) as doing so avoids pulling in cryptbase!RtlGenRandom. ProcessPrng backs RtlGenRandom and rand_s on modern versions of Windows so this will not affect the quality of the random numbers provided to expat.

I will shortly make a PR. I anticipate adding an optional buildflag to control which of rand_s or ProcessPrng are called.

**Comment by hartwork** [comment]
Hi @quidity, calling the [`XML_SetHashSalt` function](https://libexpat.github.io/doc/api/latest/#XML_SetHashSalt) with a [value unequal zero](https://github.com/libexpat/libexpat/blob/6a36e138f343192d256a0eace730c94170a8141b/expat/lib/xmlparse.c#L955-L956) should suppress calls to `rand_s` and let you provide raw entropy instead, e.g. by calling `ProcessPrng` outside of Expat. Could you help me understand how calling `XML_SetHashSalt` to pass self-extracted entropy to Expat could or could not solve your problem in detail? What are the qualities that any fix would need to have to be a fix you? I'd like to be sure to understand. Thanks!

**Comment by quidity** [comment]
Great - I think I can use the API you suggested - Thanks for the info!
