### ISSUE TITLE
[Question] How to stop the parser after a certain tag is seen?

### ISSUE THREAD

**Issue by npsables** [libexpat/libexpat#734]
I'm trying to extract some values from XML string and I want to stop the parser after those are extracted. The [document](https://www.xml.com/pub/1999/09/expat/index.html#elementhandler) says:
> For instance, your application may choose to ignore all text not descended from a para element. One way it could do this is to set the character handler when a para start tag is seen, and unset it for the corresponding end tag.

My understanding of this is I can create a way to communicate between handlers so the parser can ignore others' tags. **Instead of ignoring the descendants, how can I stop the parser completely?**

**Comment by hartwork** [comment]
Hi @npsables I think you may be looking for https://libexpat.github.io/doc/api/latest/#XML_StopParser .

**Comment by npsables** [comment]
Thanks a lot, @hartwork, I make it work following your recommend!

Btw, an additional question, do I have to create new **XML_Parser** everytime I have new XML data? Can I reset/reuse the current parser?

**Comment by npsables** [comment]
Close as completed
