### ISSUE TITLE
CMake unconditionally adds -fno-strict-aliasing

### ISSUE THREAD

**Issue by mathstuf** [libexpat/libexpat#74]
This flag only really makes sense on GCC or GCC-like compilers. Its use should be shadowed behind a compiler check. I see that [an issue](https://sourceforge.net/p/expat/bugs/538/) was raised which caused its addition, though I suspect that the core issue should be fixed rather than relying on compiler flags to not make optimizations (e.g., MSVC, Intel, etc. all are still free to make the troublesome assumptions).

**Comment by hartwork** [comment]
Hello Ben,

in discussion with the Pascal — the reporter of the issue you linked to — we decided to go with `-fno-strict-aliasing` in general last time. I'm happy about pull requests addressing the core issue as well as pull request guarding the adding in the CMake build system. (I will not have the resources for much energy this road myself.) We welcome help with CMake in general, e.g. see #43.

Best, Sebastian

**Comment by DerDakon** [comment]
Fixed by #107, can be closed.
