### ISSUE TITLE
Need Information on supported versions

### ISSUE THREAD

**Issue by srikumaran360** [libexpat/libexpat#752]
As the latest version of expat is 2.5.0 as of 22nd September,2023. What are the previous versions of expat that are currently supported and maintained by expat team. Could anyone help me get the list?

**Comment by hartwork** [comment]
Hi @srikumaran360, the latest release 2.5.0 is of "Oct 25, 2022" and it is the only version supported upstream and recommend for use, but the answer depends on what you really mean by "supported". Some [downstreams](https://libexpat.github.io/doc/packages/) backport fixes with known security impact onto older releases, e.g. [Debian does](https://sources.debian.org/patches/expat/). What do you mean by supported and what is your context/environment of use? If any part of a reply would be unfit for writing up here, my e-mail is in my GitHub profile for an alternative mean of contact as needed.

**Comment by hartwork** [comment]
Closing due to no reply for two weeks…
