### ISSUE TITLE
Warning when building with -Wextra without assertions (-DNDEBUG)

### ISSUE THREAD

**Issue by segevfiner** [libexpat/libexpat#76]
```
warning: variable ‘gettimeofday_res’ set but not used [-Wunused-but-set-variable]
```

Due to: [expat/lib/xmlparse.c:815-818](https://github.com/libexpat/libexpat/blob/e72c42eb18ba106b86c953a476a95096156a484b/expat/lib/xmlparse.c#L815-L818).

I would have sent a PR if I was sure how to fix this. We can just ignore it by adding a line like:
```c
(void)gettimeofday_res;
```

But is that what we want to do? It can theoretically still fail even in a build without assertions and we will return stack garbage in that case.

**Comment by hartwork** [comment]
Hi Segev,

so the warning only occurs with `-DNDEBUG`, is that understanding correct?
I would recommend against disabling assertions in production. Do you have a a good reason to do that? is excluding Expat from that an option?
I'm not sure if we want to add extra code to fix `-DNDEBUG` warnings.

Best, Sebastian

**Comment by segevfiner** [comment]
It's actually something I noticed in Python's code base which vendors expat.

cc @haypo

בתאריך 12 ביול' 2017 20:47,‏ "Sebastian Pipping" <notifications@github.com>
כתב:

Hi Segev,

so the warning only occurs with -DNDEBUG, is that understanding correct?
I would recommend against disabling assertions in production. Do you have a
a good reason to do that? is excluding Expat from that an option?
I'm not sure if we want to add extra code to fix -DNDEBUG warnings.

Best, Sebastian

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libexpat/libexpat/issues/76#issuecomment-314845272>,
or mute
the thread

**Comment by hartwork** [comment]
Do they use `-DNDEBUG`?

**Comment by segevfiner** [comment]
Yes. When you don't configure with `--with-pydebug` or `--with-assertions`.

**Comment by hartwork** [comment]
I see. Is that the only warning you get from Expat?

How do you like?:
```
--- a/expat/lib/xmlparse.c
+++ b/expat/lib/xmlparse.c
@@ -815,7 +815,12 @@ gather_time_entropy(void)
   int gettimeofday_res;
 
   gettimeofday_res = gettimeofday(&tv, NULL);
+
+#if defined(NDEBUG)
+  (void)gettimeofday_res;
+#else
   assert (gettimeofday_res == 0);
+#endif  /* defined(NDEBUG) */
 
   /* Microseconds time is <20 bits entropy */
   return tv.tv_usec;
```

**Comment by hartwork** [comment]
I have pushed 1ea1425d15a7bc0e0ed3ef0f66a42a643fbca9a5 now. Good enough?

**Comment by segevfiner** [comment]
Seems to work. 😃

I also looked at CPython's buildbots and saw this in one of them (That's from a PGO build of CPython):
```
/var/lib/buildbot/slaves/enable-optimizations-bot/3.x.gps-debian-profile-opt.nondebug/build/Modules/expat/xmlparse.c: In function ‘appendAttributeValue’:
/var/lib/buildbot/slaves/enable-optimizations-bot/3.x.gps-debian-profile-opt.nondebug/build/Modules/expat/xmlparse.c:5332:40: warning: array subscript is above array bounds [-Warray-bounds]
           if (!poolAppendChar(pool, buf[i]))
                                     ~~~^~~
/var/lib/buildbot/slaves/enable-optimizations-bot/3.x.gps-debian-profile-opt.nondebug/build/Modules/expat/xmlparse.c:461:27: note: in definition of macro ‘poolAppendChar’
    : ((*((pool)->ptr)++ = c), 1))
                           ^
/var/lib/buildbot/slaves/enable-optimizations-bot/3.x.gps-debian-profile-opt.nondebug/build/Modules/expat/xmlparse.c:5332:40: warning: array subscript is above array bounds [-Warray-bounds]
           if (!poolAppendChar(pool, buf[i]))
                                     ~~~^~~
/var/lib/buildbot/slaves/enable-optimizations-bot/3.x.gps-debian-profile-opt.nondebug/build/Modules/expat/xmlparse.c:461:27: note: in definition of macro ‘poolAppendChar’
    : ((*((pool)->ptr)++ = c), 1))
                           ^
```

I'm not sure if this one is real or not...

**Comment by hartwork** [comment]
Thanks!

I made a new ticket #78 from your compiler output above.
