### ISSUE TITLE
how to parse an xml with some special character

### ISSUE THREAD

**Issue by lanewei120** [libexpat/libexpat#767]
I have an xml file like this:
```
<?xml version='1.0' encoding='UTF-8'?>
<model xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06" xml:lang="en-US" requiredextensions="p">
 <metadata name="Description">test stringend;</metadata>
 </model>
```

when use following functions to do the parsing:
XML_ParserCreate
XML_SetUserData
XML_SetElementHandler
XML_SetCharacterDataHandler
XML_Parse

XML_Parse returned error, and show "Error (not well-formed (invalid token)) while parsing 'text.xml' at line 3"
I found there is a special character '' following "test string"

is there a way to parse it successfully or just ignore this char
and go on the remaing parsing?

thanks

**Comment by lanewei120** [comment]
> I'm not sure what that codepoint is that we are dealing with here precisely — maybe https://codepoints.net/U+FFFD ?
> 
> The XML spec dictates that XML parsers must not ignore well-formedness errors and hence Expat does not offer ignoring errors like this one in order to be in line with the spec.
> 
> Also please note that Expat implements XML 1.0 Fourth Edition so parse errors from characters only added to XML 1.0 in the Fifth Edition are to be expected and that would be known years-open issue #767.
> 
> I will close the question as answered but if I missed anything in my reply we can sure re-open this issue.

@hartwork

 thanks for the fast reply

could you also give some suggestion to process such an xml?
my requirement is just ignore the error line, and parse other lines

**Comment by hartwork** [comment]
> could you also give some suggestion to process such an xml? my requirement is just ignore the error line, and parse other lines

@lanewei120 either fixing the source that produces the malformed XML or doing pre-processing prior to passing to Expat for parsing. Depends on your environment.

**Comment by lanewei120** [comment]
> > could you also give some suggestion to process such an xml? my requirement is just ignore the error line, and parse other lines
> 
> @lanewei120 either fixing the source that produces the malformed XML or doing pre-processing prior to passing to Expat for parsing. Depends on your environment.

@hartwork 

thanks for the suggestion

I am also curious why the character with ascii code '02' can not be recoganized by libexpat
as it uses utf-8 encoding
'02' should be a valid character also

**Comment by hartwork** [comment]
> I am also curious why the character with ascii code '02' can not be recoganized by libexpat as it uses utf-8 encoding '02' should be a valid character also

@lanewei120 if you mean https://codepoints.net/U+0002 I would want to ask back why you think it would be allowed in well-formed XML 1.0 Fourth Edition.
