### ISSUE TITLE
[2.2.1] warning: array subscript is above array bounds [-Warray-bounds]

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#78]
From @segevfiner's post [here](https://github.com/libexpat/libexpat/issues/76#issuecomment-314896370):

```
[..]/expat/xmlparse.c: In function ‘appendAttributeValue’:
[..]/expat/xmlparse.c:5332:40: warning: array subscript is above array bounds [-Warray-bounds]
           if (!poolAppendChar(pool, buf[i]))
                                     ~~~^~~
[..]/expat/xmlparse.c:461:27: note: in definition of macro ‘poolAppendChar’
    : ((*((pool)->ptr)++ = c), 1))
                           ^
[..]/expat/xmlparse.c:5332:40: warning: array subscript is above array bounds [-Warray-bounds]
           if (!poolAppendChar(pool, buf[i]))
                                     ~~~^~~
[..]/expat/xmlparse.c:461:27: note: in definition of macro ‘poolAppendChar’
    : ((*((pool)->ptr)++ = c), 1))
                           ^
```

**Comment by hartwork** [comment]
The relevant code is:
```
        XML_Char buf[XML_ENCODE_MAX];
[..]
        n = XmlEncode(n, (ICHAR *)buf);
        if (!n) {
          if (enc == encoding)
            eventPtr = ptr;
          return XML_ERROR_BAD_CHAR_REF;
        }
        for (i = 0; i < n; i++) {
          if (!poolAppendChar(pool, buf[i]))
            return XML_ERROR_NO_MEMORY;
        }
```

After a close look:
* `XML_ENCODE_MAX` is defined as `XML_UTF8_ENCODE_MAX` (=4) (or `XML_UTF16_ENCODE_MAX` (=2) if `XML_UNICODE` is defined)
* `XmlEncode` is defined as `XmlUtf8Encode` (returns 0..4) (or `XmlUtf16Encode` (return 0..2)  if `XML_UNICODE` is defined).
* `i < n` with `n` returned `XmlEncode` ensures that `buf[i]` is within bounds.

My conclusion: False positive.

**Comment by hartwork** [comment]
PS: @segevfiner if you have ideas on how to silence this warning, please let me know. Also, if you can share the compiler in use and the precise flags, I could play with it a bit more myself. (I don't get these warnings currently.)

**Comment by segevfiner** [comment]
I don't know the exact details, I only saw it in CPython's buildbot when I
looked to see if there are any other warnings from expat.

The builder that triggers this is this one:
http://buildbot.python.org/all/builders/AMD64%20Debian%20PGO%203.x which
seems to build CPython's master branch with PGO. I'm not sure which Debian
is it, and I'm not sure who to ask. It seems to happen only in the PGO
rebuild step too.

בתאריך 13 ביול' 2017 23:39,‏ "Sebastian Pipping" <notifications@github.com>
כתב:
