### ISSUE TITLE
macOS pre-10.7/Lion high quality entropy

### ISSUE THREAD

**Issue by gnw3** [libexpat/libexpat#81]
Snow Leopard has `arc4random` but not `arc4random_buf`.   See: [cocoa-arc4random-os-x-10-6](https://stackoverflow.com/questions/8044332/cocoa-arc4random-os-x-10-6).  An example from [curl](https://curl.haxx.se/mail/lib-2012-07/att-0084/0001-Re-wrote-Curl_darwinssl_random-to-not-use-arc4random.patch).

**Comment by hartwork** [comment]
Hi!

Thanks for bringing this to my attention. Given auto-updates on OS X and OS X 10.7 released in 2011 — where is pre-10.7 in use today? How did you run into the issue?

@nickzman, is [0001-Re-wrote-Curl_darwinssl_random-to-not-use-arc4random.patch](https://curl.haxx.se/mail/lib-2012-07/att-0084/0001-Re-wrote-Curl_darwinssl_random-to-not-use-arc4random.patch) yours? Can we use that code under the MIT license with Expat?

Best, Sebastian

**Comment by nickzman** [comment]
You would be amazed; Snow Leopard is Apple's XP. It was the last macOS release that supported PowerPC apps, the last macOS release to use the 2000s-era UI design, and the last macOS release to have a really powerful server GUI (Lion's was dumbed down quite a bit, while Mountain Lion's was better).

That code was merged into curl years ago. Do with it what you will.

**Comment by hartwork** [comment]
I see!

I made #84 now. It would be awesome to have some review and testing on an actual pre-10.7 macOS system. Thanks in advance!
