### ISSUE TITLE
[2.6.0] `./configure --without-docbook && make clean all` fails with `xmlwf.xml: command not found`

### ISSUE THREAD

**Issue by kraptor** [libexpat/libexpat#821]
**Related**: https://github.com/libexpat/libexpat/issues/253

This happens when running the tests if `make check` is ran.

After a bisect, this is the offending change: https://github.com/libexpat/libexpat/commit/7384c88f9aa7dd49f22ae08f2a65c57b5dda2f9e

Reverting the change fixes the error. It seems to me the lack of a pre-renderered xmlwf.1 file sets WITH_DOCBOOK to true even if --without-docbook is specified (or if the detection doesn't find a valid docwhatever executable that option is looking for).

**Reasoning:**
This recent change breaks tests when docbook is not present, as the generated `docs/Makefile` tries to expand `DOCBOOK_TO_MAN` (which ends up empty) and tries to execute the xml directly when generating the manpage.

**Error output:**
```
[   50s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/expat-2.6.0/xmlwf'
[   50s] Making all in doc
[   50s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/expat-2.6.0/doc'
[   50s] rm -f xmlwf.1
[   50s] xmlwf.xml
[   50s] /usr/bin/bash: line 1: xmlwf.xml: command not found
[   50s] make[2]: *** [Makefile:606: xmlwf.1] Error 127
[   50s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/expat-2.6.0/doc'
[   50s] make[1]: *** [Makefile:650: all-recursive] Error 1
[   50s] make: *** [Makefile:509: all] Error 2
```

**Comment by hartwork** [comment]
Hi @kraptor,

I tried to reproduce the issue but I don#t get the error, neither from the release tarball (with xmlwf.1 present) not with a Git clone (with the file absent):

### `make dist` tarball
```
cd "$(mktemp -d)" && wget https://github.com/libexpat/libexpat/releases/download/R_2_6_0/expat-2.6.0.tar.xz && tar xf expat-2.6.0.tar.xz && cd expat-2.6.0 && ./configure --without-docbook && make all check
```

### Git clone
```
cd "$(mktemp -d)" && git clone --depth 1 --branch R_2_6_0 https://github.com/libexpat/libexpat && cd libexpat/expat && ./buildconf.sh && ./configure --without-docbook && make all check
```

For `DOCBOOK_TO_MAN` to be expanded in `doc/Makefile(.am)`, it would take
- a) xmlwf.1 absent
- b) (xmlwf.1 mis-located or not found)
- c) xmlwf.1 less recent than xmlwf.xml

I'll need your help understanding how any of that would be the case. Any ideas?
In particular, is there anything that makes assumption…

> This relies on file xmlwf.1 being at least as recent as its source file xmlwf.xml.

…violated in your environment? 

PS: Which Linux distro is this about?

**Comment by kraptor** [comment]
Distro: openSUSE.

Let me prepare a failing build in openSUSE Open Build Service so you can see the full trace. We are using the same tarball as in your `make dist` example.

**Comment by kraptor** [comment]
Here you go:
* [x86_64 build failing](https://build.opensuse.org/package/live_build_log/home:david.anes:expat_build/expat/openSUSE_Factory/x86_64) [[full trace](https://build.opensuse.org/build/home:david.anes:expat_build/openSUSE_Factory/x86_64/expat/_log)]

Let me know if you can't acces any of these links and I attach the files here.

We are using configure with:
```
%configure \
  --disable-silent-rules \
  --docdir="%{_docdir}/%{name}" \
  --disable-static \
  --without-docbook
```

Then we run `make` (`%make_build` expands basically to `make -jN`) and `make check` (`%makebuild check`). The SPEC file is quite barebones, nothing fancy there.

**Comment by kraptor** [comment]
Uhm, I noticed something fishy... let me investigate and I'll come back to you asap.

**Comment by hartwork** [comment]
> Uhm, I noticed something fishy... let me investigate and I'll come back to you asap.

@kraptor thanks!

> [The SPEC file](https://build.opensuse.org/package/view_file/home:david.anes:expat_build/expat/expat.spec?expand=1) is quite barebones, nothing fancy there.

One a side note, I had a quick look and a few things caught my eye as not right with 2.6.0 in SUSE:
- `rm -f examples/*.dsp` can be dropped, files are long gone
- `chmod 0644 examples/elements.c` and related comment can can be dropped, long fixed upstream
- file `doc/ok.min.css`needs to be copied since 2.4.0 to make `doc/reference.html` look right
- example file `examples/element_declarations.c` from >=2.6.0 is not copied, so it will be missing

**Comment by kraptor** [comment]
Ok, what I noticed:

Does this work for you?

```
cd "$(mktemp -d)" && wget https://github.com/libexpat/libexpat/releases/download/R_2_6_0/expat-2.6.0.tar.xz && tar xf expat-2.6.0.tar.xz && cd expat-2.6.0 && ./configure --without-docbook && make clean && make
```

It seems that a `make clean`, removes the file then the detection gets confused (there is no compiled man file `xmlwf.1` now) and at the same time `DOCBOOK_TO_MAN` is empty, so the build fails. I think this is a corner case of the side-effect of RPM expanded macros being 'executed' regardless of they are commented out or protected by %if (so that corner case also made me realize there are a few other non-related issues to fix on our side).

In any case, is not unrealistic that someone runs a `make clean` and then hits this issue trying to rebuild again from source. Not sure how to fix this.

> One a side note, I had a quick look and a few things caught my eye as not right with 2.6.0 in SUSE:
> 
>     * `rm -f examples/*.dsp` can be dropped, files are long gone
> 
>     * `chmod 0644 examples/elements.c` and related comment can can be dropped, long fixed upstream
> 
>     * file `doc/ok.min.css`needs to be copied since 2.4.0 to make `doc/reference.html` look right
> 
>     * example file `examples/element_declarations.c` from >=2.6.0 is not copied, so it will be missing

Thanks for the review!! This spec file has been long inherited by several people, I can clean all that and fix some other things I noticed not related to topic.

**Comment by hartwork** [comment]
> Ok, what I noticed:
> 
> Does this work for you?
> 
> ```
> cd "$(mktemp -d)" && wget https://github.com/libexpat/libexpat/releases/download/R_2_6_0/expat-2.6.0.tar.xz && tar xf expat-2.6.0.tar.xz && cd expat-2.6.0 && ./configure --without-docbook && make clean && make
> ```
> 
> It seems that a `make clean`, removes the file then the detection gets confused (there is no compiled man file `xmlwf.1` now) and at the same time `DOCBOOK_TO_MAN` is empty, so the build fails. I think this is a corner case of the side-effect of RPM expanded macros being 'executed' regardless if they are commented out or protected by %if (so that corner case also made me realize there are a few other non-related issues to fix on our side).
> 
> In any case, is not unrealistic that someone runs a `make clean` and then hits this issue trying to rebuild again from source. Not sure how to fix this.

@kraptor confirmed, that's it, fails for me too :+1: 

A workaround could be to move `xmlwf.1` somewhere before cleaning and move it back after, definitely not a fix.
I'll need to think about a better clean fix, ideas welcome. Maybe we can adjust `clean-local-check` some clean way to not delete the file when shipped. I have an idea for a new Automake conditional, but it needs more consideration.

> > One a side note, I had a quick look and a few things caught my eye as not right with 2.6.0 in SUSE:
> >
> > * `rm -f examples/*.dsp` can be dropped, files are long gone
> > 
> > * `chmod 0644 examples/elements.c` and related comment can can be dropped, long fixed upstream
> > 
> > * file `doc/ok.min.css`needs to be copied since 2.4.0 to make `doc/reference.html` look right
> > 
> > * example file `examples/element_declarations.c` from >=2.6.0 is not copied, so it will be missing
> >
> 
> Thanks for the review!! This spec file has been long inherited by several people, I can clean all that and fix some other things I noticed not related to the current topic.

Cool!

`expat.keyring` also needs a refresh if still used, a quick check shows it's an expired version:

```
# wget -q -O- https://build.opensuse.org/package/view_file/home:david.anes:expat_build/expat/expat.keyring | html2text | sed -n '23,267p' | gpg --show-keys
pub   rsa4096 2019-05-09 [SC] [expired: 2023-01-27]
      3176EF7DB2367F1FCA4F306B1F9B0E909AF37285
uid                      Sebastian Pipping <sping@gentoo.org>
sub   rsa4096 2019-05-09 [E] [expired: 2023-01-27]
sub   rsa4096 2019-05-09 [S] [expired: 2023-01-27]

gpg: WARNING: No valid encryption subkey left over.
```

PS: I'd love to know how download raw content for `expat.keyring` and avoid the `html2text | sed -n '23,267p'` stunt above, seems impossible to find using Google or in the OBS UI. Any ideas?

**Comment by kraptor** [comment]
> A workaround could be to move `xmlwf.1` somewhere before cleaning and move it back after, definitely not a fix.

Exactly the fix I just implemented :)

> I'll need to think about a better clean fix, ideas welcome.

I think the simplest way would be storing that file in `doc/man/` instead (wouldn't hurt, I guess). During the build process if `DOCBOOK_TO_MAN` is empty, just copy the file to `/doc` and procedd, else just proceed and generate it. Unfortunately I'm far from being happy comfortable with Automake so I'm not sure if this could be a solution.

> `expat.keyring` also needs a refresh if still used, a quick check shows it's an expired version:

That's easy. I can update it 💪🏼 Is there a URL I can pull the keyring automatically? That will make the process simpler on our side.

> I'd love to know how download raw content for `expat.keyring` and avoid the `html2text | sed -n '23,267p'` stunt above, seems impossible to find using Google or in the OBS UI

From OBS, just get the link from the "download sign" next to the file: ![image](https://github.com/libexpat/libexpat/assets/7249728/1e835814-9d50-4f54-87f3-1f12a04b45f2) 

Then you'll get an URL similar to [this one ](https://build.opensuse.org/source/home:david.anes:expat_build/expat/expat.keyring?rev=d506468f916ceff71b973eedf13c297c), which AFAIK, can be directly downloaded.

**Comment by hartwork** [comment]
> > A workaround could be to move `xmlwf.1` somewhere before cleaning and move it back after, definitely not a fix.
> 
> Exactly the fix I just implemented :)

@kraptor :+1: 

> 
> > I'll need to think about a better clean fix, ideas welcome.
> 
> I think the simplest way would be storing that file in `doc/man/` instead (wouldn't hurt, I guess). During the build process if `DOCBOOK_TO_MAN` is empty, just copy the file to `/doc` and procedd, else just proceed and generate it. Unfortunately I'm far from being happy comfortable with Automake so I'm not sure if this could be a solution.

I'll sleep over it. Could take a few days, this week is a bit packed.

> > `expat.keyring` also needs a refresh if still used, a quick check shows it's an expired version:
> 
> That's easy. I can update it 💪🏼 Is there a URL I can pull the keyring automatically? That will make the process simpler on our side.

There are three places I keep the public key updated as of now, the list is at https://github.com/libexpat/libexpat/issues/537#issuecomment-1003796884 . Now sure how stable these services with regard to integration in a build pipeline.

> > I'd love to know how download raw content for `expat.keyring` and avoid the `html2text | sed -n '23,267p'` stunt above, seems impossible to find using Google or in the OBS UI
> 
> From OBS, just get the link from the "download sign" next to the file: ![image](https://private-user-images.githubusercontent.com/7249728/304216731-1e835814-9d50-4f54-87f3-1f12a04b45f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NzA4NjEsIm5iZiI6MTcwNzc3MDU2MSwicGF0aCI6Ii83MjQ5NzI4LzMwNDIxNjczMS0xZTgzNTgxNC05ZDUwLTRmNTQtODdmMy0xZjEyYTA0YjQ1ZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMjA0MjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIyYjkzMjFmNGUxY2U1NjgwZDllM2YwYmVhZTlmYWE4NWFhMzk0NTQyNDAwZDliNGVjN2NjMWRlODgwYTFhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lRvN3Quf8rZ8cMT5a7BqwDmDiFn13yuDLsrDNNZo1ms)
> 
> Then you'll get an URL similar to [this one ](https://build.opensuse.org/source/home:david.anes:expat_build/expat/expat.keyring?rev=d506468f916ceff71b973eedf13c297c), which AFAIK, can be directly downloaded.

Could it be that both of these are available to logged-in users only? I don't see the icon and wget says "Username/Password Authentication Failed".

**Comment by kraptor** [comment]
> I'll sleep over it. Could take a few days, this week is a bit packed.

No pressure. I really  appreciate your work and responsiveness. It's awesome to have upstream developers like you.

> There are three places I keep the public key updated as of now, the list is at [#537 (comment)](https://github.com/libexpat/libexpat/issues/537#issuecomment-1003796884) . Now sure how stable these services with regard to integration in a build pipeline.

This is the most ugly thing I wrote this week 🤦🏼 
```
gpg --no-default-keyring --keyring /tmp/keyring.gpg --keyserver keyserver.ubuntu.com --recv-key 1F9B0E909AF37285 && gpg --no-default-keyring --keyring /tmp/keyring.gpg --output expat.keyring --export -a && rm /tmp/keyring.gpg
```

> Could it be that both of these are available to logged-in users only?

Seems so... we've got a lot of users abusing OBS lately and it seems it's been restricted.

Let me know if there is anything else I can do on my side and I'll happily help.

**Comment by hartwork** [comment]
> > I'll sleep over it. Could take a few days, this week is a bit packed.
> 
> No pressure. I really appreciate your work and responsiveness. It's awesome to have upstream developers like you.

@kraptor thanks! :pray: 


> > Could it be that both of these are available to logged-in users only?
> 
> Seems so... we've got a lot of users abusing OBS lately and it seems it's been restricted.
> 
> Let me know if there is anything else I can do on my side and I'll happily help.

Not at the moment, thanks, I was just curious how to resolve that hack if possible, and learn for the next case like it.

**Comment by hartwork** [comment]
@kraptor I just pushed a first draft pull request #824 on the topic. Please feel invited to play with it.

**Comment by hartwork** [comment]
@kraptor thanks!

**Comment by hartwork** [comment]
@kraptor PS: I should mention that [`buildconf.sh`](https://github.com/libexpat/libexpat/blob/master/expat/buildconf.sh) will be needed instead of plain `autoreconf`, to not break `expat_config.h.in` in the process.

**Comment by kraptor** [comment]
Testing right now...

**Comment by kraptor** [comment]
Everything seems fine. Should be included soon in openSUSE: https://build.opensuse.org/request/show/1147980

Thanks!

**Comment by hartwork** [comment]
@kraptor cool, thanks for testing and the feedback! I will merge now. Maybe I can make the configure script detect and reject lack of using `buildconf.sh` (or its effect precisely) by accident also, will see.
