### ISSUE TITLE
v2.6.0 - missing #define XML_GE in to expat\lib\xmlparse.c(69,1)

### ISSUE THREAD

**Issue by VictorVG** [libexpat/libexpat#822]
v2.6.0 - missing #define XML_GE in to expat\lib\xmlparse.c(69,1) then have link error in to VC++2019 v16.11.33 and other project can't build.

Fix is simple - add string

`#define XML_GE 1`

in to expat\lib\xmlparse.c(68,1) and build is success.

**Comment by hartwork** [comment]
@VictorVG I'm reading that as "problem solved" and hence close the issue. We can re-open as needed.
