### ISSUE TITLE
Test failures for 2.6.0 in conda-forge - timing expectations too tight?

### ISSUE THREAD

**Issue by h-vetinari** [libexpat/libexpat#835]
Hey there!

I help maintain packages in [conda-forge](https://conda-forge.org/), a pretty large ecosystem for Python, R, scientific computing, etc. We essentially do binary redistribution, but with tightly controlled metadata to ensure each environment uses libraries with a consistent ABI.

While building https://github.com/conda-forge/expat-feedstock/pull/43, we do run the test suite (where possible), and I'm getting the following errors on linux (x64, aarch64, ppc64le), though not on osx-64 or win-64:
```
=======================================
   expat 2.6.0: tests/test-suite.log
=======================================

# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: runtests
==============

ERROR: check failed: taken > 0
ERROR: check failed: taken > 0
Expat version: expat_2.6.0
FAIL [chunksize=4 deferral=1]: test_big_tokens_take_linear_time (max_slowdown=15 text="<a>aaaaaa</a>" at basic_tests.c:5293)
FAIL [chunksize=5 deferral=1]: test_big_tokens_take_linear_time (max_slowdown=15 text="<a>aaaaaa</a>" at basic_tests.c:5293)
99%: Checks: 4320, Failed: 2
FAIL runtests (exit status: 1)

FAIL: runtests_cxx
==================

ERROR: check failed: taken > 0
Expat version: expat_2.6.0
FAIL [chunksize=0 deferral=1]: test_big_tokens_take_linear_time (max_slowdown=15 text="<a>aaaaaa</a>" at basic_tests.c:5293)
99%: Checks: 4320, Failed: 1
FAIL runtests_cxx (exit status: 1)
```

Going purely by the name of the test `test_big_tokens_take_linear_time`, it's possible that our CI is just so puny (we run on the freely available azure pipeline agents, which aren't very powerful) that this violates some timing expectations? Another argument in favour of this is that the failures have been flaky - sometimes there, sometimes not - but happen >75% of the time.

If so, should we just skip that test?

**Comment by hartwork** [comment]
Hi @h-vetinari,

sorry for the inconvenience. This is fixed by pull request #817 and if things go as planned, I will release Expat 2.6.1 #832 with that fix tomorrow in the UTC+1 evening.

CC #825 #827 #830
