### ISSUE TITLE
ClusterFuzz finding 66812

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#839]
# Issue

This is the public side of soon-public (access protected) oss-fuzz Expat finding:
[Issue 66812: expat:xml_parse_fuzzer_UTF-16: Timeout in xml_parse_fuzzer_UTF-16](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66812).

The three key (access protected) contained links are:

- Detailed Report: https://oss-fuzz.com/testcase?key=5187173185814528
- Regressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_expat&range=202401100604:202401110602
- Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5187173185814528

The reproducer (original attached as file [clusterfuzz-testcase-minimized-xml_parse_fuzzer_UTF-16-5187173185814528-timeout-original.xml.txt](https://github.com/libexpat/libexpat/files/14502184/clusterfuzz-testcase-minimized-xml_parse_fuzzer_UTF-16-5187173185814528-timeout-original.xml.txt)) is essentially this two-file case:

File `one.xml`:
```xml
<!DOCTYPE doc SYSTEM "two.dtd">
<doc>&g1;</doc>
```

File `two.dtd`:
```xml
<!ENTITY % p1 '%p1'>
<!ENTITY g1 '%p1;'>
```

The original's SHA245 sum is `6b870c78cff9efe41f1060277f434da98b9f78e9159baf4cb95f034e890ac087`.

The regression link effectively links to https://github.com/libexpat/libexpat/compare/be47f6d5e871382dc2ab783a9df416ec4370074e...716fd10bd461be13c1f67ab11d96ca16a9a202ab (which makes good sense since these changes increase fuzzing coverage).

# Analysis

[ClusterFuzz](https://google.github.io/clusterfuzz/) uncovered two things at once here:

- Direct recursion (`a -> a` in contrast to indirect recursion `a -> b -> a`) of parameter entities (reference syntax `%name;`) was previously not detected in the [external subset](https://www.w3.org/TR/2006/REC-xml-20060816/#ExtSubset) — file `two.dtd` in the example above) — but it [is forbidden by the XML spec](https://www.w3.org/TR/2006/REC-xml-20060816/#norecursion) and was also causing undefined behavior at runtime.
  ```console
  # ./fuzz/xml_parse_fuzzer_UTF-8 [..]/clusterfuzz-testcase-minimized-xml_parse_fuzzer_UTF-16-5187173185814528-timeout-original.xml.txt
  INFO: Running with entropic power schedule (0xFF, 100).
  INFO: Seed: 3441536382
  INFO: Loaded 1 modules   (21351 inline 8-bit counters): 21351 [0x558df02c6000, 0x558df02cb367), 
  INFO: Loaded 1 PC tables (21351 PCs): 21351 [0x558df02cb368,0x558df031e9d8), 
  ./fuzz/xml_parse_fuzzer_UTF-8: Running 1 inputs 1 time(s) each.
  Running: [..]/clusterfuzz-testcase-minimized-xml_parse_fuzzer_UTF-16-5187173185814528-timeout-original.xml.txt
  [..]/expat/lib/xmlparse.c:6273:46: runtime error: applying zero offset to null pointer
  SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior [..]/expat/lib/xmlparse.c:6273:46 in 
  ```  
  Pull request #841 addresses that problem.
- The way that the fuzzing code uses external parsers (created via function [`XML_ExternalEntityParserCreate`](https://libexpat.github.io/doc/api/latest/#XML_ExternalEntityParserCreate)) caused a timeout revealing that due to the lack of any direct input bytes from the parent parser, the amplification ratio calculated by `accountingGetCurrentAmplification` was constantly reported as 1.0 and hence had little chance of stopping billion laughs attacks in practice. Pull request #842 addresses that problem.

Two related side notes:
- [ClusterFuzz](https://google.github.io/clusterfuzz/) leaked part of this finding — the recursion aspect — to the public corpus a few days ago as case `f9b6ba558667913f4554395e039c01f6d8217b43` that later disappeared from the public corpus again.
- Statement…
  
  > If the same entity is declared more than once, the _first_ declaration encountered is binding;

  …in [section 4.2 Entity Declarations](https://www.w3.org/TR/2006/REC-xml-20060816/#sec-entity-decl) of the XML spec is worth noting, emphasis mine.

CC @catenacyber @RMJ10 @Snild-Sony

**Comment by Snild-Sony** [comment]
> [ClusterFuzz](https://google.github.io/clusterfuzz/) leaked part of this finding — the recursion aspect — to the public corpus a few days ago as case `f9b6ba558667913f4554395e039c01f6d8217b43` that later disappeared from the public corpus again.

...which made for a very confusing "regression" in CI runs for an innocent PR. :)

**Comment by hartwork** [comment]
> > [ClusterFuzz](https://google.github.io/clusterfuzz/) leaked part of this finding — the recursion aspect — to the public corpus a few days ago as case `f9b6ba558667913f4554395e039c01f6d8217b43` that later disappeared from the public corpus again.
> 
> ...which made for a very confusing "regression" in CI runs for an innocent PR. :)

Indeed. I had to disable the [fuzzing regression testing wokflow](https://github.com/libexpat/libexpat/actions/workflows/fuzzing.yml) altogether because of that. Would be great if that leak was human- or machine-made.

**Comment by hartwork** [comment]
> > I had to disable the [fuzzing regression testing workflow](https://github.com/libexpat/libexpat/actions/workflows/fuzzing.yml) temporarily because of that.

FYI I re-enabled that workflow after merge of #841 now.

**Comment by PshySimon** [comment]
Sorry to bother you, I'm a bit confused about this test case. 
      {"<!ENTITY % p1 '%p1;'>"
       "<!ENTITY % p1 'first declaration wins'>",
       XML_STATUS_ERROR},
      {"<!ENTITY % p1 'first declaration wins'>"
       "<!ENTITY % p1 '%p1;'>",
       XML_STATUS_OK}

I can't see any difference between these two cases, why do they have different results?

**Comment by Snild-Sony** [comment]
I believe this is what @hartwork was explaining with this quote above:

> * Statement…
>   > If the same entity is declared more than once, the _first_ declaration encountered is binding;
>
>   …in [section 4.2 Entity Declarations](https://www.w3.org/TR/2006/REC-xml-20060816/#sec-entity-decl) of the XML spec is worth noting, emphasis mine.

The full sentence makes it a little clearer:

> If the same entity is declared more than once, the _first_ declaration encountered is binding;at user option, an XML processor `may` issue a warning if entities are declared multiple times.

So, the test added in #841 says:

* `<!ENTITY % p1 '%p1;'>` is bad.
* `<!ENTITY % p1 '%p1;'><!ENTITY % p1 'first declaration wins'>` is bad, because the recursive declaration comes first.
* `<!ENTITY % p1 'first declaration wins'><!ENTITY % p1 '%p1;'>` is fine, because the first declaration is OK and the second one can be (and, I'm guessing, _is_) ignored.

**Comment by PshySimon** [comment]
Oh, I understand now. Thank you for your explanation.

**Comment by hartwork** [comment]
@Snild-Sony well said, thank you!
