### ISSUE TITLE
Conda install version of libexpat 2.6.1 for windows does not include DLL. 

### ISSUE THREAD

**Issue by imcslatte** [libexpat/libexpat#844]
I'm getting the following message when creating a new conda environment  with the latest version of libexpat:
(base) PS C:\Users\Eli Hunter> conda create --name cloud python=3.12
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\work\miniconda3\envs\cloud

  added / updated specs:
    - python=3.12

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-hcfcfb64_5
  ca-certificates    conda-forge/win-64::ca-certificates-2024.2.2-h56e8100_0
  libexpat           conda-forge/win-64::libexpat-2.6.1-h63175ca_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libsqlite          conda-forge/win-64::libsqlite-3.45.1-hcfcfb64_0
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_5
  openssl            conda-forge/win-64::openssl-3.2.1-hcfcfb64_0
  pip                conda-forge/noarch::pip-24.0-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.12.2-h2628c8c_0_cpython
  setuptools         conda-forge/noarch::setuptools-69.1.1-pyhd8ed1ab_0
  tk                 conda-forge/win-64::tk-8.6.13-h5226925_1
  tzdata             conda-forge/noarch::tzdata-2024a-h0c530f3_0
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.3-hcf57466_18
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.38.33130-h82b7239_18
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.38.33130-hcb4865c_18
  wheel              conda-forge/noarch::wheel-0.42.0-pyhd8ed1ab_0
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0

Proceed ([y]/n)? y

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for libexpat located at C:\work\miniconda3\pkgs\libexpat-2.6.1-h63175ca_0
appears to be corrupted. The path 'Library/bin/libexpat.dll'
specified in the package manifest cannot be found.

I verified the DLLL was missing.  

I re-installed version 2.5.0 and the dll downloaded and installed. 

conda version 24.1.2
python version 3.12

Eli

**Comment by hartwork** [comment]
Hi @imcslatte, you have have come to libexpat upstream, this is not conda-forge. Please take your issue to the right place, to conda-forge, closing…

**Comment by samuelchodur** [comment]
The file is not missing from the conda package, but `Library/bin/expat.dll` is seemingly being flagged by my anti-virus software and being automatically deleted. This issue started with version 2.6.1.

**Comment by hartwork** [comment]
@imcslatte @samuelchodur the official release binary packages both do contain file `libexpat.dll`:

```console
# cd "$(mktemp -d)"
# wget https://github.com/libexpat/libexpat/releases/download/R_2_6_1/expat-win32bin-2.6.1.zip
# unzip -l expat-win32bin-2.6.1.zip | grep -F .dll
   551936  02-28-2024 23:47   Bin/libexpat.dll
   556032  02-28-2024 23:51   Bin/libexpatw.dll
# wget https://github.com/libexpat/libexpat/releases/download/R_2_6_1/expat-win32bin-2.6.1.exe
# innoextract -e expat-win32bin-2.6.1.exe |& grep -F .dll
 - "app/Bin/libexpat.dll"
 - "app/Bin/libexpatw.dll"
```

And VirusTotal has [0 complaints](https://www.virustotal.com/gui/file/29ad9936798df1588a59d10858e705fb3f5ab6c8ccbcf7926332a8cb58d02204) about libexpat.dll with SHA256 checksum `29ad9936798df1588a59d10858e705fb3f5ab6c8ccbcf7926332a8cb58d02204` as of the moment.

I don't see any problem here that would be an Expat upstream matter. Please reach out to conda-forge, instead.

**Comment by samuelchodur** [comment]
@hartwork, thanks for the insight. My system's anti-virus software does not have a problem with the official release version you linked. Thank you for your time and I agree, this is a problem with conda-forge.
