### ISSUE TITLE
CMake: Broken check for size_t and off_t (was: build failed on NetBSD9.3)

### ISSUE THREAD

**Issue by leleliu008** [libexpat/libexpat#854]
# reproduce steps

```bash
curl -LO https://github.com/libexpat/libexpat/releases/download/R_2_6_2/expat-2.6.2.tar.gz
tar xf expat-2.6.2.tar.gz
cd expat-2.6.2
cmake |
    -DEXPAT_BUILD_TOOLS=ON \
    -DEXPAT_BUILD_TESTS=OFF \
    -DEXPAT_BUILD_DOCS=OFF \
    -DEXPAT_BUILD_FUZZERS=OFF \
    -DEXPAT_BUILD_EXAMPLES=OFF \
    -DEXPAT_ENABLE_INSTALL=OFF \
    -S . \
    -B build.d
cmake --build build.d
```

# reported logs

```
In file included from /home/vagrant/expat-2.6.2/lib/xmlparse.c:66:0:
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected identifier or '(' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected identifier or '(' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected specifier-qualifier-list before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
/home/vagrant/expat-2.6.2/build.d/expat_config.h:120:15: error: expected declaration specifiers or '...' before numeric constant
 #define off_t 1
               ^
*** Error code 1

Stop.
make[2]: stopped in /home/vagrant/expat-2.6.2/build.d
*** Error code 1

Stop.
make[1]: stopped in /home/vagrant/expat-2.6.2/build.d
*** Error code 1

Stop.
make: stopped in /home/vagrant/expat-2.6.2/build.d
```

# cmake version is 3.28.1

# relatant code

https://github.com/libexpat/libexpat/blob/master/expat/ConfigureChecks.cmake#L49

**Comment by leleliu008** [comment]
my workaound:

```patch
--- ConfigureChecks.cmake.orign 2024-04-02 08:58:53.499986940 +0000
+++ ConfigureChecks.cmake       2024-04-02 09:21:47.648735869 +0000
@@ -46,12 +46,32 @@
 endif(WORDS_BIGENDIAN)
 
 if(HAVE_SYS_TYPES_H)
-    check_symbol_exists("off_t" "sys/types.h" off_t)
-    check_symbol_exists("size_t" "sys/types.h" size_t)
+    check_c_source_compiles("
+        #include <sys/types.h>
+        int main() {
+           off_t x;
+            return 0;
+        }"
+       HAVE_OFF_T)
+    check_c_source_compiles("
+        #include <sys/types.h>
+        int main() {
+           size_t x;
+            return 0;
+        }"
+       HAVE_SIZE_T)
 else(HAVE_SYS_TYPES_H)
+    set(HAVE_OFF_T 0)
+    set(HAVE_SIZE_T 0)
+endif(HAVE_SYS_TYPES_H)
+
+if (NOT HAVE_OFF_T)
     set(off_t "long")
+endif()
+
+if (NOT HAVE_SIZE_T)
     set(size_t "unsigned")
-endif(HAVE_SYS_TYPES_H)
+endif()
 
 check_c_source_compiles("
         #include <stdlib.h>  /* for NULL */
```

**Comment by leleliu008** [comment]
Actually, `size_t` usually define in `stddef.h`

Reference: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stddef.h.html

**Comment by hartwork** [comment]
Hi @leleliu008,

thanks for taking this upstream! I confirm that (1) the current…

```cmake
    check_symbol_exists("off_t" "sys/types.h" off_t)
    check_symbol_exists("size_t" "sys/types.h" size_t)
```

…is broken and (2) that `check_symbol_exists` is not the best use here.

Your demo above has good ideas, but some details will need adjustment. I can offer:
- a) that you create a pull request up here, I will do detailed review, and you'll have a commit in Expat history in the end, or
- b) that I create a pull request, you'll be in the reviewers seat, and the commit will be mine.

Which of the two do you prefer?

Best, Sebastian

**Comment by leleliu008** [comment]
@hartwork  I select `b`. I can test it for you.

**Comment by hartwork** [comment]
> @hartwork I select `b`. I can test it for you.

@leleliu008 deal, I'll ping again here when it's ready for review.

**Comment by leleliu008** [comment]
@hartwork I find that this project only has GitHub Actions workflows for testing GNU/Linux and macOS, are you intersting in adding more tests for other commonly used platforms (e.g. freebsd, netbsd, openbsd, etc) ? here is a reference https://github.com/universal-ctags/ctags/tree/master/.github/workflows

**Comment by leleliu008** [comment]
@hartwork there are many well-known and commonly used software (e.g. git, python, bsdtar) rely on this project, so I hope this project could test more platforms.

**Comment by hartwork** [comment]
@leleliu008 I don't have resources to add something like that myself at the moment but if you want to contribute in that area we can jump on a call sometime to make sure we find an approach that (1) fits what we find in requirement engineering and (2) is cheap enough to review with confidence in my spare time. Commit 8548bc03fdb887c8720f01e95440f1406bd15ffa comes to mind in this context, if you haven't seen it. Could be a project where it's possible to find a sponsor for your even. If you're interested, let's take the remainder to e-mail — my profile has the address. Thanks :beers:

**Comment by hartwork** [comment]
> @hartwork there are many well-known and commonly used software (e.g. git, python, libarchive) rely on this project

@leleliu008 FYI there is a list at https://libexpat.github.io/doc/users/ .

**Comment by leleliu008** [comment]
@hartwork I'm good at building softwares and writting GitHub Actions workflows but not good at english.

**Comment by hartwork** [comment]
> @hartwork I'm good at building softwares and writting GitHub Actions workflows but not good at english.

I understand. I'll get some other todos off my plate first, and then we can see how far we get with this in written communication.

**Comment by leleliu008** [comment]
@hartwork https://github.com/universal-ctags/ctags/tree/master/.github/workflows  most of these workflows are written by me, you can have a look at these when you have time, if you think you can accept then @ me here, I always online.

**Comment by hartwork** [comment]
@leleliu008 sounds like a plan.

I have a pull request #855 now, but it's tougher to get by CI (for good) than expected. Let's see.

**Comment by hartwork** [comment]
> > @hartwork I select `b`. I can test it for you.
> 
> @leleliu008 deal, I'll ping again here when it's ready for review.

@leleliu008 I believe pull request #855 is ready for review and testing now.

**Comment by leleliu008** [comment]
@hartwork OK, let me test it.

**Comment by leleliu008** [comment]
I tested with following instructions on Ubuntu-23.10, FreeBSD-13.2, NetBSD-9.3, OpenBSD-7.4, all are successfully built.

```bash
install -d libexpat
cd libexpat

git -c init.defaultBranch=master init
git remote add origin https://github.com/libexpat/libexpat
git fetch origin pull/855/head:pr-855
git checkout -B pr-855 pr-855

cd expat
cmake \
    -DEXPAT_BUILD_TOOLS=ON \
    -DEXPAT_BUILD_TESTS=OFF \
    -DEXPAT_BUILD_DOCS=OFF \
    -DEXPAT_BUILD_FUZZERS=OFF \
    -DEXPAT_BUILD_EXAMPLES=OFF \
    -DEXPAT_ENABLE_INSTALL=OFF \
    -S . \
    -B build.d
cmake --build build.d
```
