### ISSUE TITLE
Check UTF-16 encodings don't specify the wrong endianness

### ISSUE THREAD

**Issue by RMJ10** [libexpat/libexpat#86]
The function `processXmlDecl()` has some simple checks to make sure that the encoding in an XML declaration doesn't conflict with what the parser has already deduced:

```
if (newEncoding) {
  if (newEncoding->minBytesPerChar != encoding->minBytesPerChar) {
    evenPtr = encodingName;
    return XML_ERROR_INCORRECT_ENCODING;
  }
  encoding = newEncoding;
}
```

This will raise an error if the XML declaration specifies an 8-bit encoding when the parser has been reading a 16-bit encoding, or vice versa.  There is one more case that ought to be tested for, though; specifying UTF-16BE when the parser has been reading UTF-16LE and vice versa.  Unfortunately this isn't as easy as it sounds; the encoding structure does not include an endianness flag, and there's no easy way of identifying which encoding is which once control returns to `processXmlDecl()`.

The harder I look at this, the more of a nest of snakes it seems to be :-(

**Comment by hartwork** [comment]
>  There is one more case that ought to be tested for, though; specifying UTF-16BE when the parser has been reading UTF-16LE and vice versa.

Yes, please.

>  the encoding structure does not include an endianness flag

Can we check compare pointers against `little2_toUtf16` or `big2_toUtf16`?

PS: From look at this code
```
  if (streqci(buf, KW_UTF_16) && enc->minBytesPerChar == 2)
    return enc;
  i = getEncodingIndex(buf);
```
I believe that can be simplified to
```
  i = getEncodingIndex(buf);
```
as that covers `KW_UTF_16` as well.

**Comment by RMJ10** [comment]
> Can we check compare pointers against little2_toUtf16 or big2_toUtf16?

I'd rather compare encoding->utf8Convert with newEncoding->utf8Convert than explicitly involve the little2_ and big2_ functions.  Something like

```
if (newEncoding->minBytesPerChar == 2 && newEncoding->utf8Convert != encoding->utf8Convert) {
  /* whinge */
}
```

> PS: From a look at this code
> ```
>  if (streqci(buf, KW_UTF_16) && enc->minBytesPerChar == 2)
>    return enc;
>  i = getEncodingIndex(buf);
>```
>I believe that can be simplified to just
>```
>  i = getEncodingIndex(buf);
>```

I don't think so.  "UTF-16" on its own doesn't specify endianness.  What the check does is resolve "UTF-16" to whichever of "UTF-16LE" or "UTF-16BE" is actually being used, rather than picking an arbitrary endianness for "UTF-16" and potentially getting it wrong.

**Comment by hartwork** [comment]
> I'd rather compare encoding->utf8Convert with newEncoding->utf8Convert [..]

Why `utf8Convert` when it's with UTC-16? If find that confusing. Comparing `encoding` and `newEncoding` does not work?

> What the check does is resolve "UTF-16" to whichever of "UTF-16LE" or "UTF-16BE" is actually being used, rather than picking an arbitrary endianness for "UTF-16" and potentially getting it wrong.

Good point! I looked it up: Not exactly arbitrary, it would always be set to big endian:
```
static const ENCODING * const NS(encodings)[] = {
  &ns(latin1_encoding).enc,
  &ns(ascii_encoding).enc,
  &ns(utf8_encoding).enc,
  &ns(big2_encoding).enc, /* KW_UTF_16 goes here */
  &ns(big2_encoding).enc,
  &ns(little2_encoding).enc,
  &ns(utf8_encoding).enc /* NO_ENC */
};
```

**Comment by RMJ10** [comment]
> Why utf8Convert when it's with UTC-16? If find that confusing. Comparing encoding and newEncoding themselves does not work?

They do.  I had confused myself.  I'll fix that.

> I looked it up: Not exactly arbitrary, it would always be set to big endian

That's true.  I meant the choice of big endian was arbitrary (presumably what Windows uses?) and won't always be the right one.

**Comment by hartwork** [comment]
Hi!

I know it can be considered picky but I noticed that we have code
```
         eventPtr = encodingName;
         return XML_ERROR_INCORRECT_ENCODING;
```
in there twice now so I would like to propose that we merge the conditionals like this and resolve the code duplication:
```
       if ((newEncoding->minBytesPerChar != encoding->minBytesPerChar)
           || ((newEncoding->minBytesPerChar == 2) && (newEncoding != encoding))) {
         eventPtr = encodingName;
         return XML_ERROR_INCORRECT_ENCODING;
       }
```
While I wouldn't insist, I would like to see more braces that kill any potential questions about operator precedence with people reading the code, in general. If you're with that, let's start applied that for all new code. Also, please let's make the next version a pull request (which it is). Okay?

**Comment by RMJ10** [comment]
I prefer slightly fewer brackets than you do -- beyond a certain point I think they make things less readable.  I'm happy to use brackets to make the order of || and && clear, but I'd very much rather not put them round the individual equality/inequality tests.
