### ISSUE TITLE
Ubuntu trusty/14.04 does not support any sources of high quality entropy

### ISSUE THREAD

**Issue by sjackman** [libexpat/libexpat#88]
Any thoughts on why I'd be seeing this error message on Ubuntu 14?
See https://travis-ci.org/Linuxbrew/homebrew-core/builds/255089067#L1624

I've tried adding `CFLAGS=-DHAVE_SYSCALL_GETRANDOM`
which changed the error message to:
```
lib/xmlparse.c: In function ‘writeRandomBytes_getrandom’:
lib/xmlparse.c:760:17: error: ‘SYS_getrandom’ undeclared (first use in this function)
         syscall(SYS_getrandom, currentTarget, bytesToWrite, getrandomFlags);
```
See https://travis-ci.org/Linuxbrew/homebrew-core/builds/255142857#L1612

**Comment by sjackman** [comment]
I'm attempting to compile `expat` 2.2.2, and I didn't see this error with `expat` 2.2.1 on the same system.

**Comment by sjackman** [comment]
Ubuntu 14 has `glibc` 2.19.

**Comment by hartwork** [comment]
Hello Shaun,

Ubuntu 14 is in quite a sad state: There is not `getrandom` yet, not even the `syscall` version, and their libbsd is broken on top.

Options I see:
* Use `--with-libbsd` and a newer backport of libbsd
* Move on to a distribution less old than 3 years, e.g. 16.04 LTS
* Use `-DXML_POOR_ENTROPY` (only) if the related software does not face end users and end user input

What do you think?

**Comment by sjackman** [comment]
I'm packaging `expat` for Linuxbrew (http://linuxbrew.sh) so using a recent `libbsd` is an option. We plan to move from Ubuntu 14 to Ubuntu 16 on our CI system that builds the precompiled binaries later this year. The package is end-user facing. What, briefly, does `expat` use the entropy for, and what's the implication of using a poor source of entropy?
As I mentioned, `expat` 2.2.1 was working for us, so were we previously using a poor source of entropy?
My understanding is that `/dev/random` is a high-quality source of entropy (and `/dev/urandom` a poor one). Could you get the bits from reading `/dev/random`?

**Comment by hartwork** [comment]
> I'm packaging `expat` for Linuxbrew (http://linuxbrew.sh) so using a recent `libbsd` is an option.

Excellent!

> What, briefly, does `expat` use the entropy for, and what's the implication of using a poor source of entropy?

The entropy is used to seed the hash algorithm using during parsing. Better entropy means less vulnerability denial-of-service attacks from crafted Hash collisions.

> As I mentioned, `expat` 2.2.1 was working for us, so were we previously using a poor source of entropy?

Yes, you were.

> My understanding is that `/dev/random` is a high-quality source of entropy (and `/dev/urandom` a poor one). Could you get the bits from reading `/dev/random`?

Simplified, if we have a working libbsd availabe, its `arc4random_buf` answers that question for us without need for patching anything Expat. You can use `EXPAT_ENTROPY_DEBUG=1` (e.g. during `make check` but also when running `xmlwf`) to see entropy bits as they are used.

**Comment by sjackman** [comment]
A quick test on my local machine of building `expat` with `libbsd` 0.8.3 on Ubuntu 14 worked. I'm running it through CI now. Thanks for your help, Sebastian.

**Comment by hartwork** [comment]
Okay cool. I'm closing this ticket then.

**Comment by maxim-belkin** [comment]
CI succeeded, so now people can now install `expat` on Linux with a simple:

```
brew install expat
```

**Comment by xiangzhai** [comment]
:mips-interest
