### ISSUE TITLE
Does expat decodes an attribute value before calling the StartHandler?

### ISSUE THREAD

**Issue by pamoller** [libexpat/libexpat#908]
I'm asking because of https://github.com/pamoller/xmlformatter/issues/2 

Thx in advance

**Comment by hartwork** [comment]
Hi @pamoller,

(in XML terminology you seem to be referring to the [inclusion](https://www.w3.org/TR/2006/REC-xml-20060816/#included) of [predefined (general) entities](https://www.w3.org/TR/2006/REC-xml-20060816/#sec-predefined-ent) or any general entities (not just predefined ones) with regard to their [treatment as a "reference in attribute value"](https://www.w3.org/TR/2006/REC-xml-20060816/#entproc).)

Yes it does:

```console
# cd "$(mktemp -d)"
# git clone --depth 1 https://github.com/libexpat/libexpat
# cd libexpat/expat/
# cmake . && cmake --build .
# ./examples/outline <<<"<root k1='1 &lt; 2'/>"
root k1='1 < 2'
```

The examples code can also be browsed at https://github.com/libexpat/libexpat/blob/master/expat/examples/outline.c .

If xmlformatter does a full round trip — parse and re-serialize — it has to [escape at least three characters](https://www.w3.org/TR/2006/REC-xml-20060816/#NT-AttValue) to produce [well-formed](https://www.w3.org/TR/2006/REC-xml-20060816/#sec-well-formed) XML output.

Does that answer the question?

**Comment by pamoller** [comment]
Ok, predefined entity references like &lt; must be replaced by the parser and for this reason the original reference has to be escaped before parser invocation?

**Comment by hartwork** [comment]
Update: @pamoller and I had a quick call just now, and the question is considered answered. Closing…
