### ISSUE TITLE
Reg build failures in doc folder in expat 2.6.3 version

### ISSUE THREAD

**Issue by anjuvmenon** [libexpat/libexpat#916]
Hi Team,
This message is regarding the ongoing issue that I recently reported regarding the expat build failure in the doc folder for version 2.6.3[ expat-2.6.3.tar.gz] (https://github.com/libexpat/libexpat/issues/909). I want to clarify that this was not a bot request. 
 I have attached the detailed bug report here:
[expatdocbuilderror.txt](https://github.com/user-attachments/files/17538408/expatdocbuilderror.txt)

The main issue we encountered was while executing "make -C doc" inside the expat folder:
``` rm -f xmlwf.1 test "x" != x && xmlwf.xml make: *** [Makefile:607: xmlwf.1] Error 1 make: Leaving directory '/tmp/expat/doc' ```

Upon reviewing the Makefile.am, I noticed the following where DOCBOOK_TO_MAN macro is NULL, So I am not sure whether this is causing the make error.

``` if WITH_MANPAGE
dist_man_MANS = xmlwf.1

xmlwf.1: xmlwf.xml
        -rm -f $@
        test "x$(DOCBOOK_TO_MAN)" != x && $(DOCBOOK_TO_MAN) $<
        test -f $@ || mv XMLWF.1 $@
endif```
So inorder to avoid this error we went ahead and modified the configure.ac as below.
![image](https://github.com/user-attachments/assets/b166473e-b896-4607-851c-c8b7a0417285)
AS_IF([test -f "${srcdir}"/doc/xmlwf.1],
  [AM_CONDITIONAL(WITH_MANPAGE, [false])
   AS_IF([test "x$with_docbook" = xno -o "x${DOCBOOK_TO_MAN}" = x],
     [AM_CONDITIONAL(WITH_PREBUILT_MANPAGE, [false])
      AM_CONDITIONAL(WITH_DISTRIBUTABLE_MANPAGE, [false])],
     [AM_CONDITIONAL(WITH_PREBUILT_MANPAGE, [false])
      AM_CONDITIONAL(WITH_DISTRIBUTABLE_MANPAGE, [false])])
   ],
  [AS_IF([test "x$with_docbook" != xno -a "x${DOCBOOK_TO_MAN}" != x],
     [AM_CONDITIONAL(WITH_MANPAGE, [false])
      AM_CONDITIONAL(WITH_DISTRIBUTABLE_MANPAGE, [false])],
     [AM_CONDITIONAL(WITH_MANPAGE, [false])
      AM_CONDITIONAL(WITH_DISTRIBUTABLE_MANPAGE, [false])])
   AM_CONDITIONAL(WITH_PREBUILT_MANPAGE, [false])])
After making the above changes, doc build is passing without any issues.
We would like to know if the above changes will have any impact on the functionality of the expat library since we are bundling it in our source code.

**Comment by hartwork** [comment]
Hi @anjuvmenon,

based on the [log that you shared](https://github.com/user-attachments/files/17538408/expatdocbuilderror.txt) I can say that (1) not passing `--without-docbook` and (2) output…

```
checking for docbook2x-man... no
checking for db2x_docbook2man... no
checking for docbook2man... no
checking for docbook-to-man... no
```

…from configure and (3) your [stated use of the official `make dist` tarball](https://github.com/libexpat/libexpat/issues/909#issuecomment-2406629916) with file `doc/xmlwf.1` present means that in `configure` we end up with situation…
- `with_docbook` set to default `check`,
- `DOCBOOK_TO_MAN` is the empty string,
- `WITH_MANPAGE` is `true` (from line 365)
- `WITH_PREBUILT_MANPAGE` is true (from line 367)
- `WITH_DISTRIBUTABLE_MANPAGE` is false (from line 368)

For `doc/Makefile` that means that rule `xmlwf.1: xmlwf.xml` will only try to rebuild (and fail) if file `xmlwf.xml` is more recent than `xmlwf.1` which is not the case right after unpacking — see below — or absent (but you said to use official tarballs):

```console
# tar xf expat-2.6.3.tar.gz 
# expat-2.6.3/
# ls -al doc/xmlwf.*
-rw-r--r-- 1 user123 user123 10947 Sep  4 12:42 doc/xmlwf.1
-rw-r--r-- 1 user123 user123 18994 Sep  4 12:37 doc/xmlwf.xml
                                             ^^
```

So the code that you report as broken would not even be executed with proper timestamps.  My guess is that your bundling breaks the timestamps constraint "xmlwf.1 more recent than xmlwf.xml".  It should be noted that Git does not preserve timestamps in case there is a layer of Git involved with bundling.  In that case the fix would be to either install one of the four supported flavors of `docbook-to-man` or to delete file `doc/xmlwf.1` from Git or do `touch doc/xmlwf.1` for a more recent timestamp somewhere in your toolchain.

I'm closing as "answered in detail" and "works as expected for supported cases".

Best, Sebastian
