### ISSUE TITLE
Changes in XML parser from expat version before 2.6.3?

### ISSUE THREAD

**Issue by RashmiRamanna** [libexpat/libexpat#929]
Hi,

I am currently using latest version of expat that is 2.6.4 and one of my test is failing which was passing earlier with expat version 2.5.0.

my ex. code snippet is as below:

policy.xml content is as below ->
```
<abc>
    <def>
       <ghi href=1111111 />
    </def>
</abc>
```
And I am trying to find the node "abc/def/ghi" in the file policy.xml which is failing.

**Comment by hartwork** [comment]
Hi @RashmiRamanna!

First, `href=1111111` is not well-formed XML, you're missing quotes there — single or double.

The answer to you question could be pull request #789. I suggest you do a `git bisect` to find out for sure. If you have never used `git bisect` before, this is a great chance to see its value in action.

**Comment by hartwork** [comment]
> my ex. code snippet is as below:

PS: Did you intend but forget to include C code in your post?

**Comment by hartwork** [comment]
Closing as "neither a complete question nor a complete bug report"…
