### ISSUE TITLE
Possibly wrong comment marker in .def files

### ISSUE THREAD

**Issue by vszakats** [libexpat/libexpat#93]
I'm not sure if this was intentional, but `XML_GetAttributeInfo` is commented out in the Windows `.def` files, while the comment says it was added @ version 2.1.1, the function is indeed a valid public libexpat function and it even has an export ordinal:

```diff
diff --git a/expat/lib/libexpat.def b/expat/lib/libexpat.def
index 79b0491..7cfc67f 100644
--- a/expat/lib/libexpat.def
+++ b/expat/lib/libexpat.def
@@ -72,5 +72,5 @@ EXPORTS
   XML_ResumeParser @64
   XML_GetParsingStatus @65
 ; added with version 2.1.1
-; XML_GetAttributeInfo @66
+  XML_GetAttributeInfo @66
   XML_SetHashSalt @67@
diff --git a/expat/lib/libexpatw.def b/expat/lib/libexpatw.def
index 79b0491..7cfc67f 100644
--- a/expat/lib/libexpatw.def
+++ b/expat/lib/libexpatw.def
@@ -72,5 +72,5 @@ EXPORTS
   XML_ResumeParser @64
   XML_GetParsingStatus @65
 ; added with version 2.1.1
-; XML_GetAttributeInfo @66
+  XML_GetAttributeInfo @66
   XML_SetHashSalt @67@
```

**Comment by vszakats** [comment]
Well, the function is public but it's only included in the lib if `XML_ATTR_INFO` is #defined, which it isn't by default. Not sure what the intention is, so closing.

**Comment by RMJ10** [comment]
@kwaclaw can you remember why this is commented?

**Comment by hartwork** [comment]
```console
# git blame lib/libexpat.def | fgrep XML_GetAttributeInfo
f08b5b72 (Karl Waclawek      2012-05-06 00:10:00 +0000 75) ; XML_GetAttributeInfo @66
```
yields f08b5b72d1afce6501b74b339f6681d33395e682 which points to https://sourceforge.net/p/expat/bugs/501/ where I find:
> I can only add it as commented out, as this would break the default build which excludes this function
