### ISSUE TITLE
Add a way to skip/drop/ignore invalid non-xml character during parsing

### ISSUE THREAD

**Issue by biodranik** [libexpat/libexpat#931]
It would be great to add a way of skipping any invalid characters in the parsed XML stream (like 0x00, 0x01, etc.)

That will simplify the processing of unknown input data, esp. in cases like this one: https://github.com/organicmaps/organicmaps/issues/3837

**Comment by hartwork** [comment]
These characters violate XML well-formedness constraints and the XML spec is clear that they [must be treated as fatal errors](https://www.w3.org/TR/2006/REC-xml-20060816/#sec-terminology). So it would explicitly violate the XML spec and thus is not going to happening. Thanks for your understanding. Closing as wontfix…
