### ISSUE TITLE
[2.6.3] `.dylib` references in `cmake/autotools/expat-noconfig____macos.cmake.in` do not match reality of Darwin builds

### ISSUE THREAD

**Issue by brook-milligan** [libexpat/libexpat#935]
On Darwin, the installed expat shared library includes only the major
version number, not minor version and patch, in the name.  The
corresponding cmake check, however, looks for the full name with all
three parts and fails.

The same problem occurs on Windows and is discussed here, even
mentioning that Darwin likely has the same issue:

    https://github.com/libexpat/libexpat/issues/485

For some reason, the fix (removing minor and patch versions) was
applied for Windows but not for Darwin.

A patch resolving this is the following:

```diff
--- cmake/autotools/expat-noconfig__macos.cmake.in.orig	2023-08-26 12:27:53.000000000 +0000
+++ cmake/autotools/expat-noconfig__macos.cmake.in
@@ -8,12 +8,12 @@ set(CMAKE_IMPORT_FILE_VERSION 1)
 # Import target "expat::expat" for configuration "NoConfig"
 set_property(TARGET expat::expat APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
 set_target_properties(expat::expat PROPERTIES
-  IMPORTED_LOCATION_NOCONFIG "${_IMPORT_PREFIX}/@LIBDIR_BASENAME@/libexpat.@SO_MAJOR@.@SO_MINOR@.@SO_PATCH@.dylib"
+  IMPORTED_LOCATION_NOCONFIG "${_IMPORT_PREFIX}/@LIBDIR_BASENAME@/libexpat.@SO_MAJOR@.dylib"
   IMPORTED_SONAME_NOCONFIG "@rpath/libexpat.@SO_MAJOR@.dylib"
   )
 
 list(APPEND _cmake_import_check_targets expat::expat )
-list(APPEND _cmake_import_check_files_for_expat::expat "${_IMPORT_PREFIX}/@LIBDIR_BASENAME@/libexpat.@SO_MAJOR@.@SO_MINOR@.@SO_PATCH@.dylib" )
+list(APPEND _cmake_import_check_files_for_expat::expat "${_IMPORT_PREFIX}/@LIBDIR_BASENAME@/libexpat.@SO_MAJOR@.dylib" )
 
 # Commands beyond this point should not need to know the version.
 set(CMAKE_IMPORT_FILE_VERSION)
```

**Comment by hartwork** [comment]
Hi @brook-milligan,

I understand your point, but there is CI that is comparing what Expat does manually in these very files to what CMake would generate on macOS and those two outputs agree, so this will need a closer look before deviating from what CMake does. The related CI is at https://github.com/libexpat/libexpat/blob/master/.github/workflows/autotools-cmake.yml and the latest run as of today is at https://github.com/libexpat/libexpat/actions/runs/12308752153/job/34354639625 .

What do you think?

**Comment by brook-milligan** [comment]
> On Dec 15, 2024, at 09:26, Sebastian Pipping ***@***.***> wrote:
> 
> I understand your point, but there is CI that is comparing what Expat does manually in these very files to what CMake would generate on macOS and those two outputs agree, so this will need a closer look before deviating from what CMake does. The related CI is at https://github.com/libexpat/libexpat/blob/master/.github/workflows/autotools-cmake.yml and the latest run as of today is at https://github.com/libexpat/libexpat/actions/runs/12308752153/job/34354639625 .
> What do you think?

Indeed, the CI installed libraries are the same and they are the same as for me:

	libexpat.1.dylib
        libexpat.a
        libexpat.dylib -> libexpat.1.dylib

The problem is not these files installed by expat, but rather the use (i.e., contents) of the installed file lib/cmake/expat-2.6.3/expat-noconfig.cmake (2.6.4 for you).  Other packages using that file to discover the expat installed libraries will fail, because they will be looking for versions of libexpat.MAJOR.MINOR.PATCH.dylib, not libexpat.MAJOR.dylib as is installed.  

This is what issue 485 was addressing for Windows, which also installs the library with only the major version number.  That issue also mentioned that MacOS would have the same problem for the same reason, but apparently that was missed when the fix was committed and the longer name was assumed on MacOS.

I know that fixing the contents of lib/cmake/expat-2.6.3/expat-noconfig.cmake does allow an expat-using package to build, whereas without it fails.

Cheers,
Brook

**Comment by hartwork** [comment]
Hi @brook-milligan,

I think you potentially misunderstood my point: that recursive diff includes those CMake text files that we are talking about. I'm happy to investigate this more (and have an idea how) but I should mention that I don't have access to macOS outside of GitHub Actions CI.

**Comment by brook-milligan** [comment]
> On Dec 15, 2024, at 10:23, Sebastian Pipping ***@***.***> wrote:
> 
> I think you potentially misunderstood my point: that recursive diff includes those CMake text files that we are talking about. I'm happy to investigate this more (and have an idea how) but I should mention that I don't have access to macOS outside of GitHub Actions CI.

I think we are looking at this from two different perspectives.  It seems true that your CI comparison demonstrates that both build systems install the same file contents for expat.  I do not doubt that.

However, I don’t think you are testing whether the contents of the files will in fact work for packages that use the expat-installed cmake files to discover the installed expat library files.  Thus, it is possible for both build systems to install incorrect, but identical, files.

I find that on MacOS the contents of the files are incorrect because they search for a library with the full name, i.e., all three version components, but expat installs libraries with only the major version number in the name.

Thus, the contents of cmake/autotools/expat-noconfig__macos.cmake.in should be similar to the Windows version, because in that case too the library is also installed with only the major version number in the name.

Issue 485 fixed this for Windows, but not for MacOS.  The patch I sent fixed it for MacOS.

Cheers,
Brook

**Comment by hartwork** [comment]
@brook-milligan it was not known previously that the Autotools and CMake build systems are producing different results when it comes to `*.dylib` file installation, hence having them in sync was assumed to assure correct operation as a side effect, but being in sync was the key objective giving that these files are trying to mimic original CMake as closely as possible. Based on what I can see in CI after adding some debugging output…

```
build_autotools/ROOT/usr/local/lib123/libexpat.1.dylib
build_autotools/ROOT/usr/local/lib123/libexpat.dylib
build_cmake/ROOT/usr/local/lib123/libexpat.1.10.0.dylib  !!!
build_cmake/ROOT/usr/local/lib123/libexpat.1.dylib
build_cmake/ROOT/usr/local/lib123/libexpat.dylib
```

…I confirm that Autotools is not installing the `libexpat.1.10.0.dylib` file which causes the problem. So we'll need another block like this in CI, except for macOS…

https://github.com/libexpat/libexpat/blob/192af39be0458273f0a8ac407e4a848d52f484d6/.github/workflows/autotools-cmake.yml#L119-L129

…or need to teach Autotools to create the file, also.

I'll get to either of that soon-ish.

**Comment by brook-milligan** [comment]
> On Dec 15, 2024, at 11:13, Sebastian Pipping ***@***.***> wrote:
> 
> @brook-milligan it was not known previously that the Autotools and CMake build systems are producing different results when it comes to *.dylib file installation, hence having them in sync was assumed to assure correct operation as a side effect, but being in sync was the key objective giving that these files are trying to mimic original CMake as closely as possible. Based on what I can see in CI after adding some debugging output…
> build_autotools/ROOT/usr/local/lib123/libexpat.1.dylib
> build_autotools/ROOT/usr/local/lib123/libexpat.dylib
> build_cmake/ROOT/usr/local/lib123/libexpat.1.10.0.dylib !!!
> build_cmake/ROOT/usr/local/lib123/libexpat.1.dylib
> build_cmake/ROOT/usr/local/lib123/libexpat.dylib
> 
> …I confirm that Autotools is not installing the libexpat.1.10.0.dylib file which causes the problem. So we'll need another block like this in CI, except for macOS…
> https://github.com/libexpat/libexpat/blob/192af39be0458273f0a8ac407e4a848d52f484d6/.github/workflows/autotools-cmake.yml#L119-L129
> …or need to teach Autotools to create the file, also.
> I'll get to either of that soon-ish.

Thank you very much.  I appreciate your help.

Until this is fixed and for earlier releases of expat, I assume that the correct patch is to modify the cmake file to search for the correct installed file (as in my original patch).  Do you agree?

Cheers,
Brook

**Comment by hartwork** [comment]
@brook-milligan thanks for the idea about `-E`, it seems to work well in practice :tada: I have created pull request #937 now.

Btw was this in context of Homebrew, MacPorts, Gentoo Alt, Fink, a single setup, …?

**Comment by brook-milligan** [comment]
> On Dec 17, 2024, at 11:34, Sebastian Pipping ***@***.***> wrote:
> 
> @brook-milligan thanks for the idea about -E, it seems to work well in practice 🎉 I have created pull request #937 now.

Thanks.  I hope it works.

Do I understand correctly that (i) you commited the fix to expat-noconfig__macos.cmake.in so that it finds the correct file on Darwin and that (ii) now your CI handles the difference in file naming correctly?

> Btw was this in context of Homebrew, MacPorts, Gentoo Alt, Fink, a single setup, …?

I was trying to fix the expat package in pkgsrc.  The driver was really me trying to fix another package in pkgsrc (gdal-lib) that depends on expat in a way that exposed the problem in the expat-installed cmake file derived from expat-noconfig__macos.cmake.in.

Thanks for working on this.  I appreciate your help.

Cheers,
Brook

**Comment by hartwork** [comment]
> Thanks. I hope it works. Do I understand correctly that (i) you commited the fix to expat-noconfig__macos.cmake.in so that it finds the correct file on Darwin and that (ii) now your CI handles the difference in file naming correctly?

@brook-milligan yes: the CI asserts further done that the CMake files installed by CMake and Autotools are identitical and now that they now longer are, the known difference is patched away live before making the comparison so that then the comparison passes.

>> Btw was this in context of Homebrew, MacPorts, Gentoo Alt, Fink, a single setup, …?
>
> I was trying to fix the expat package in pkgsrc. The driver was really me trying to fix another package in pkgsrc (gdal-lib) that depends on expat in a way that exposed the problem in the expat-installed cmake file derived from expat-noconfig__macos.cmake.in.

I see, thanks for elaborating! I thought https://pkgsrc.se/textproc/expat was only NetBSD but good to know, I read it's targetting a few other things more.
