### ISSUE TITLE
[2.2.{1,2}] Can't find high quality entropy on Debian 8/jessie

### ISSUE THREAD

**Issue by rossburton** [libexpat/libexpat#97]
Debian 8 doesn't have glibc 2.25 but it does have a modernish kernel (4.9) with jessie-backports.  However this means the syscall number check also fails as the lilbc that would provide SYS_getrandom is glibc 2.19.

As the kernel does support it passing the right hardcoded number works just fine (318 for x86-64).

(note that we're seeing the same failures on older centos builders).

**Comment by hartwork** [comment]
Is installing `libbsd-dev` (of jessie or a backport) and using `./configure --with-libbsd` an option to you?
Else, is using a backport of glibc with `SYS_getrandom` in option?

**Comment by rossburton** [comment]
We're building expat as part of an entire Linux system build from the ground up (yoctoproject.org, if you're curious) so asking users to upgrade glibc isn't an option, and I was hoping to not mandate libbsd-dev for the few people that hit this problem.

FWIW I suspect our approach is going to be allowing low quality entropy as it is highly unlikely that the users of expat in this environment will care.

**Comment by hartwork** [comment]
I was in touch with Jussi and Dengke for upgrading Yocto to Expat 2.2.1 that didn't have that check for lack of any supported high quality entropy provider that 2.2.2 added. So I wasn't aware of that detail back then.

`libbsd-dev` would be the build time dependency, runtime would be `libbsd${number}`, if that detaila matters. I would expect libbsd to read `/dev/urandom` in your scenario which should give better entropy than what you get with defining `XML_POOR_ENTROPY`. You can watch the entropy as it flies in with `EXPAT_ENTROPY_DEBUG=1` to get a feeling for the difference of these two scenarios: With `XML_POOR_ENTROPY` you should see a lot more zeros in there, i.e. fewer bits of entropy. So if libbsd is acceptable for a dependency, my vote for relying on that. What do you think?

**Comment by hartwork** [comment]
Hello Ross,

a quick update: Git `master` has code to read `/dev/urandom` for systems like Debian jessie by now and you should be able to run `./buildconf.sh && ./configure && make check` without errors now.

Closing, please re-open as needed.
